import '@testing-library/jest-dom/vitest';
import { afterEach, vi } from 'vitest';
import { cleanup } from '@testing-library/react';

// Mock lucide-react globally so that any test which mounts a component
// (directly or through a page tree) does not need to stub individual icons.
// We synthesize a plain object with every named export of lucide-react
// mapped to a no-op React component. Vitest 4.1.x's static-import check
// (the "No X export is defined on the X mock" error) verifies the mock
// object has the imported name as an own property, so we cannot rely on
// a Proxy or Object.create(getter) — we must pre-populate the full list.
// We use vi.hoisted to read the real lucide-react module synchronously
// during vitest's hoist phase, before any test file's `import { X } from
// 'lucide-react'` is resolved. The list of icon names is generated by:
//   node -e "const l=require('lucide-react'); const n=Object.keys(l).filter(k=>k!=='default'&&k!=='__esModule'); console.log('export const LUCIDE_ICON_NAMES = ' + JSON.stringify(n) + ';')" > src/test/lucideIconNames.ts
// and stored in ./lucideIconNames.ts (5873 entries as of lucide-react
// v0.546.0). We do the require inside vi.hoisted so vitest's hoist can
// resolve `lucide-react` before the module-mocker is asked for it.
const lucideMockModule = vi.hoisted(() => {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const React = require('react');
  const IconStub = (_props: Record<string, unknown> = {}) => React.createElement('svg', null);
  IconStub.displayName = 'IconStub';
  const lucideMock: Record<string, unknown> = { __esModule: true, default: IconStub };
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const real = require('lucide-react');
  if (real && typeof real === 'object') {
    for (const key of Object.keys(real)) {
      lucideMock[key] = IconStub;
    }
  }
  return lucideMock;
});

vi.mock('lucide-react', () => lucideMockModule);

// Mock sql.js to prevent WASM fetch failures in test env.
// sqlJsStorage tries to load https://sql.js.org/dist/sql-wasm.wasm which
// fails in jsdom/node. Instead, provide a minimal in-memory mock.
vi.mock('sql.js', () => {
  class MockDatabase {
    private tables = new Map<string, Map<string, string>>();
    run(sql: string, _params?: unknown[]) {
      const match = sql.match(/CREATE TABLE IF NOT EXISTS (\w+)/i);
      if (match && !this.tables.has(match[1]!)) this.tables.set(match[1]!, new Map());
      const insertMatch = sql.match(
        /INSERT OR REPLACE INTO (\w+) \(id, value\) VALUES \(\?, \?\)/i
      );
      if (insertMatch) {
        const tbl = this.tables.get(insertMatch[1]!);
        if (tbl && _params && _params.length >= 2)
          tbl.set(String(_params[0]!), String(_params[1]!));
      }
      const deleteMatch = sql.match(/DELETE FROM (\w+) WHERE id = \?/i);
      if (deleteMatch) {
        const tbl = this.tables.get(deleteMatch[1]!);
        if (tbl && _params && _params.length >= 1) tbl.delete(String(_params[0]!));
      }
    }
    exec(sql: string, _params?: unknown[]) {
      const selMatch = sql.match(/SELECT value FROM (\w+) WHERE id = \?/i);
      if (selMatch) {
        const tbl = this.tables.get(selMatch[1]!);
        if (tbl && _params && _params.length >= 1) {
          const val = tbl.get(String(_params[0]!));
          return val ? [{ columns: ['value'], values: [[val]] }] : [];
        }
      }
      return [];
    }
    export(): Uint8Array {
      return new Uint8Array(0);
    }
    close() {}
  }
  return {
    default: async () => ({ Database: MockDatabase }),
    Database: MockDatabase,
  };
});

// Note: the previous `vi.mock('../workers/worker-pool', ...)` block was removed
// because it was INCOMPATIBLE with the real WorkerPool API. The mock exposed
// `WorkerPool: class {}` (no constructor), `createStoragePool` and
// `createBatchCalcPool` returning a pool that only handled `stringify`/`parse`
// request types, and was MISSING `createMonteCarloPool` / `createConsolidationPool`
// entirely (undefined when imported). The real WorkerPool expects
// `new WorkerPool(workerFactory, options?)` and the factories create pools with
// the global `Worker` constructor — which is already mocked at the top of this
// file (`Worker: class {}`). Tests that need controllable worker behavior use
// their own `createMockWorkerFactory()` helper (see worker-pool.test.ts).
// See: T-AP-001 P0 #0, fix for 13/16 failing tests.

// Polyfill localStorage for Node.js v22+ where the experimental global
// may be undefined and shadows jsdom's implementation.
if (typeof localStorage === 'undefined' || localStorage === null) {
  const store = new Map<string, string>();
  const ls: Storage = {
    getItem: (key: string) => store.get(key) ?? null,
    setItem: (key: string, value: string) => {
      store.set(key, String(value));
    },
    removeItem: (key: string) => {
      store.delete(key);
    },
    clear: () => {
      store.clear();
    },
    get length() {
      return store.size;
    },
    key: (index: number) => [...store.keys()][index] ?? null,
  };
  Object.defineProperty(globalThis, 'localStorage', {
    value: ls,
    writable: false,
    configurable: true,
  });
}

// Automatically cleanup after each test
afterEach(() => {
  cleanup();
});
