import '@testing-library/jest-dom/vitest';
import { afterEach, vi } from 'vitest';
import { cleanup } from '@testing-library/react';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

// Initialize i18next for tests so that components using useTranslation() can
// render. We use English (en) with explicit resources for keys referenced by
// tests, so t() returns the English text instead of the raw key.
// Add new keys here as tests demand them.
i18n
  .use(initReactI18next)
  .init({
    lng: 'en',
    fallbackLng: 'en',
    defaultNS: 'translation',
    ns: ['translation'],
    resources: {
      en: {
        translation: {
          'drivers.notConfigured': 'No drivers configured',
          'nav.dashboard': 'Dashboard',
          'nav.analysis': 'Analysis',
          'nav.budgeting': 'Budgeting',
          'nav.forecasting': 'Forecasting',
          'nav.modeling': 'Modeling',
          'nav.scenarios': 'Scenarios',
          'nav.simulation': 'Simulation',
          'nav.ai': 'AI',
          'nav.dataManagement': 'Data Management',
          'nav.nlp': 'NLP',
          'nav.tasks': 'Tasks',
          'nav.settings': 'Settings',
          'nav.help': 'Help',
          'nav.search': 'Search',
          'sidebar.sections.main': 'Main',
          'sidebar.sections.analysis': 'Analysis',
          'sidebar.sections.industries': 'Industries',
          'sidebar.sections.management': 'Management',
          'onboarding.welcome.title': 'Welcome to FinPlan Pro',
          'onboarding.welcome.description': 'Get started with financial planning',
          'onboarding.welcome.start': 'Start Setup',
          'onboarding.steps.welcome': 'Welcome',
          'onboarding.steps.company': 'Company',
          'onboarding.steps.data': 'Data',
          'onboarding.steps.review': 'Review',
          'onboarding.steps.done': 'Done',
          'onboarding.setup.title': 'Company Setup',
          'onboarding.setup.companyName': 'Company Name',
          'onboarding.setup.companyNamePlaceholder': 'Enter company name',
          'onboarding.setup.sector': 'Industry Sector',
          'onboarding.setup.fiscalYear': 'Fiscal Year',
          'onboarding.setup.fiscalYearStart': 'Fiscal Year Start Month',
          'onboarding.setup.baseCurrency': 'Base Currency',
          'onboarding.import.title': 'Import Data',
          'onboarding.import.description': 'Import your financial data',
          'onboarding.import.skip': 'Skip Import',
          'onboarding.review.title': 'Review',
          'onboarding.review.empty': 'No data imported',
          'onboarding.finish.title': 'Setup Complete',
          'onboarding.finish.description': 'You are all set to start using FinPlan Pro',
          'onboarding.finish.confirm': 'Confirm',
          'onboarding.finish.goDashboard': 'Go to Dashboard',
          'onboarding.finish.nextSteps.viewDashboard': 'View your dashboard',
          'onboarding.finish.nextSteps.createBudget': 'Create your first budget',
          'onboarding.finish.nextSteps.generateReports': 'Generate financial reports',
          'buttons.continue': 'Continue',
          'buttons.back': 'Back',
          'forms.date': 'Date',
          'forms.account': 'Account',
          'forms.amount': 'Amount',
        },
      },
    },
    interpolation: { escapeValue: false },
    returnEmptyString: false,
  })
  .catch(() => {
    // ignore init errors in test environment
  });

// Mock lucide-react globally so that any test which mounts a component
// (directly or through a page tree) does not need to stub individual icons.
// Vitest 4.1.x's static-import check (the "No X export is defined on the X
// mock" error) verifies the mock object has each imported name as an own
// property. We use a pre-baked list of every named export of lucide-react
// (5873+ entries, generated by:
//   node -e "const l=require('lucide-react'); const n=Object.keys(l).filter(k=>k!=='default'&&k!=='__esModule'&&!k.startsWith('Lucide')); require('fs').writeFileSync('src/test/allLucideIcons.cjs','module.exports = { ALL_LUCIDE_ICONS: ' + JSON.stringify(n) + ' };\n');"
// and saved in ./allLucideIcons.cjs). See T-AP-001 P0 #0.
const lucideMockModule = vi.hoisted(() => {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const React = require('react');
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { ALL_LUCIDE_ICONS } = require('./allLucideIcons.cjs') as {
    ALL_LUCIDE_ICONS: readonly string[];
  };
  const IconStub = (_props: Record<string, unknown> = {}) => React.createElement('svg', null);
  IconStub.displayName = 'IconStub';
  const lucideMock: Record<string, unknown> = { __esModule: true, default: IconStub };
  for (const name of ALL_LUCIDE_ICONS) {
    lucideMock[name] = IconStub;
  }
  return lucideMock;
});

vi.mock('lucide-react', () => lucideMockModule);

// Mock @json-render/core and @json-render/react. The real modules require a
// properly-typed Schema object to call `defineCatalog(schema, catalog)`.
// Most tests that import GenerativeDashboard (the only consumer) just want
// to render a component that doesn't crash; they don't exercise the AI
// renderer. Provide a no-op catalog and a passthrough renderer.
vi.mock('@json-render/core', () => ({
  defineCatalog: (_schema: unknown, catalog: unknown) => catalog,
  defineSchema: () => ({
    createCatalog: (catalog: unknown) => catalog,
  }),
  defineDirective: () => ({}),
  buildUserPrompt: () => '',
  validateSpec: () => ({ valid: true, issues: [] }),
  Spec: class {},
  StateModel: class {},
  JsonPatch: class {},
  deepMergeSpec: (a: unknown, b: unknown) => ({
    ...((a as object) || {}),
    ...((b as object) || {}),
  }),
  autoFixSpec: (s: unknown) => s,
  runValidation: () => ({ valid: true, issues: [] }),
  runValidationCheck: () => ({ valid: true, issues: [] }),
  evaluateVisibility: () => true,
  resolvePropValue: <T>(v: T) => v,
  resolveElementProps: <T>(p: T) => p,
  resolveBindings: <T>(v: T) => v,
  visibility: { AndCondition: {}, OrCondition: {} },
  check: () => ({ valid: true, issues: [] }),
}));

vi.mock('@json-render/react', () => ({
  Renderer: ({ children }: { children?: React.ReactNode }) =>
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    require('react').createElement('div', null, children),
}));

// Mock sql.js to prevent WASM fetch failures in test env.
// sqlJsStorage tries to load https://sql.js.org/dist/sql-wasm.wasm which
// fails in jsdom/node. Instead, provide a minimal in-memory mock.
vi.mock('sql.js', () => {
  class MockDatabase {
    private tables = new Map<string, Map<string, string>>();
    run(sql: string, _params?: unknown[]) {
      const match = sql.match(/CREATE TABLE IF NOT EXISTS (\w+)/i);
      if (match && !this.tables.has(match[1]!)) this.tables.set(match[1]!, new Map());
      const insertMatch = sql.match(
        /INSERT OR REPLACE INTO (\w+) \(id, value\) VALUES \(\?, \?\)/i
      );
      if (insertMatch) {
        const tbl = this.tables.get(insertMatch[1]!);
        if (tbl && _params && _params.length >= 2)
          tbl.set(String(_params[0]!), String(_params[1]!));
      }
      const deleteMatch = sql.match(/DELETE FROM (\w+) WHERE id = \?/i);
      if (deleteMatch) {
        const tbl = this.tables.get(deleteMatch[1]!);
        if (tbl && _params && _params.length >= 1) tbl.delete(String(_params[0]!));
      }
    }
    exec(sql: string, _params?: unknown[]) {
      const selMatch = sql.match(/SELECT value FROM (\w+) WHERE id = \?/i);
      if (selMatch) {
        const tbl = this.tables.get(selMatch[1]!);
        if (tbl && _params && _params.length >= 1) {
          const val = tbl.get(String(_params[0]!));
          return val ? [{ columns: ['value'], values: [[val]] }] : [];
        }
      }
      return [];
    }
    export(): Uint8Array {
      return new Uint8Array(0);
    }
    close() {}
  }
  return {
    default: async () => ({ Database: MockDatabase }),
    Database: MockDatabase,
  };
});

// Note: the previous `vi.mock('../workers/worker-pool', ...)` block was removed
// because it was INCOMPATIBLE with the real WorkerPool API. The mock exposed
// `WorkerPool: class {}` (no constructor), `createStoragePool` and
// `createBatchCalcPool` returning a pool that only handled `stringify`/`parse`
// request types, and was MISSING `createMonteCarloPool` / `createConsolidationPool`
// entirely (undefined when imported). The real WorkerPool expects
// `new WorkerPool(workerFactory, options?)` and the factories create pools with
// the global `Worker` constructor — which is already mocked at the top of this
// file (`Worker: class {}`). Tests that need controllable worker behavior use
// their own `createMockWorkerFactory()` helper (see worker-pool.test.ts).
// See: T-AP-001 P0 #0, fix for 13/16 failing tests.

// Polyfill localStorage for Node.js v22+ where the experimental global
// may be undefined and shadows jsdom's implementation.
if (typeof localStorage === 'undefined' || localStorage === null) {
  const store = new Map<string, string>();
  const ls: Storage = {
    getItem: (key: string) => store.get(key) ?? null,
    setItem: (key: string, value: string) => {
      store.set(key, String(value));
    },
    removeItem: (key: string) => {
      store.delete(key);
    },
    clear: () => {
      store.clear();
    },
    get length() {
      return store.size;
    },
    key: (index: number) => [...store.keys()][index] ?? null,
  };
  Object.defineProperty(globalThis, 'localStorage', {
    value: ls,
    writable: false,
    configurable: true,
  });
}

// Automatically cleanup after each test
afterEach(() => {
  cleanup();
});

// JSDOM does not implement scrollIntoView. Many components (CommandPalette,
// virtualized lists, ag-grid wrappers) call it on mount/update. Provide a
// no-op globally so these tests render instead of throwing
// "selectedEl?.scrollIntoView is not a function".
if (typeof Element !== 'undefined' && !Element.prototype.scrollIntoView) {
  Element.prototype.scrollIntoView = function () {
    /* no-op for jsdom */
  };
}
