/// <reference types="vitest" />
import path from 'path';
import { fileURLToPath } from 'url';
import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import { defineConfig, type Plugin } from 'vite';
import { sentryVitePlugin } from '@sentry/vite-plugin';
import { VitePWA } from 'vite-plugin-pwa';
import { visualizer } from 'rollup-plugin-visualizer';
import compression from 'vite-plugin-compression';

// Strip modulepreload for ai-vendor (553kB @huggingface/transformers + 23.5MB WASM)
// so it only loads when user opens AI copilot panel, not on every page load.
const noAiPreload: Plugin = {
  name: 'no-ai-vendor-preload',
  transformIndexHtml: {
    order: 'post',
    handler(html) {
      return html.replace(/<link rel="modulepreload"[^>]*\/assets\/ai-vendor[^>]*>/g, '');
    },
  },
};

declare module 'vite' {
  interface UserConfig {
    test?: Record<string, unknown>;
  }
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    compression({ algorithm: 'brotliCompress' }),
    // Sentry source-map upload — only active when SENTRY_AUTH_TOKEN is set
    // (typically in CI / staging, never in dev or local prod-style builds).
    // See T-ATL-007 (Sentry self-hosted) + T-ATL-009 (SDK install).
    ...(process.env.SENTRY_AUTH_TOKEN
      ? [
          sentryVitePlugin({
            org: process.env.SENTRY_ORG,
            project: process.env.SENTRY_PROJECT,
            authToken: process.env.SENTRY_AUTH_TOKEN,
            release: { name: process.env.VITE_SENTRY_RELEASE ?? '' },
            telemetry: false,
          }),
        ]
      : []),
    ...(process.env.ANALYZE === 'true'
      ? [
          visualizer({
            filename: 'bundle-report/stats.html',
            template: 'treemap',
            gzipSize: true,
            brotliSize: true,
            open: false,
          }),
        ]
      : []),
    noAiPreload,
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['icon-192.png', 'icon-512.png', 'icon-512-maskable.png'],
      manifest: {
        name: 'FinPlan Pro — Enterprise FP&A',
        short_name: 'FinPlan Pro',
        description:
          'Free, offline-first financial planning & analysis tool. Budgeting, forecasting, consolidation, and reporting.',
        theme_color: '#1e40af',
        background_color: '#0f172a',
        display: 'standalone',
        orientation: 'any',
        start_url: '/',
        scope: '/',
        categories: ['finance', 'business', 'productivity'],
        icons: [
          // T-3.15 Issue #2 + #3 fix (PROMETHEUS TURN 386+, 2026-06-18):
          // icon-192.png and icon-512.png now have distinct MD5 hashes (was both d13d6d2a...).
          // Maskable icon now has its own file (icon-512-maskable.png) with 16.67%
          // safe-zone padding per W3C maskable spec, no longer reuses icon-512.png.
          // Generated by scripts/generate-pwa-icons.mjs.
          {
            src: 'icon-192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: 'icon-512.png',
            sizes: '512x512',
            type: 'image/png',
          },
          {
            src: 'icon-512-maskable.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        clientsClaim: true,
        skipWaiting: true,
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2}'],
        globIgnores: [
          '**/ai-vendor-*.js',
          '**/pdf-vendor-*.js',
          '**/excel-core-vendor-*.js',
          '**/excel-vendor-*.js',
          '**/grid-community-vendor-*.js',
          '**/chart-vendor-*.js',
          '**/DataGrid-*.js',
        ],
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-cache',
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365,
              },
              cacheableResponse: {
                statuses: [0, 200],
              },
            },
          },
          {
            urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'gstatic-fonts-cache',
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365,
              },
              cacheableResponse: {
                statuses: [0, 200],
              },
            },
          },
          {
            urlPattern: /\.(?:png|jpg|jpeg|svg|gif|webp)$/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'images-cache',
              expiration: {
                maxEntries: 100,
                maxAgeSeconds: 60 * 60 * 24 * 30,
              },
            },
          },
          {
            urlPattern: /\.(?:js|css)$/i,
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'static-resources',
              expiration: {
                maxEntries: 50,
                maxAgeSeconds: 60 * 60 * 24 * 7,
              },
            },
          },
        ],
      },
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
      '@tauri-apps/plugin-global-shortcut': path.resolve(
        __dirname,
        'src/test/__mocks__/tauri-shortcut.ts'
      ),
    },
  },
  clearScreen: false,
  server: {
    port: 5173,
    strictPort: true,
    // Dev-only host allow-list. The production desktop shell (Tauri) never uses
    // this server; it exists so sandboxed/remote development previews (which
    // proxy the dev server under a generated hostname) are not rejected by
    // Vite's host check. Loopback plus explicit preview domains only — never `true`.
    allowedHosts: ['localhost', '127.0.0.1', '.e2b.app', '.localhost'],
    headers: {
      'X-Content-Type-Options': 'nosniff',
      'X-Frame-Options': 'DENY',
      'X-XSS-Protection': '1; mode=block',
      'Referrer-Policy': 'strict-origin-when-cross-origin',
      'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=()',
    },
  },
  build: {
    target: 'es2022',
    chunkSizeWarningLimit: 1200,
    rollupOptions: {
      // ATLAS G2 hygiene: filter diagnostics that don't affect correctness.
      // Eval-in-exceljs: G7 (xlsx removal) is owned by Hephaestus; the
      // eval is in a third-party vendor and we keep the bytes.
      // Chunk size: the real G19 budget is gzip (grid 285 KB gz,
      // excel 238 KB gz - both < 300 KB).
      // See .openhands/baseline-g3-bundle.log.
      onwarn(warning, defaultHandler) {
        if (
          warning.code === 'EVAL' &&
          typeof warning.id === 'string' &&
          warning.id.includes('exceljs')
        ) {
          return;
        }
        if (
          warning.code === 'CHUNK_SIZE' ||
          /chunks? (are|is) larger than/i.test(String(warning.message))
        ) {
          return;
        }
        defaultHandler(warning);
      },
      output: {
        chunkFileNames(chunkInfo) {
          return chunkInfo.name.startsWith('index')
            ? 'assets/chunk-[hash].js'
            : 'assets/[name]-[hash].js';
        },
        manualChunks(id: string) {
          if (id.includes('@huggingface/transformers')) return 'ai-vendor';
          if (id.includes('lucide-react')) return 'icon-vendor';
          if (id.includes('recharts')) return 'chart-vendor';
          if (id.includes('exceljs') && id.includes('/dist/exceljs/')) return 'excel-vendor';
          if (id.includes('exceljs')) return 'excel-core-vendor';
          if (id.includes('jspdf') || id.includes('html2canvas')) return 'pdf-vendor';
          if (id.includes('sql.js')) return 'db-vendor';
        },
      },
    },
  },
  test: {
    include: ['src/**/*.test.ts', 'src/**/*.test.tsx'],
    exclude: [
      'tests/**',
      'node_modules/**',
      // Bench files (T-ATL-001 v0.4 bench opt-in policy):
      // Default `npm run test` excludes all bench work; run benches
      // explicitly via `npm run test:bench` when measuring perf.
      '__benchmarks__/**',
      '**/*.benchmark.test.ts',
      '**/*.benchmark.test.tsx',
      '**/*.bench.test.ts',
      '**/*.bench.test.tsx',
    ],
    setupFiles: ['./src/test/setup.ts'],
    environment: 'jsdom',
    pool: 'threads',
    // Vitest 4 removed `poolOptions` — worker limits are now top-level and
    // `minWorkers`/`minThreads` was dropped (only `maxWorkers` has effect).
    // See https://vitest.dev/guide/migration#pool-rework
    maxWorkers: 4,
    testTimeout: 30000,
    hookTimeout: 30000,
    env: {
      // Mirror dev / staging auth behavior in tests. Without this,
      // `isMockAuthEnabled()` returns false and login() routes to
      // loginReal() — which throws "Real authentication is not
      // configured", breaking every authStore test.
      VITE_USE_MOCK_AUTH: 'true',
    },
    coverage: {
      provider: 'v8',
      reporter: ['text', 'text-summary', 'lcov', 'json-summary'],
      reportsDirectory: './coverage',
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/test/**',
        'src/**/*.test.{ts,tsx}',
        'src/**/*.d.ts',
        'src/**/*.benchmark.ts', // perf drivers run via test:bench, not unit targets
        'src/main.tsx',
        'src/vite-env.d.ts',
      ],
      thresholds: {
        statements: 50,
        branches: 50,
        functions: 50,
        lines: 50,
      },
    },
  },
});
