/**
 * Engine Registry — lazy-load 129 engines instead of static imports.
 * Only loads engines when needed. Preloads critical ones at startup.
 */

import { ENGINE_MANIFEST, ENGINE_IDS, type EngineId } from './engineManifest.generated';

type EngineModule = Record<string, unknown>;

/** Thrown when an engine id is not present in the generated manifest. */
export class UnknownEngineError extends Error {
  readonly engineId: string;
  constructor(engineId: string) {
    super(
      `Unknown engine "${engineId}". Known engines: ${ENGINE_IDS.length}. ` +
        'If this is a new module, run: node scripts/generate-engine-manifest.mjs'
    );
    this.name = 'UnknownEngineError';
    this.engineId = engineId;
  }
}

interface CacheEntry {
  module: EngineModule;
  loadedAt: number;
  lastAccessed: number;
}

class EngineRegistry {
  private cache = new Map<string, CacheEntry>();
  private preloaded = new Set<string>();
  private loading = new Map<string, Promise<EngineModule>>();

  private static CRITICAL_ENGINES = [
    'FormulaEngine',
    'ThreeStatementEngine',
    'CalculationGraph',
    'ConsolidationEngine',
    'ImportEngine',
  ];

  /**
   * Load an engine by name. Returns cached if already loaded.
   */
  async load(engineId: string): Promise<EngineModule> {
    const cached = this.cache.get(engineId);
    if (cached) {
      cached.lastAccessed = Date.now();
      return cached.module;
    }

    // Deduplicate concurrent loads
    const pending = this.loading.get(engineId);
    if (pending) return pending;

    const promise = this.doLoad(engineId);
    this.loading.set(engineId, promise);

    try {
      const mod = await promise;
      return mod;
    } finally {
      this.loading.delete(engineId);
    }
  }

  private async doLoad(engineId: string): Promise<EngineModule> {
    // Dynamic import map for all engines
    const mod = await this.dynamicImport(engineId);
    this.cache.set(engineId, {
      module: mod,
      loadedAt: Date.now(),
      lastAccessed: Date.now(),
    });
    return mod;
  }

  private async dynamicImport(engineId: string): Promise<EngineModule> {
    // N-0013: resolved from the GENERATED manifest, not a hand-written switch.
    // The previous switch listed only 40 of 178 engines, so `load()` threw
    // "Unknown engine" for the other 138 — they were unreachable at runtime
    // through every supported path. The manifest is regenerated by
    // scripts/generate-engine-manifest.mjs and checked in CI, so it cannot
    // silently drift out of sync with the filesystem again.
    const loader = ENGINE_MANIFEST[engineId as EngineId];
    if (!loader) {
      throw new UnknownEngineError(engineId);
    }
    return loader();
  }

  /**
   * Preload an engine without blocking. Fire-and-forget.
   */
  preload(engineId: string): void {
    if (this.cache.has(engineId) || this.preloaded.has(engineId)) return;
    this.preloaded.add(engineId);
    this.load(engineId).catch(() => {
      this.preloaded.delete(engineId);
    });
  }

  /**
   * Preload critical engines at startup.
   */
  preloadCritical(): void {
    for (const id of EngineRegistry.CRITICAL_ENGINES) {
      this.preload(id);
    }
  }

  /**
   * Get a loaded engine synchronously. Returns null if not loaded.
   */
  get(engineId: string): EngineModule | null {
    const cached = this.cache.get(engineId);
    if (cached) {
      cached.lastAccessed = Date.now();
      return cached.module;
    }
    return null;
  }

  /**
   * Check if an engine is loaded.
   */
  has(engineId: string): boolean {
    return this.cache.has(engineId);
  }

  /** Every engine id known to the generated manifest (N-0013). */
  listAvailable(): EngineId[] {
    return [...ENGINE_IDS];
  }

  /** True when the id resolves to a real, loadable module. */
  isKnown(engineId: string): boolean {
    return engineId in ENGINE_MANIFEST;
  }

  /** Ids of engines currently resident in the cache. */
  listLoaded(): string[] {
    return [...this.cache.keys()];
  }

  /**
   * Evict cold engines not accessed within maxAge ms.
   */
  evictCold(maxAge: number = 15 * 60 * 1000): number {
    const now = Date.now();
    let evicted = 0;
    for (const [id, entry] of this.cache) {
      if (now - entry.lastAccessed > maxAge) {
        // Don't evict critical engines
        if (!EngineRegistry.CRITICAL_ENGINES.includes(id)) {
          this.cache.delete(id);
          evicted++;
        }
      }
    }
    return evicted;
  }

  /**
   * Get cache stats.
   */
  getStats(): { loaded: number; critical: string[]; cold: number } {
    const now = Date.now();
    let cold = 0;
    for (const entry of this.cache.values()) {
      if (now - entry.lastAccessed > 15 * 60 * 1000) cold++;
    }
    return {
      loaded: this.cache.size,
      critical: EngineRegistry.CRITICAL_ENGINES,
      cold,
    };
  }

  /**
   * Clear entire cache except critical engines.
   */
  clear(): void {
    for (const [id] of this.cache) {
      if (!EngineRegistry.CRITICAL_ENGINES.includes(id)) {
        this.cache.delete(id);
      }
    }
  }
}

export const engineRegistry = new EngineRegistry();

// Preload critical engines on module load
engineRegistry.preloadCritical();
