/**
 * @vitest-environment jsdom
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { ExportEngine, type ExportData, type ExportConfig } from './ExportEngine';
import * as canvasFactory from '@/utils/canvasFactory';

// ---------------------------------------------------------------------------
// Mock jsPDF
// ---------------------------------------------------------------------------

const mockSave = vi.fn();
const mockAddPage = vi.fn();
const mockSetFontSize = vi.fn();
const mockSetTextColor = vi.fn();
const mockSetDrawColor = vi.fn();
const mockLine = vi.fn();
const mockText = vi.fn();
const mockAutoTable = vi.fn((opts: any) => {
  if (opts.didDrawPage) opts.didDrawPage();
  if (opts.didParseCell) {
    opts.didParseCell({ column: { index: 0 }, cell: { styles: { halign: 'left' } } });
    opts.didParseCell({ column: { index: 1 }, cell: { styles: { halign: 'left' } } });
  }
});

const mockOutlineAdd = vi.fn();
const mockOutlineBold = vi.fn(() => ({ add: mockOutlineAdd }));

function createMockPdf() {
  return {
    autoTable: mockAutoTable,
    save: mockSave,
    setFontSize: mockSetFontSize,
    text: mockText,
    setTextColor: mockSetTextColor,
    setDrawColor: mockSetDrawColor,
    line: mockLine,
    addPage: mockAddPage,
    outline: {
      add: {
        bold: mockOutlineBold,
      },
    },
    internal: {
      pageSize: { width: 210, height: 297 },
      getCurrentPageInfo: () => ({ pageNumber: 1 }),
    },
  };
}

let mockPdf: ReturnType<typeof createMockPdf>;

beforeEach(() => {
  vi.clearAllMocks();
  mockPdf = createMockPdf();

  (window as any).jsPDF = class MockJsPDF {
    constructor() {
      return mockPdf;
    }
  };
});

describe('ExportEngine', () => {
  describe('exportToCSV', () => {
    it('generates CSV content and escapes commas, quotes, and newlines', () => {
      const data: ExportData = {
        headers: ['Name', 'Details', 'Formula'],
        rows: [
          ['Revenue', 'Normal text', '1000'],
          ['Cost, Operating', 'Contains "quotes"', '=1+1'],
          ['Multi\nLine', null, undefined as any],
        ],
      };
      const config: ExportConfig = { title: 'Financial Summary' };

      const downloadSpy = vi.spyOn(canvasFactory, 'downloadBlob').mockImplementation(() => {});

      ExportEngine.exportToCSV(data, config);

      expect(downloadSpy).toHaveBeenCalledTimes(1);
      const [blob, filename] = downloadSpy.mock.calls[0]!;
      expect(filename).toBe('Financial_Summary.csv');
      expect(blob).toBeInstanceOf(Blob);
    });

    it('handles default filename when title is omitted', () => {
      const data: ExportData = {
        headers: ['Col'],
        rows: [['Val']],
      };
      const downloadSpy = vi.spyOn(canvasFactory, 'downloadBlob').mockImplementation(() => {});

      ExportEngine.exportToCSV(data, {});

      expect(downloadSpy).toHaveBeenCalledWith(expect.any(Blob), 'export.csv');
    });
  });

  describe('exportToPDF', () => {
    it('exports data rows to PDF with header, footer, and autoTable', async () => {
      const data: ExportData = {
        headers: ['Item', 'Amount'],
        rows: [
          ['Revenue', 100000],
          ['COGS', 40000],
        ],
      };
      const config: ExportConfig = {
        title: 'Income Statement',
        companyName: 'Acme Corp',
        orientation: 'landscape',
        pageSize: 'a4',
      };

      await ExportEngine.exportToPDF(data, config);

      expect(mockAutoTable).toHaveBeenCalled();
      expect(mockText).toHaveBeenCalledWith('Acme Corp', 14, 10);
      expect(mockText).toHaveBeenCalledWith('Income Statement', 210 - 14, 10);
      expect(mockText).toHaveBeenCalledWith('Generated by FinPlan Pro', 14, 297 - 10);
      expect(mockSave).toHaveBeenCalledWith('Income_Statement.pdf');
    });

    it('renders empty data notice when rows are empty', async () => {
      const data: ExportData = {
        headers: ['Item', 'Amount'],
        rows: [],
      };
      const config: ExportConfig = { title: 'Empty Report' };

      await ExportEngine.exportToPDF(data, config);

      expect(mockText).toHaveBeenCalledWith('No data to export', 14, 50);
      expect(mockSave).toHaveBeenCalledWith('Empty_Report.pdf');
    });
  });

  describe('exportBatchToPDF', () => {
    it('exports multiple sections with PDF outlines and page breaks', async () => {
      const sections = [
        {
          title: 'Section 1: P&L',
          data: {
            headers: ['Line', 'Value'],
            rows: [['Rev', 5000]],
          },
        },
        {
          title: 'Section 2: Balance Sheet',
          data: {
            headers: ['Account', 'Value'],
            rows: [],
          },
        },
      ];
      const config: ExportConfig = {
        title: 'Batch Board Pack',
        companyName: 'Global Corp',
      };

      await ExportEngine.exportBatchToPDF(sections, config);

      expect(mockAddPage).toHaveBeenCalledTimes(1); // 2 sections = 1 addPage
      expect(mockOutlineAdd).toHaveBeenCalledWith('Section 1: P&L', { pageNumber: 1 });
      expect(mockOutlineAdd).toHaveBeenCalledWith('Section 2: Balance Sheet', { pageNumber: 1 });
      expect(mockText).toHaveBeenCalledWith('No data to export', 14, 50); // Section 2 empty
      expect(mockSave).toHaveBeenCalledWith('Batch_Board_Pack.pdf');
    });
  });

  describe('exportToExcel', () => {
    it('delegates to exportExcel implementation without error', async () => {
      const data: ExportData = {
        headers: ['Account', 'Amount'],
        rows: [['Cash', 50000]],
      };
      const config: ExportConfig = { title: 'Cash Flow' };

      await expect(ExportEngine.exportToExcel(data, config)).resolves.not.toThrow();
    });
  });
});
