export interface ExportConfig {
  title: string;
  subtitle?: string;
  date?: string;
  orientation?: 'p' | 'l' | 'portrait' | 'landscape';
  pageSize?: string;
  includeCharts?: boolean;
  includeTimestamp?: boolean;
  companyName?: string;
  password?: string;
}

export interface ExportData {
  headers: string[];
  rows: (string | number | boolean | null)[][];
  footers?: string[];
}

interface JsPDFInstance {
  autoTable: (options: Record<string, unknown>) => void;
  save: (filename: string) => void;
  setFontSize: (size: number) => void;
  text: (text: string, x: number, y: number) => void;
  setFillColor: (r: number, g: number, b: number) => void;
  rect: (x: number, y: number, w: number, h: number, style?: string) => void;
  setTextColor: (r: number, g: number, b: number) => void;
  setDrawColor: (r: number, g: number, b: number) => void;
  line: (x1: number, y1: number, x2: number, y2: number) => void;
  internal: { pageSize: { width: number; height: number }; getCurrentPageInfo?: () => { pageNumber: number } };
}

interface JsPDFConstructor {
  new (options: { orientation?: string; unit?: string; format?: string }): JsPDFInstance;
}

interface WindowWithJsPDF extends Window {
  jsPDF?: JsPDFConstructor;
  XLSX?: {
    utils: {
      book_new: () => unknown;
      aoa_to_sheet: (data: unknown[][]) => Record<string, unknown>;
      encode_cell: (cell: { r: number; c: number }) => string;
    };
    writeFile: (wb: unknown, filename: string) => void;
  };
}

export class ExportEngine {
  static exportToPDF(data: ExportData, config: ExportConfig): void {
    const { jsPDF } = window as unknown as WindowWithJsPDF;
    if (!jsPDF) {
      throw new Error('jsPDF not loaded — include jsPDF script before exporting');
    }

    const doc = new jsPDF({
      orientation: config.orientation || 'portrait',
      unit: 'mm',
      format: config.pageSize || 'a4',
    });

    // HEADER — every page
    const addHeader = () => {
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(config.companyName || 'FinPlan Pro', 14, 10);
      doc.text(config.title || 'Report', doc.internal.pageSize.width - 14, 10);
      doc.setDrawColor(200);
      doc.line(14, 13, doc.internal.pageSize.width - 14, 13);
    };

    // FOOTER — every page
    const addFooter = () => {
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by FinPlan Pro', 14, doc.internal.pageSize.height - 10);
      doc.text(
        'Page ' + doc.internal.getCurrentPageInfo().pageNumber,
        doc.internal.pageSize.width - 14,
        doc.internal.pageSize.height - 10
      );
    };

    if (data.rows.length === 0) {
      addHeader();
      doc.setFontSize(12);
      doc.setTextColor(150, 150, 150);
      doc.text('No data to export', 14, 50);
      addFooter();
    } else {
      // Add header/footer to each page
      // jsPDF eachPage is not a standard method, we use hooks in autoTable instead
      (doc as unknown as JsPDFInstance).autoTable({
        head: [data.headers],
        body: data.rows,
        startY: 20,
        margin: { top: 20, bottom: 15 },
        headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold', fontSize: 9 },
        alternateRowStyles: { fillColor: [245, 245, 245] },
        styles: { fontSize: 8, cellPadding: 2 },
        columnStyles: { 0: { cellWidth: 'wrap' } },
        didDrawPage: () => {
          addHeader();
          addFooter();
        },
        didParseCell: (cellData: {
          column: { index: number };
          cell: { styles: { halign: string } };
        }) => {
          // Right-align number columns (index 1, 2, 3, etc)
          if (cellData.column.index > 0) cellData.cell.styles.halign = 'right';
        },
      });
    }

    doc.save(`${config.title?.replace(/\s+/g, '_') || 'export'}.pdf`);
  }

  static exportToExcel(data: ExportData, config: ExportConfig): void {
    const XLSX = (window as unknown as WindowWithJsPDF).XLSX;
    if (!XLSX) {
      throw new Error('XLSX not loaded — include SheetJS script before exporting');
    }

    const wb = XLSX.utils.book_new();
    const ws_data = [data.headers, ...data.rows];
    const ws = XLSX.utils.aoa_to_sheet(ws_data);

    // Freeze header row
    ws['!freeze'] = { xSplit: 0, ySplit: 1 };

    // Auto column width
    const colWidths = data.headers.map((h: string, i: number) => {
      const maxLen = Math.max(
        h.length,
        ...data.rows.map((r: (string | number | boolean | null)[]) => String(r[i] || '').length)
      );
      return { wch: maxLen + 3 };
    });
    ws['!cols'] = colWidths;

    // Currency format for number columns
    for (let r = 1; r <= data.rows.length; r++) {
      for (let c = 1; c < data.headers.length; c++) {
        const cellRef = XLSX.utils.encode_cell({ r, c });
        if (ws[cellRef] && typeof ws[cellRef].v === 'number') {
          ws[cellRef].z = '$#,##0.00';
        }
      }
    }

    XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');
    XLSX.writeFile(wb, `${config.title?.replace(/\s+/g, '_') || 'export'}.xlsx`);
  }

  /**
   * Export multiple datasets as a single PDF with bookmarks per section.
   */
  static exportBatchToPDF(
    sections: Array<{ title: string; data: ExportData }>,
    config: ExportConfig
  ): void {
    const { jsPDF } = window as unknown as WindowWithJsPDF;
    if (!jsPDF) {
      throw new Error('jsPDF not loaded — include jsPDF script before exporting');
    }

    const doc = new jsPDF({
      orientation: config.orientation || 'portrait',
      unit: 'mm',
      format: config.pageSize || 'a4',
    });

    const addHeader = () => {
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(config.companyName || 'FinPlan Pro', 14, 10);
      doc.text(config.title || 'Report', doc.internal.pageSize.width - 14, 10);
      doc.setDrawColor(200);
      doc.line(14, 13, doc.internal.pageSize.width - 14, 13);
    };

    const addFooter = () => {
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by FinPlan Pro', 14, doc.internal.pageSize.height - 10);
      doc.text(
        'Page ' + doc.internal.getCurrentPageInfo().pageNumber,
        doc.internal.pageSize.width - 14,
        doc.internal.pageSize.height - 10
      );
    };

    sections.forEach((section, idx) => {
      if (idx > 0) doc.addPage();

      // Add bookmark for this section
      const outline = doc.outline;
      if (outline) {
        const heading = outline.add.bold();
        heading.add(section.title, { pageNumber: doc.internal.getCurrentPageInfo().pageNumber });
      }

      addHeader();

      if (section.data.rows.length === 0) {
        doc.setFontSize(12);
        doc.setTextColor(150, 150, 150);
        doc.text('No data to export', 14, 50);
      } else {
        doc.setFontSize(14);
        doc.setTextColor(30);
        doc.text(section.title, 14, 20);

        (doc as unknown as JsPDFInstance).autoTable({
          head: [section.data.headers],
          body: section.data.rows,
          startY: 28,
          margin: { top: 20, bottom: 15 },
          headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold', fontSize: 9 },
          alternateRowStyles: { fillColor: [245, 245, 245] },
          styles: { fontSize: 8, cellPadding: 2 },
          didDrawPage: () => {
            addHeader();
            addFooter();
          },
          didParseCell: (cellData: {
            column: { index: number };
            cell: { styles: { halign: string } };
          }) => {
            if (cellData.column.index > 0) cellData.cell.styles.halign = 'right';
          },
        });
      }

      addFooter();
    });

    doc.save(`${config.title?.replace(/\s+/g, '_') || 'batch_export'}.pdf`);
  }

  static exportToCSV(data: ExportData, config: ExportConfig): void {
    const escapeCSV = (val: string | number | boolean | null | undefined): string => {
      if (val === null || val === undefined) return '';
      const str = String(val);
      if (str.includes('"') || str.includes(',') || str.includes('\n') || str.includes('\r')) {
        return '"' + str.replace(/"/g, '""') + '"';
      }
      return str;
    };

    const csvContent = [
      data.headers.map(escapeCSV).join(','),
      ...data.rows.map((row) => row.map(escapeCSV).join(',')),
    ].join('\r\n');

    const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `${config.title.replace(/\s+/g, '_')}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
}
