/**
 * @vitest-environment jsdom
 */
import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { BoardPackTemplate } from './BoardPackTemplate';

const exportToExcel = vi.fn().mockResolvedValue(undefined);
const exportToCSV = vi.fn();
vi.mock('@/engines/ExportEngine', () => ({
  ExportEngine: {
    exportToExcel: (...args: unknown[]) => exportToExcel(...args),
    exportToCSV: (...args: unknown[]) => exportToCSV(...args),
  },
}));

const reportExportFailure = vi.fn();
vi.mock('@/utils/exportErrorHandler', () => ({
  reportExportFailure: (...args: unknown[]) => reportExportFailure(...args),
}));

vi.mock('@/engines/ExportTemplateEngine', async (importOriginal) => {
  // Keep the REAL resolver helpers: they are the data-binding logic under test.
  // Only the engine class (which pulls in jsPDF) is stubbed.
  const actual = await importOriginal<typeof import('@/engines/ExportTemplateEngine')>();

  class MockExportTemplateEngine {
    getTemplate = vi.fn().mockReturnValue({
      id: 'tpl-board-pack',
      name: 'Board Pack',
      type: 'board_pack',
      description: 'Board pack template',
      sections: [
        { id: 'cover', type: 'cover', title: 'Cover', order: 0, config: { confidential: true } },
        {
          id: 'kpi',
          type: 'kpi_summary',
          title: 'Key Metrics',
          order: 1,
          config: { kpis: [{ label: 'Revenue', value: '$4.2M', change: '+12%' }] },
        },
        {
          id: 'table',
          type: 'table',
          title: 'P&L Summary',
          order: 2,
          config: { headers: ['Line Item', 'Actual'], rows: [['Revenue', '4200000']] },
        },
        {
          id: 'text',
          type: 'text',
          title: 'Commentary',
          order: 3,
          config: { content: 'Strong performance for {entity} in {period}' },
        },
        { id: 'break', type: 'page_break', title: '', order: 4, config: {} },
      ],
      style: {
        primaryColor: '#1E3A5F',
        secondaryColor: '#4A90D9',
        fontFamily: 'helvetica',
        headerFontSize: 10,
        bodyFontSize: 8,
        companyName: 'FinPlan Pro',
      },
      variables: [],
      createdAt: '2026-01-01',
      updatedAt: '2026-01-01',
    });
    generatePDF = vi.fn();
  }

  return {
    ...actual,
    ExportTemplateEngine: MockExportTemplateEngine,
  };
});

describe('BoardPackTemplate', () => {
  it('renders without crashing', () => {
    render(<BoardPackTemplate />);
  });

  it('renders the preview heading with default entity info', () => {
    render(<BoardPackTemplate />);
    expect(screen.getByText('Board Pack Preview')).toBeInTheDocument();
    // "Acme Corporation" appears in cover, table, and text sections
    expect(screen.getAllByText(/Acme Corporation/).length).toBeGreaterThanOrEqual(1);
  });

  it('renders with custom props', () => {
    render(
      <BoardPackTemplate
        entity="Custom Corp"
        period="Q1 2026"
        currency="EUR"
        preparedBy="Finance Team"
      />
    );
    // "Custom Corp" appears in cover, table, and text sections
    expect(screen.getAllByText(/Custom Corp/).length).toBeGreaterThanOrEqual(1);
    expect(screen.getAllByText(/Q1 2026/).length).toBeGreaterThanOrEqual(1);
  });

  it('renders the export PDF button', () => {
    render(<BoardPackTemplate />);
    expect(screen.getByRole('button', { name: /export pdf/i })).toBeInTheDocument();
  });

  it('renders the show export options button', () => {
    render(<BoardPackTemplate />);
    expect(screen.getByRole('button', { name: /show export options/i })).toBeInTheDocument();
  });

  it('toggles export options panel on button click', () => {
    render(<BoardPackTemplate />);
    const toggleBtn = screen.getByRole('button', { name: /show export options/i });
    fireEvent.click(toggleBtn);
    expect(screen.getByText('Export Options')).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /hide export options/i })).toBeInTheDocument();
  });

  it('renders cover section with entity name', () => {
    render(<BoardPackTemplate />);
    expect(screen.getAllByText('Acme Corporation').length).toBeGreaterThanOrEqual(1);
  });

  it('renders the footer', () => {
    render(<BoardPackTemplate />);
    expect(screen.getByText(/Generated by FinPlan Pro/)).toBeInTheDocument();
  });

  it('renders KPI summary section with metrics', () => {
    render(<BoardPackTemplate />);
    expect(screen.getByText('Key Metrics')).toBeInTheDocument();
    // "Revenue" appears in both KPI and table sections
    expect(screen.getAllByText('Revenue').length).toBeGreaterThanOrEqual(1);
    expect(screen.getByText('$4.2M')).toBeInTheDocument();
  });

  it('renders table section', () => {
    render(<BoardPackTemplate />);
    expect(screen.getAllByText('P&L Summary').length).toBeGreaterThanOrEqual(1);
  });

  it('renders text section with variable substitution', () => {
    render(<BoardPackTemplate />);
    expect(screen.getAllByText('Commentary').length).toBeGreaterThanOrEqual(1);
    expect(screen.getByText(/Strong performance for Acme Corporation/)).toBeInTheDocument();
  });

  // --- Regression: empty export ------------------------------------------
  // The Excel and CSV buttons used to pass `rows: []` unconditionally, so a
  // user exporting a board pack received four column headers and no data.

  it('exports the rows shown in the preview, never a headers-only file', async () => {
    exportToExcel.mockClear();
    render(<BoardPackTemplate />);
    fireEvent.click(screen.getByRole('button', { name: /show export options/i }));
    fireEvent.click(screen.getByRole('button', { name: /^excel$/i }));

    await vi.waitFor(() => expect(exportToExcel).toHaveBeenCalledTimes(1));

    const [data] = exportToExcel.mock.calls[0] as [{ headers: string[]; rows: string[][] }];
    expect(data.rows.length).toBeGreaterThan(0);
    // The mocked template's P&L row must actually be in the payload.
    const flat = data.rows.map((r) => r.join('|')).join('\n');
    expect(flat).toContain('Revenue');
    expect(flat).toContain('4200000');
  });

  it('exports the same data to CSV', async () => {
    exportToCSV.mockClear();
    render(<BoardPackTemplate />);
    fireEvent.click(screen.getByRole('button', { name: /show export options/i }));
    fireEvent.click(screen.getByRole('button', { name: /^csv$/i }));

    await vi.waitFor(() => expect(exportToCSV).toHaveBeenCalledTimes(1));
    const [data] = exportToCSV.mock.calls[0] as [{ rows: string[][] }];
    expect(data.rows.map((r) => r.join('|')).join('\n')).toContain('4200000');
  });
});
