/**
 * @vitest-environment jsdom
 */
import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { BoardPackTemplate } from './BoardPackTemplate';

vi.mock('@/engines/ExportTemplateEngine', () => {
  class MockExportTemplateEngine {
    getTemplate = vi.fn().mockReturnValue({
      id: 'tpl-board-pack',
      name: 'Board Pack',
      type: 'board_pack',
      description: 'Board pack template',
      sections: [
        { id: 'cover', type: 'cover', title: 'Cover', order: 0, config: { confidential: true } },
        {
          id: 'kpi',
          type: 'kpi_summary',
          title: 'Key Metrics',
          order: 1,
          config: { kpis: [{ label: 'Revenue', value: '$4.2M', change: '+12%' }] },
        },
        {
          id: 'table',
          type: 'table',
          title: 'P&L Summary',
          order: 2,
          config: { headers: ['Line Item', 'Actual'], rows: [['Revenue', '4200000']] },
        },
        {
          id: 'text',
          type: 'text',
          title: 'Commentary',
          order: 3,
          config: { content: 'Strong performance for {entity} in {period}' },
        },
        { id: 'break', type: 'page_break', title: '', order: 4, config: {} },
      ],
      style: {
        primaryColor: '#1E3A5F',
        secondaryColor: '#4A90D9',
        fontFamily: 'helvetica',
        headerFontSize: 10,
        bodyFontSize: 8,
        companyName: 'FinPlan Pro',
      },
      variables: [],
      createdAt: '2026-01-01',
      updatedAt: '2026-01-01',
    });
    generatePDF = vi.fn();
  }

  return {
    ExportTemplateEngine: MockExportTemplateEngine,
  };
});

describe('BoardPackTemplate', () => {
  it('renders without crashing', () => {
    render(<BoardPackTemplate />);
  });

  it('renders the preview heading with default entity info', () => {
    render(<BoardPackTemplate />);
    expect(screen.getByText('Board Pack Preview')).toBeInTheDocument();
    // "Acme Corporation" appears in cover, table, and text sections
    expect(screen.getAllByText(/Acme Corporation/).length).toBeGreaterThanOrEqual(1);
  });

  it('renders with custom props', () => {
    render(
      <BoardPackTemplate
        entity="Custom Corp"
        period="Q1 2026"
        currency="EUR"
        preparedBy="Finance Team"
      />
    );
    // "Custom Corp" appears in cover, table, and text sections
    expect(screen.getAllByText(/Custom Corp/).length).toBeGreaterThanOrEqual(1);
    expect(screen.getAllByText(/Q1 2026/).length).toBeGreaterThanOrEqual(1);
  });

  it('renders the export PDF button', () => {
    render(<BoardPackTemplate />);
    expect(screen.getByRole('button', { name: /export pdf/i })).toBeInTheDocument();
  });

  it('renders the show export options button', () => {
    render(<BoardPackTemplate />);
    expect(screen.getByRole('button', { name: /show export options/i })).toBeInTheDocument();
  });

  it('toggles export options panel on button click', () => {
    render(<BoardPackTemplate />);
    const toggleBtn = screen.getByRole('button', { name: /show export options/i });
    fireEvent.click(toggleBtn);
    expect(screen.getByText('Export Options')).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /hide export options/i })).toBeInTheDocument();
  });

  it('renders cover section with entity name', () => {
    render(<BoardPackTemplate />);
    expect(screen.getAllByText('Acme Corporation').length).toBeGreaterThanOrEqual(1);
  });

  it('renders the footer', () => {
    render(<BoardPackTemplate />);
    expect(screen.getByText(/Generated by FinPlan Pro/)).toBeInTheDocument();
  });

  it('renders KPI summary section with metrics', () => {
    render(<BoardPackTemplate />);
    expect(screen.getByText('Key Metrics')).toBeInTheDocument();
    // "Revenue" appears in both KPI and table sections
    expect(screen.getAllByText('Revenue').length).toBeGreaterThanOrEqual(1);
    expect(screen.getByText('$4.2M')).toBeInTheDocument();
  });

  it('renders table section', () => {
    render(<BoardPackTemplate />);
    expect(screen.getAllByText('P&L Summary').length).toBeGreaterThanOrEqual(1);
  });

  it('renders text section with variable substitution', () => {
    render(<BoardPackTemplate />);
    expect(screen.getAllByText('Commentary').length).toBeGreaterThanOrEqual(1);
    expect(screen.getByText(/Strong performance for Acme Corporation/)).toBeInTheDocument();
  });
});
