// =============================================================================
// ANNUAL OPERATING BUDGET TEMPLATE
// Full P&L budget with department-level granularity, seasonality, and
// variance tracking. Realistic mid-market company ($50M revenue).
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from '../engines/TemplateLibrary';

function makePeriodRange(
  start: string,
  end: string,
  frequency: 'monthly' | 'quarterly' | 'annual'
) {
  return { start, end, frequency };
}

// ---------------------------------------------------------------------------
// Drivers
// ---------------------------------------------------------------------------

const drivers: DriverDefinition[] = [
  {
    id: 'aob-revenue-growth',
    name: 'Revenue Growth Rate',
    description: 'Year-over-year revenue growth percentage',
    unit: 'percentage',
    defaultValue: 12,
    minValue: -30,
    maxValue: 100,
    step: 1,
    category: 'Revenue',
    tags: ['growth', 'topline'],
  },
  {
    id: 'aob-gross-margin',
    name: 'Gross Margin Target',
    description: 'Target gross margin percentage',
    unit: 'percentage',
    defaultValue: 62,
    minValue: 20,
    maxValue: 90,
    step: 1,
    category: 'Profitability',
    tags: ['margin', 'cogs'],
  },
  {
    id: 'aob-headcount-growth',
    name: 'Headcount Growth',
    description: 'Planned headcount increase percentage',
    unit: 'percentage',
    defaultValue: 8,
    minValue: -20,
    maxValue: 50,
    step: 1,
    category: 'Workforce',
    tags: ['headcount', 'hiring'],
  },
  {
    id: 'aob-avg-salary',
    name: 'Average Fully-Loaded Salary',
    description: 'Average annual salary including benefits',
    unit: 'currency',
    defaultValue: 95000,
    minValue: 30000,
    maxValue: 500000,
    step: 1000,
    category: 'Workforce',
    tags: ['salary', 'compensation'],
  },
  {
    id: 'aob-rent-escalation',
    name: 'Rent Escalation',
    description: 'Annual rent increase percentage',
    unit: 'percentage',
    defaultValue: 3,
    minValue: 0,
    maxValue: 15,
    step: 0.5,
    category: 'Facilities',
    tags: ['rent', 'occupancy'],
  },
  {
    id: 'aob-marketing-pct',
    name: 'Marketing as % of Revenue',
    description: 'Marketing spend as percentage of revenue',
    unit: 'percentage',
    defaultValue: 10,
    minValue: 0,
    maxValue: 30,
    step: 0.5,
    category: 'Sales & Marketing',
    tags: ['marketing', 'demand-gen'],
  },
  {
    id: 'aob-rd-pct',
    name: 'R&D as % of Revenue',
    description: 'R&D spend as percentage of revenue',
    unit: 'percentage',
    defaultValue: 18,
    minValue: 5,
    maxValue: 40,
    step: 1,
    category: 'R&D',
    tags: ['engineering', 'product'],
  },
  {
    id: 'aob-inflation',
    name: 'Cost Inflation Factor',
    description: 'General cost inflation adjustment',
    unit: 'percentage',
    defaultValue: 3.5,
    minValue: 0,
    maxValue: 20,
    step: 0.5,
    category: 'Macro',
    tags: ['inflation', 'cpi'],
  },
  {
    id: 'aob-seasonal-peak',
    name: 'Seasonal Peak Month',
    description: 'Month number (1-12) of peak revenue',
    unit: 'count',
    defaultValue: 11,
    minValue: 1,
    maxValue: 12,
    step: 1,
    category: 'Seasonality',
    tags: ['seasonal', 'demand'],
  },
  {
    id: 'aob-seasonal-factor',
    name: 'Seasonal Amplitude',
    description: 'Peak-to-trough revenue variation percentage',
    unit: 'percentage',
    defaultValue: 25,
    minValue: 0,
    maxValue: 80,
    step: 5,
    category: 'Seasonality',
    tags: ['seasonal', 'variation'],
  },
];

// ---------------------------------------------------------------------------
// Accounts (Chart of Accounts)
// ---------------------------------------------------------------------------

const accounts: AccountDefinition[] = [
  // Revenue
  {
    id: 'aob-total-revenue',
    name: 'Total Revenue',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Total net revenue',
    isCalculated: true,
  },
  {
    id: 'aob-product-revenue',
    name: 'Product Revenue',
    parentId: 'aob-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Revenue from product sales',
    isCalculated: false,
  },
  {
    id: 'aob-service-revenue',
    name: 'Service Revenue',
    parentId: 'aob-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Revenue from services',
    isCalculated: false,
  },
  {
    id: 'aob-subscription-revenue',
    name: 'Subscription Revenue',
    parentId: 'aob-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Recurring subscription revenue',
    isCalculated: false,
  },

  // COGS
  {
    id: 'aob-total-cogs',
    name: 'Cost of Goods Sold',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Total COGS',
    isCalculated: true,
  },
  {
    id: 'aob-material-cost',
    name: 'Materials & Supplies',
    parentId: 'aob-total-cogs',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Raw materials',
    isCalculated: false,
  },
  {
    id: 'aob-direct-labor',
    name: 'Direct Labor',
    parentId: 'aob-total-cogs',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Production labor',
    isCalculated: false,
  },
  {
    id: 'aob-freight-in',
    name: 'Freight & Shipping',
    parentId: 'aob-total-cogs',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Inbound freight',
    isCalculated: false,
  },

  // Gross Profit
  {
    id: 'aob-gross-profit',
    name: 'Gross Profit',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Revenue minus COGS',
    isCalculated: true,
  },
  {
    id: 'aob-gross-margin-pct',
    name: 'Gross Margin %',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Gross margin percentage',
    isCalculated: true,
  },

  // Operating Expenses
  {
    id: 'aob-total-opex',
    name: 'Total Operating Expenses',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Total OpEx',
    isCalculated: true,
  },
  {
    id: 'aob-salary-expense',
    name: 'Salaries & Wages',
    parentId: 'aob-total-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Total compensation',
    isCalculated: true,
  },
  {
    id: 'aob-benefits-expense',
    name: 'Benefits & Taxes',
    parentId: 'aob-total-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Benefits, payroll taxes',
    isCalculated: true,
  },
  {
    id: 'aob-rent-expense',
    name: 'Rent & Occupancy',
    parentId: 'aob-total-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Office rent, utilities',
    isCalculated: true,
  },
  {
    id: 'aob-marketing-expense',
    name: 'Marketing & Advertising',
    parentId: 'aob-total-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Demand generation',
    isCalculated: true,
  },
  {
    id: 'aob-travel-expense',
    name: 'Travel & Entertainment',
    parentId: 'aob-total-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'T&E',
    isCalculated: false,
  },
  {
    id: 'aob-technology-expense',
    name: 'Technology & Software',
    parentId: 'aob-total-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'SaaS, infrastructure',
    isCalculated: false,
  },
  {
    id: 'aob-professional-expense',
    name: 'Professional Services',
    parentId: 'aob-total-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Legal, accounting, consulting',
    isCalculated: false,
  },
  {
    id: 'aob-insurance-expense',
    name: 'Insurance',
    parentId: 'aob-total-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Business insurance',
    isCalculated: false,
  },
  {
    id: 'aob-depreciation-expense',
    name: 'Depreciation & Amortization',
    parentId: 'aob-total-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'D&A',
    isCalculated: false,
  },
  {
    id: 'aob-other-expense',
    name: 'Other Operating Expenses',
    parentId: 'aob-total-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Miscellaneous',
    isCalculated: false,
  },

  // R&D (separate from OpEx for visibility)
  {
    id: 'aob-rd-expense',
    name: 'R&D Expense',
    parentId: 'aob-total-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Research & Development',
    isCalculated: true,
  },

  // Profitability
  {
    id: 'aob-ebitda',
    name: 'EBITDA',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Operating income before D&A',
    isCalculated: true,
  },
  {
    id: 'aob-ebitda-margin',
    name: 'EBITDA Margin %',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'EBITDA as % of revenue',
    isCalculated: true,
  },
  {
    id: 'aob-operating-income',
    name: 'Operating Income (EBIT)',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Earnings before interest and tax',
    isCalculated: true,
  },
  {
    id: 'aob-net-income',
    name: 'Net Income',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Bottom line',
    isCalculated: true,
  },
  {
    id: 'aob-net-margin',
    name: 'Net Margin %',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Net income as % of revenue',
    isCalculated: true,
  },

  // Headcount
  {
    id: 'aob-headcount',
    name: 'Total Headcount',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Full-time equivalents',
    isCalculated: true,
  },
  {
    id: 'aob-revenue-per-employee',
    name: 'Revenue per Employee',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Revenue / FTE',
    isCalculated: true,
  },
];

// ---------------------------------------------------------------------------
// Cascade Rules
// ---------------------------------------------------------------------------

const cascadeRules: CascadeRuleDefinition[] = [
  {
    id: 'aob-c-1',
    driverId: 'aob-revenue-growth',
    targetAccountId: 'aob-product-revenue',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 0.6,
    formula: 'x * prev / 100 + prev',
    description: 'Growth drives product revenue',
  },
  {
    id: 'aob-c-2',
    driverId: 'aob-revenue-growth',
    targetAccountId: 'aob-service-revenue',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 0.3,
    formula: 'x * prev / 100 + prev',
    description: 'Growth drives service revenue',
  },
  {
    id: 'aob-c-3',
    driverId: 'aob-revenue-growth',
    targetAccountId: 'aob-subscription-revenue',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 0.1,
    formula: 'x * prev / 100 + prev',
    description: 'Growth drives subscription revenue',
  },
  {
    id: 'aob-c-4',
    driverId: 'aob-gross-margin',
    targetAccountId: 'aob-total-cogs',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * (100 - x) / 100',
    description: 'Margin target drives COGS',
  },
  {
    id: 'aob-c-5',
    driverId: 'aob-headcount-growth',
    targetAccountId: 'aob-headcount',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'prev * (1 + x / 100)',
    description: 'Growth drives headcount',
  },
  {
    id: 'aob-c-6',
    driverId: 'aob-avg-salary',
    targetAccountId: 'aob-salary-expense',
    cascadeType: 'direct',
    impactType: 'multiplicative',
    weight: 1,
    description: 'Salary drives total comp',
  },
  {
    id: 'aob-c-7',
    driverId: 'aob-rent-escalation',
    targetAccountId: 'aob-rent-expense',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'prev * (1 + x / 100)',
    description: 'Escalation drives rent',
  },
  {
    id: 'aob-c-8',
    driverId: 'aob-marketing-pct',
    targetAccountId: 'aob-marketing-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Marketing % drives spend',
  },
  {
    id: 'aob-c-9',
    driverId: 'aob-rd-pct',
    targetAccountId: 'aob-rd-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'R&D % drives spend',
  },
  {
    id: 'aob-c-10',
    driverId: 'aob-inflation',
    targetAccountId: 'aob-technology-expense',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'prev * (1 + x / 100)',
    description: 'Inflation drives tech costs',
  },
];

// ---------------------------------------------------------------------------
// Template Export
// ---------------------------------------------------------------------------

export function buildAnnualOperatingBudgetTemplate(): FPTemplate {
  return {
    id: 'tpl-annual-operating-budget',
    name: 'Annual Operating Budget',
    description:
      'Comprehensive annual operating budget with department-level P&L, seasonality modeling, headcount planning, and variance tracking. Pre-populated with realistic mid-market company data ($50M revenue, 250 FTEs).',
    industry: 'SaaS',
    category: 'opex',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: ['budget', 'operating', 'p&l', 'department', 'headcount', 'seasonal', 'annual'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
