// =============================================================================
// BANKING NIM TEMPLATE
// Net interest margin model with rate sensitivity, deposit mix,
// credit quality metrics, and regulatory capital ratios. Regional bank.
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from '../engines/TemplateLibrary';

function makePeriodRange(
  start: string,
  end: string,
  frequency: 'monthly' | 'quarterly' | 'annual'
) {
  return { start, end, frequency };
}

const drivers: DriverDefinition[] = [
  {
    id: 'bnk-fed-funds',
    name: 'Fed Funds Rate',
    description: 'Federal funds target rate',
    unit: 'percentage',
    defaultValue: 4.5,
    minValue: 0,
    maxValue: 20,
    step: 0.25,
    category: 'Rates',
    tags: ['rates'],
  },
  {
    id: 'bnk-loan-yield',
    name: 'Loan Yield',
    description: 'Weighted average loan yield',
    unit: 'percentage',
    defaultValue: 6.25,
    minValue: 0,
    maxValue: 30,
    step: 0.25,
    category: 'Rates',
    tags: ['yield'],
  },
  {
    id: 'bnk-deposit-cost',
    name: 'Cost of Deposits',
    description: 'Weighted average deposit cost',
    unit: 'percentage',
    defaultValue: 2.1,
    minValue: 0,
    maxValue: 15,
    step: 0.1,
    category: 'Rates',
    tags: ['deposits'],
  },
  {
    id: 'bnk-loan-volume',
    name: 'Total Loans',
    description: 'Total outstanding loans',
    unit: 'currency',
    defaultValue: 12000000000,
    minValue: 0,
    maxValue: 500000000000,
    step: 100000000,
    category: 'Volume',
    tags: ['loans'],
  },
  {
    id: 'bnk-deposit-volume',
    name: 'Total Deposits',
    description: 'Total deposits',
    unit: 'currency',
    defaultValue: 15000000000,
    minValue: 0,
    maxValue: 500000000000,
    step: 100000000,
    category: 'Volume',
    tags: ['deposits'],
  },
  {
    id: 'bnk-npl-ratio',
    name: 'NPL Ratio',
    description: 'Non-performing loans as % of total',
    unit: 'percentage',
    defaultValue: 0.9,
    minValue: 0,
    maxValue: 15,
    step: 0.1,
    category: 'Credit',
    tags: ['npl'],
  },
  {
    id: 'bnk-provision-rate',
    name: 'Provision Rate',
    description: 'Loan loss provision as % of loans',
    unit: 'percentage',
    defaultValue: 0.4,
    minValue: 0,
    maxValue: 10,
    step: 0.05,
    category: 'Credit',
    tags: ['provision'],
  },
  {
    id: 'bnk-noninterest-income-pct',
    name: 'Non-Interest Income %',
    description: 'Fee income as % of average assets',
    unit: 'percentage',
    defaultValue: 1.4,
    minValue: 0,
    maxValue: 10,
    step: 0.1,
    category: 'Revenue',
    tags: ['fees'],
  },
  {
    id: 'bnk-efficiency-ratio',
    name: 'Efficiency Ratio',
    description: 'OpEx as % of revenue',
    unit: 'percentage',
    defaultValue: 52,
    minValue: 20,
    maxValue: 100,
    step: 1,
    category: 'Efficiency',
    tags: ['efficiency'],
  },
  {
    id: 'bnk-tier1-ratio',
    name: 'Tier 1 Capital Ratio',
    description: 'T1 capital / risk-weighted assets',
    unit: 'percentage',
    defaultValue: 11.5,
    minValue: 6,
    maxValue: 25,
    step: 0.5,
    category: 'Capital',
    tags: ['basel'],
  },
  {
    id: 'bnk-loan-growth',
    name: 'Loan Growth Rate',
    description: 'Annual loan portfolio growth',
    unit: 'percentage',
    defaultValue: 5,
    minValue: -10,
    maxValue: 30,
    step: 1,
    category: 'Growth',
    tags: ['growth'],
  },
  {
    id: 'bnk-beta',
    name: 'Deposit Beta',
    description: 'Deposit rate sensitivity to fed funds',
    unit: 'percentage',
    defaultValue: 45,
    minValue: 0,
    maxValue: 100,
    step: 5,
    category: 'Rates',
    tags: ['beta', 'sensitivity'],
  },
];

const accounts: AccountDefinition[] = [
  // Interest Income/Expense
  {
    id: 'bnk-nii',
    name: 'Net Interest Income',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'NII',
    isCalculated: true,
  },
  {
    id: 'bnk-interest-income',
    name: 'Interest Income',
    parentId: 'bnk-nii',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Loan interest',
    isCalculated: true,
  },
  {
    id: 'bnk-interest-expense',
    name: 'Interest Expense',
    parentId: 'bnk-nii',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Deposit interest',
    isCalculated: true,
  },
  {
    id: 'bnk-nim',
    name: 'Net Interest Margin',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'NIM %',
    isCalculated: true,
  },

  // Non-Interest
  {
    id: 'bnk-noninterest-income',
    name: 'Non-Interest Income',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Fee income',
    isCalculated: true,
  },
  {
    id: 'bnk-total-revenue',
    name: 'Total Revenue',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'NII + fees',
    isCalculated: true,
  },

  // Expenses
  {
    id: 'bnk-provision',
    name: 'Provision for Credit Losses',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Loan loss provision',
    isCalculated: true,
  },
  {
    id: 'bnk-operating-expense',
    name: 'Operating Expense',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Total OpEx',
    isCalculated: true,
  },
  {
    id: 'bnk-prefax-income',
    name: 'Pre-Tax Income',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Pretax profit',
    isCalculated: true,
  },
  {
    id: 'bnk-net-income',
    name: 'Net Income',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Bottom line',
    isCalculated: true,
  },

  // Balance Sheet
  {
    id: 'bnk-total-assets',
    name: 'Total Assets',
    parentId: null,
    accountType: 'asset',
    debitSide: 'debit',
    description: 'Total bank assets',
    isCalculated: true,
  },
  {
    id: 'bnk-npl-amount',
    name: 'Non-Performing Loans',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'NPL balance',
    isCalculated: true,
  },
  {
    id: 'bnk-allowance',
    name: 'Allowance for Credit Losses',
    parentId: null,
    accountType: 'asset',
    debitSide: 'credit',
    description: 'ACL',
    isCalculated: true,
  },
  {
    id: 'bnk-tier1-capital',
    name: 'Tier 1 Capital',
    parentId: null,
    accountType: 'equity',
    debitSide: 'credit',
    description: 'T1 capital',
    isCalculated: true,
  },

  // Ratios
  {
    id: 'bnk-roa',
    name: 'Return on Assets',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'ROA',
    isCalculated: true,
  },
  {
    id: 'bnk-roe',
    name: 'Return on Equity',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'ROE',
    isCalculated: true,
  },
  {
    id: 'bnk-ldr',
    name: 'Loan-to-Deposit Ratio',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'LDR',
    isCalculated: true,
  },
  {
    id: 'bnk-coverage-ratio',
    name: 'ACL / NPL Ratio',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Coverage',
    isCalculated: true,
  },
];

const cascadeRules: CascadeRuleDefinition[] = [
  {
    id: 'bnk-c-1',
    driverId: 'bnk-loan-yield',
    targetAccountId: 'bnk-interest-income',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'bnk_loan_volume * x / 100 / 12',
    description: 'Yield drives interest income',
  },
  {
    id: 'bnk-c-2',
    driverId: 'bnk-deposit-cost',
    targetAccountId: 'bnk-interest-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'bnk_deposit_volume * x / 100 / 12',
    description: 'Cost drives interest expense',
  },
  {
    id: 'bnk-c-3',
    driverId: 'bnk-npl-ratio',
    targetAccountId: 'bnk-npl-amount',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'bnk_loan_volume * x / 100',
    description: 'NPL ratio drives NPL amount',
  },
  {
    id: 'bnk-c-4',
    driverId: 'bnk-provision-rate',
    targetAccountId: 'bnk-provision',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'bnk_loan_volume * x / 100 / 12',
    description: 'Provision rate drives provision',
  },
  {
    id: 'bnk-c-5',
    driverId: 'bnk-efficiency-ratio',
    targetAccountId: 'bnk-operating-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'total_revenue * x / 100',
    description: 'Efficiency ratio drives OpEx',
  },
  {
    id: 'bnk-c-6',
    driverId: 'bnk-loan-growth',
    targetAccountId: 'bnk-loan-volume',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'prev * (1 + x / 100 / 12)',
    description: 'Growth drives loan volume',
  },
  {
    id: 'bnk-c-7',
    driverId: 'bnk-beta',
    targetAccountId: 'bnk-deposit-cost',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'bnk_fed_funds * x / 100',
    description: 'Beta drives deposit cost sensitivity',
  },
];

export function buildBankingNIMTemplate(): FPTemplate {
  return {
    id: 'tpl-banking-nim',
    name: 'Banking NIM Model',
    description:
      'Regional bank NIM model with rate sensitivity analysis (deposit beta), credit quality metrics (NPL, ACL coverage), regulatory capital ratios (Tier 1, LDR), and profitability analysis (ROA, ROE). Pre-populated for a $12B loan portfolio.',
    industry: 'Banking',
    category: 'balance-sheet',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'quarterly'),
    tags: ['banking', 'nim', 'npl', 'capital', 'roa', 'roe', 'credit', 'rate-sensitivity'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
