// =============================================================================
// CAPEX PLAN TEMPLATE
// Capital expenditure planning with asset categories, depreciation schedules,
// project tracking, and ROI analysis. Manufacturing + tech hybrid company.
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from '../engines/TemplateLibrary';

function makePeriodRange(
  start: string,
  end: string,
  frequency: 'monthly' | 'quarterly' | 'annual'
) {
  return { start, end, frequency };
}

const drivers: DriverDefinition[] = [
  {
    id: 'cap-machinery-budget',
    name: 'Machinery & Equipment Budget',
    description: 'Annual budget for production equipment',
    unit: 'currency',
    defaultValue: 8000000,
    minValue: 0,
    maxValue: 500000000,
    step: 100000,
    category: 'Production',
    tags: ['machinery'],
  },
  {
    id: 'cap-it-budget',
    name: 'IT Infrastructure Budget',
    description: 'Annual IT hardware and infrastructure',
    unit: 'currency',
    defaultValue: 3500000,
    minValue: 0,
    maxValue: 200000000,
    step: 50000,
    category: 'Technology',
    tags: ['it', 'servers'],
  },
  {
    id: 'cap-facilities-budget',
    name: 'Facilities Budget',
    description: 'Building improvements and leasehold',
    unit: 'currency',
    defaultValue: 2000000,
    minValue: 0,
    maxValue: 100000000,
    step: 50000,
    category: 'Facilities',
    tags: ['building'],
  },
  {
    id: 'cap-vehicle-budget',
    name: 'Vehicle & Fleet Budget',
    description: 'Company vehicles and fleet',
    unit: 'currency',
    defaultValue: 1200000,
    minValue: 0,
    maxValue: 50000000,
    step: 10000,
    category: 'Fleet',
    tags: ['vehicles'],
  },
  {
    id: 'cap-leasehold-budget',
    name: 'Leasehold Improvements',
    description: 'Tenant improvements to leased space',
    unit: 'currency',
    defaultValue: 1500000,
    minValue: 0,
    maxValue: 50000000,
    step: 25000,
    category: 'Facilities',
    tags: ['leasehold'],
  },
  {
    id: 'cap-machinery-life',
    name: 'Machinery Useful Life',
    description: 'Depreciation life for machinery (years)',
    unit: 'count',
    defaultValue: 10,
    minValue: 1,
    maxValue: 30,
    step: 1,
    category: 'Depreciation',
    tags: ['useful-life'],
  },
  {
    id: 'cap-it-life',
    name: 'IT Useful Life',
    description: 'Depreciation life for IT (years)',
    unit: 'count',
    defaultValue: 5,
    minValue: 1,
    maxValue: 10,
    step: 1,
    category: 'Depreciation',
    tags: ['useful-life'],
  },
  {
    id: 'cap-facilities-life',
    name: 'Facilities Useful Life',
    description: 'Depreciation life for buildings (years)',
    unit: 'count',
    defaultValue: 30,
    minValue: 5,
    maxValue: 50,
    step: 1,
    category: 'Depreciation',
    tags: ['useful-life'],
  },
  {
    id: 'cap-disposal-rate',
    name: 'Asset Disposal Rate',
    description: 'Percentage of assets retired annually',
    unit: 'percentage',
    defaultValue: 5,
    minValue: 0,
    maxValue: 30,
    step: 1,
    category: 'Disposal',
    tags: ['disposal', 'retirement'],
  },
  {
    id: 'cap-revenue-pct',
    name: 'CapEx as % of Revenue',
    description: 'Total CapEx as percentage of revenue',
    unit: 'percentage',
    defaultValue: 6,
    minValue: 1,
    maxValue: 30,
    step: 0.5,
    category: 'Benchmark',
    tags: ['benchmark'],
  },
];

const accounts: AccountDefinition[] = [
  // CapEx Budget by Category
  {
    id: 'cap-total-capex',
    name: 'Total Capital Expenditures',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Total CapEx budget',
    isCalculated: true,
  },
  {
    id: 'cap-machinery-capex',
    name: 'Machinery & Equipment',
    parentId: 'cap-total-capex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Production equipment',
    isCalculated: false,
  },
  {
    id: 'cap-it-capex',
    name: 'IT Infrastructure',
    parentId: 'cap-total-capex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Servers, network, hardware',
    isCalculated: false,
  },
  {
    id: 'cap-facilities-capex',
    name: 'Facilities',
    parentId: 'cap-total-capex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Building improvements',
    isCalculated: false,
  },
  {
    id: 'cap-vehicle-capex',
    name: 'Vehicles & Fleet',
    parentId: 'cap-total-capex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Company vehicles',
    isCalculated: false,
  },
  {
    id: 'cap-leasehold-capex',
    name: 'Leasehold Improvements',
    parentId: 'cap-total-capex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Tenant improvements',
    isCalculated: false,
  },

  // Gross PP&E
  {
    id: 'cap-gross-ppe',
    name: 'Gross PP&E',
    parentId: null,
    accountType: 'asset',
    debitSide: 'debit',
    description: 'Total gross property, plant & equipment',
    isCalculated: true,
  },
  {
    id: 'cap-machinery-gross',
    name: 'Machinery (Gross)',
    parentId: 'cap-gross-ppe',
    accountType: 'asset',
    debitSide: 'debit',
    description: 'Gross machinery value',
    isCalculated: true,
  },
  {
    id: 'cap-it-gross',
    name: 'IT Equipment (Gross)',
    parentId: 'cap-gross-ppe',
    accountType: 'asset',
    debitSide: 'debit',
    description: 'Gross IT value',
    isCalculated: true,
  },
  {
    id: 'cap-facilities-gross',
    name: 'Facilities (Gross)',
    parentId: 'cap-gross-ppe',
    accountType: 'asset',
    debitSide: 'debit',
    description: 'Gross facilities value',
    isCalculated: true,
  },

  // Depreciation
  {
    id: 'cap-total-depreciation',
    name: 'Total Depreciation',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Annual depreciation expense',
    isCalculated: true,
  },
  {
    id: 'cap-machinery-dep',
    name: 'Machinery Depreciation',
    parentId: 'cap-total-depreciation',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Machinery D&A',
    isCalculated: true,
  },
  {
    id: 'cap-it-dep',
    name: 'IT Depreciation',
    parentId: 'cap-total-depreciation',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'IT D&A',
    isCalculated: true,
  },
  {
    id: 'cap-facilities-dep',
    name: 'Facilities Depreciation',
    parentId: 'cap-total-depreciation',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Facilities D&A',
    isCalculated: true,
  },

  // Accumulated Depreciation
  {
    id: 'cap-accum-dep',
    name: 'Accumulated Depreciation',
    parentId: null,
    accountType: 'asset',
    debitSide: 'credit',
    description: 'Total accumulated depreciation',
    isCalculated: true,
  },
  {
    id: 'cap-net-ppe',
    name: 'Net PP&E',
    parentId: null,
    accountType: 'asset',
    debitSide: 'debit',
    description: 'Net book value',
    isCalculated: true,
  },

  // Disposals
  {
    id: 'cap-disposals',
    name: 'Asset Disposals',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Assets retired this period',
    isCalculated: true,
  },

  // Metrics
  {
    id: 'cap-capex-to-revenue',
    name: 'CapEx to Revenue %',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'CapEx / Revenue',
    isCalculated: true,
  },
  {
    id: 'cap-avg-useful-life',
    name: 'Weighted Avg Useful Life',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Average asset life',
    isCalculated: true,
  },
  {
    id: 'cap-asset-age',
    name: 'Average Asset Age',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Avg age of assets',
    isCalculated: true,
  },
];

const cascadeRules: CascadeRuleDefinition[] = [
  {
    id: 'cap-c-1',
    driverId: 'cap-machinery-budget',
    targetAccountId: 'cap-machinery-capex',
    cascadeType: 'direct',
    impactType: 'replacement',
    weight: 1,
    description: 'Budget drives machinery CapEx',
  },
  {
    id: 'cap-c-2',
    driverId: 'cap-it-budget',
    targetAccountId: 'cap-it-capex',
    cascadeType: 'direct',
    impactType: 'replacement',
    weight: 1,
    description: 'Budget drives IT CapEx',
  },
  {
    id: 'cap-c-3',
    driverId: 'cap-facilities-budget',
    targetAccountId: 'cap-facilities-capex',
    cascadeType: 'direct',
    impactType: 'replacement',
    weight: 1,
    description: 'Budget drives facilities CapEx',
  },
  {
    id: 'cap-c-4',
    driverId: 'cap-machinery-life',
    targetAccountId: 'cap-machinery-dep',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current / x',
    description: 'Life drives depreciation',
  },
  {
    id: 'cap-c-5',
    driverId: 'cap-it-life',
    targetAccountId: 'cap-it-dep',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current / x',
    description: 'Life drives IT depreciation',
  },
  {
    id: 'cap-c-6',
    driverId: 'cap-disposal-rate',
    targetAccountId: 'cap-disposals',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Disposal rate drives retirements',
  },
];

export function buildCapExPlanTemplate(): FPTemplate {
  return {
    id: 'tpl-capex-plan',
    name: 'Capital Expenditure Plan',
    description:
      'Multi-category CapEx planning with asset tracking, depreciation schedules (straight-line), disposals, and ROI benchmarking. Pre-populated for a manufacturing + tech company with $8M machinery, $3.5M IT, $2M facilities budgets.',
    industry: 'Manufacturing',
    category: 'capex',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: ['capex', 'capital-expenditure', 'depreciation', 'pp&e', 'asset-management', 'budget'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
