// =============================================================================
// CASH FLOW FORECAST TEMPLATE
// 13-week rolling cash flow forecast with AR/AP aging, debt service,
// and scenario modeling. Mid-market company with $30M monthly revenue.
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from '../engines/TemplateLibrary';

function makePeriodRange(
  start: string,
  end: string,
  frequency: 'monthly' | 'quarterly' | 'annual'
) {
  return { start, end, frequency };
}

const drivers: DriverDefinition[] = [
  {
    id: 'cf-collections-rate',
    name: 'Collection Rate',
    description: 'Percentage of AR collected per month',
    unit: 'percentage',
    defaultValue: 85,
    minValue: 50,
    maxValue: 100,
    step: 1,
    category: 'Collections',
    tags: ['ar', 'collections'],
  },
  {
    id: 'cf-avg-collection-days',
    name: 'Average Collection Days',
    description: 'Average days to collect receivables',
    unit: 'days',
    defaultValue: 42,
    minValue: 0,
    maxValue: 180,
    step: 1,
    category: 'Collections',
    tags: ['dso'],
  },
  {
    id: 'cf-payment-days',
    name: 'Average Payment Days',
    description: 'Average days to pay vendors',
    unit: 'days',
    defaultValue: 38,
    minValue: 0,
    maxValue: 120,
    step: 1,
    category: 'Payments',
    tags: ['dpo'],
  },
  {
    id: 'cf-monthly-revenue',
    name: 'Monthly Revenue',
    description: 'Average monthly revenue',
    unit: 'currency',
    defaultValue: 30000000,
    minValue: 0,
    maxValue: 1000000000,
    step: 100000,
    category: 'Revenue',
    tags: ['revenue'],
  },
  {
    id: 'cf-revenue-growth',
    name: 'Monthly Revenue Growth',
    description: 'Month-over-month revenue growth',
    unit: 'percentage',
    defaultValue: 2,
    minValue: -20,
    maxValue: 30,
    step: 0.5,
    category: 'Revenue',
    tags: ['growth'],
  },
  {
    id: 'cf-payroll-pct',
    name: 'Payroll as % of Revenue',
    description: 'Total payroll as percentage of revenue',
    unit: 'percentage',
    defaultValue: 35,
    minValue: 10,
    maxValue: 70,
    step: 1,
    category: 'Expenses',
    tags: ['payroll'],
  },
  {
    id: 'cf-rent-monthly',
    name: 'Monthly Rent',
    description: 'Monthly rent and occupancy cost',
    unit: 'currency',
    defaultValue: 450000,
    minValue: 0,
    maxValue: 10000000,
    step: 10000,
    category: 'Expenses',
    tags: ['rent'],
  },
  {
    id: 'cf-min-cash-balance',
    name: 'Minimum Cash Balance',
    description: 'Target minimum cash on hand',
    unit: 'currency',
    defaultValue: 5000000,
    minValue: 0,
    maxValue: 100000000,
    step: 100000,
    category: 'Liquidity',
    tags: ['cash', 'minimum'],
  },
  {
    id: 'cf-credit-line-limit',
    name: 'Credit Line Limit',
    description: 'Maximum revolving credit facility',
    unit: 'currency',
    defaultValue: 15000000,
    minValue: 0,
    maxValue: 500000000,
    step: 1000000,
    category: 'Financing',
    tags: ['credit', 'facility'],
  },
  {
    id: 'cf-interest-rate',
    name: 'Credit Line Interest Rate',
    description: 'Annual interest rate on credit facility',
    unit: 'percentage',
    defaultValue: 7.5,
    minValue: 0,
    maxValue: 25,
    step: 0.25,
    category: 'Financing',
    tags: ['interest'],
  },
];

const accounts: AccountDefinition[] = [
  // Opening Balance
  {
    id: 'cf-opening-cash',
    name: 'Opening Cash Balance',
    parentId: null,
    accountType: 'asset',
    debitSide: 'debit',
    description: 'Cash at start of period',
    isCalculated: true,
  },

  // Cash Inflows
  {
    id: 'cf-total-inflows',
    name: 'Total Cash Inflows',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Total cash received',
    isCalculated: true,
  },
  {
    id: 'cf-cash-sales',
    name: 'Cash Sales',
    parentId: 'cf-total-inflows',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Immediate cash receipts',
    isCalculated: true,
  },
  {
    id: 'cf-ar-collections',
    name: 'AR Collections',
    parentId: 'cf-total-inflows',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Collections on receivables',
    isCalculated: true,
  },
  {
    id: 'cf-other-income',
    name: 'Other Income',
    parentId: 'cf-total-inflows',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Interest income, misc',
    isCalculated: false,
  },
  {
    id: 'cf-credit-draws',
    name: 'Credit Line Draws',
    parentId: 'cf-total-inflows',
    accountType: 'liability',
    debitSide: 'credit',
    description: 'Draws on credit facility',
    isCalculated: true,
  },

  // Cash Outflows
  {
    id: 'cf-total-outflows',
    name: 'Total Cash Outflows',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Total cash paid',
    isCalculated: true,
  },
  {
    id: 'cf-payroll-payment',
    name: 'Payroll',
    parentId: 'cf-total-outflows',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Payroll disbursements',
    isCalculated: true,
  },
  {
    id: 'cf-vendor-payments',
    name: 'Vendor Payments',
    parentId: 'cf-total-outflows',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'AP payments',
    isCalculated: true,
  },
  {
    id: 'cf-rent-payment',
    name: 'Rent & Occupancy',
    parentId: 'cf-total-outflows',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Rent payments',
    isCalculated: true,
  },
  {
    id: 'cf-debt-service',
    name: 'Debt Service',
    parentId: 'cf-total-outflows',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Loan principal + interest',
    isCalculated: false,
  },
  {
    id: 'cf-capex-payment',
    name: 'Capital Expenditures',
    parentId: 'cf-total-outflows',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'CapEx payments',
    isCalculated: false,
  },
  {
    id: 'cf-tax-payment',
    name: 'Tax Payments',
    parentId: 'cf-total-outflows',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Quarterly tax payments',
    isCalculated: false,
  },
  {
    id: 'cf-credit-repayment',
    name: 'Credit Line Repayment',
    parentId: 'cf-total-outflows',
    accountType: 'liability',
    debitSide: 'debit',
    description: 'Credit facility repayments',
    isCalculated: true,
  },
  {
    id: 'cf-other-payment',
    name: 'Other Payments',
    parentId: 'cf-total-outflows',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Miscellaneous',
    isCalculated: false,
  },

  // Net Cash Flow
  {
    id: 'cf-net-cash-flow',
    name: 'Net Cash Flow',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Inflows minus outflows',
    isCalculated: true,
  },
  {
    id: 'cf-closing-cash',
    name: 'Closing Cash Balance',
    parentId: null,
    accountType: 'asset',
    debitSide: 'debit',
    description: 'Cash at end of period',
    isCalculated: true,
  },
  {
    id: 'cf-credit-outstanding',
    name: 'Credit Line Balance',
    parentId: null,
    accountType: 'liability',
    debitSide: 'credit',
    description: 'Outstanding credit facility',
    isCalculated: true,
  },
  {
    id: 'cf-cash-runway',
    name: 'Cash Runway (Months)',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Months of cash remaining',
    isCalculated: true,
  },
];

const cascadeRules: CascadeRuleDefinition[] = [
  {
    id: 'cf-c-1',
    driverId: 'cf-monthly-revenue',
    targetAccountId: 'cf-cash-sales',
    cascadeType: 'direct',
    impactType: 'multiplicative',
    weight: 0.15,
    description: '15% of revenue is cash sales',
  },
  {
    id: 'cf-c-2',
    driverId: 'cf-collections-rate',
    targetAccountId: 'cf-ar-collections',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Collection rate drives AR inflow',
  },
  {
    id: 'cf-c-3',
    driverId: 'cf-payroll-pct',
    targetAccountId: 'cf-payroll-payment',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Payroll % drives payroll outflow',
  },
  {
    id: 'cf-c-4',
    driverId: 'cf-rent-monthly',
    targetAccountId: 'cf-rent-payment',
    cascadeType: 'direct',
    impactType: 'replacement',
    weight: 1,
    description: 'Monthly rent drives rent payment',
  },
  {
    id: 'cf-c-5',
    driverId: 'cf-revenue-growth',
    targetAccountId: 'cf-cash-sales',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'prev * (1 + x / 100)',
    description: 'Growth drives revenue',
  },
];

export function buildCashFlowForecastTemplate(): FPTemplate {
  return {
    id: 'tpl-cash-flow-forecast',
    name: 'Cash Flow Forecast',
    description:
      '13-week rolling cash flow forecast with AR/AP aging, revolving credit facility modeling, debt service scheduling, and minimum cash balance alerts. Pre-populated with $30M/month mid-market data.',
    industry: 'Manufacturing',
    category: 'cashflow',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: ['cash-flow', 'forecast', 'liquidity', 'working-capital', 'treasury', '13-week'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
