// =============================================================================
// CONSTRUCTION PROJECT COSTING TEMPLATE
// Job costing with cost codes, labor tracking, material procurement,
// subcontractor management, and change order tracking. $50M commercial project.
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from '../engines/TemplateLibrary';

function makePeriodRange(
  start: string,
  end: string,
  frequency: 'monthly' | 'quarterly' | 'annual'
) {
  return { start, end, frequency };
}

const drivers: DriverDefinition[] = [
  {
    id: 'con-contract-value',
    name: 'Total Contract Value',
    description: 'Total project contract amount',
    unit: 'currency',
    defaultValue: 50000000,
    minValue: 100000,
    maxValue: 10000000000,
    step: 100000,
    category: 'Contract',
    tags: ['contract'],
  },
  {
    id: 'con-labor-pct',
    name: 'Labor % of Budget',
    description: 'Labor costs as % of total budget',
    unit: 'percentage',
    defaultValue: 35,
    minValue: 10,
    maxValue: 60,
    step: 1,
    category: 'Cost',
    tags: ['labor'],
  },
  {
    id: 'con-material-pct',
    name: 'Materials % of Budget',
    description: 'Material costs as % of total budget',
    unit: 'percentage',
    defaultValue: 40,
    minValue: 15,
    maxValue: 70,
    step: 1,
    category: 'Cost',
    tags: ['materials'],
  },
  {
    id: 'con-subcontractor-pct',
    name: 'Subcontractor % of Budget',
    description: 'Subcontractor costs as % of total',
    unit: 'percentage',
    defaultValue: 20,
    minValue: 5,
    maxValue: 50,
    step: 1,
    category: 'Cost',
    tags: ['subcontractor'],
  },
  {
    id: 'con-overhead-pct',
    name: 'Overhead % of Direct Costs',
    description: 'General conditions as % of direct costs',
    unit: 'percentage',
    defaultValue: 12,
    minValue: 3,
    maxValue: 25,
    step: 0.5,
    category: 'Overhead',
    tags: ['overhead'],
  },
  {
    id: 'con-profit-margin',
    name: 'Target Profit Margin',
    description: 'Target net profit margin',
    unit: 'percentage',
    defaultValue: 8,
    minValue: 0,
    maxValue: 25,
    step: 0.5,
    category: 'Profit',
    tags: ['margin'],
  },
  {
    id: 'con-retention-pct',
    name: 'Retention Holdback %',
    description: 'Owner retention holdback',
    unit: 'percentage',
    defaultValue: 10,
    minValue: 0,
    maxValue: 20,
    step: 1,
    category: 'Billing',
    tags: ['retention'],
  },
  {
    id: 'con-contingency-pct',
    name: 'Contingency % of Budget',
    description: 'Budget contingency reserve',
    unit: 'percentage',
    defaultValue: 5,
    minValue: 0,
    maxValue: 15,
    step: 0.5,
    category: 'Risk',
    tags: ['contingency'],
  },
  {
    id: 'con-duration-months',
    name: 'Project Duration',
    description: 'Total project duration in months',
    unit: 'months',
    defaultValue: 24,
    minValue: 1,
    maxValue: 120,
    step: 1,
    category: 'Schedule',
    tags: ['duration'],
  },
  {
    id: 'con-change-order-rate',
    name: 'Change Order Rate',
    description: 'Expected change orders as % of contract',
    unit: 'percentage',
    defaultValue: 8,
    minValue: 0,
    maxValue: 30,
    step: 1,
    category: 'Risk',
    tags: ['change-order'],
  },
];

const accounts: AccountDefinition[] = [
  // Contract
  {
    id: 'con-contract-amount',
    name: 'Original Contract Amount',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Base contract',
    isCalculated: false,
  },
  {
    id: 'con-change-orders',
    name: 'Approved Change Orders',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Net change orders',
    isCalculated: true,
  },
  {
    id: 'con-revised-contract',
    name: 'Revised Contract Amount',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Contract + COs',
    isCalculated: true,
  },

  // Cost Budget
  {
    id: 'con-total-budget',
    name: 'Total Project Budget',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Total estimated cost',
    isCalculated: true,
  },
  {
    id: 'con-labor-budget',
    name: 'Labor Budget',
    parentId: 'con-total-budget',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Craft labor budget',
    isCalculated: true,
  },
  {
    id: 'con-material-budget',
    name: 'Material Budget',
    parentId: 'con-total-budget',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Material procurement',
    isCalculated: true,
  },
  {
    id: 'con-subcontractor-budget',
    name: 'Subcontractor Budget',
    parentId: 'con-total-budget',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Subcontractor agreements',
    isCalculated: true,
  },
  {
    id: 'con-overhead-budget',
    name: 'General Conditions',
    parentId: 'con-total-budget',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Project overhead',
    isCalculated: true,
  },
  {
    id: 'con-contingency',
    name: 'Contingency Reserve',
    parentId: 'con-total-budget',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Budget contingency',
    isCalculated: true,
  },

  // Actual Costs
  {
    id: 'con-total-actual',
    name: 'Total Actual Cost',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Costs incurred to date',
    isCalculated: true,
  },
  {
    id: 'con-labor-actual',
    name: 'Labor Cost (Actual)',
    parentId: 'con-total-actual',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Actual labor',
    isCalculated: false,
  },
  {
    id: 'con-material-actual',
    name: 'Material Cost (Actual)',
    parentId: 'con-total-actual',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Actual materials',
    isCalculated: false,
  },
  {
    id: 'con-subcontractor-actual',
    name: 'Subcontractor Cost (Actual)',
    parentId: 'con-total-actual',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Actual subs',
    isCalculated: false,
  },

  // Billing
  {
    id: 'con-total-billed',
    name: 'Total Billed to Date',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Invoiced amount',
    isCalculated: false,
  },
  {
    id: 'con-retention-held',
    name: 'Retention Held',
    parentId: null,
    accountType: 'asset',
    debitSide: 'debit',
    description: 'Retention holdback',
    isCalculated: true,
  },
  {
    id: 'con-net-billed',
    name: 'Net Billed (Cash Received)',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Billed minus retention',
    isCalculated: true,
  },

  // Variance
  {
    id: 'con-cost-variance',
    name: 'Cost Variance',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Budget - Actual',
    isCalculated: true,
  },
  {
    id: 'con-schedule-variance',
    name: 'Schedule Variance %',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Earned vs planned',
    isCalculated: true,
  },
  {
    id: 'con-percent-complete',
    name: 'Percent Complete',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Physical completion %',
    isCalculated: true,
  },
  {
    id: 'con-earned-value',
    name: 'Earned Value',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'EV = % complete * budget',
    isCalculated: true,
  },
  {
    id: 'con-etc',
    name: 'Estimate to Complete',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Remaining cost estimate',
    isCalculated: true,
  },
  {
    id: 'con-eac',
    name: 'Estimate at Completion',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Total projected cost',
    isCalculated: true,
  },
  {
    id: 'con-gross-profit',
    name: 'Projected Gross Profit',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Revenue minus EAC',
    isCalculated: true,
  },
];

const cascadeRules: CascadeRuleDefinition[] = [
  {
    id: 'con-c-1',
    driverId: 'con-contract-value',
    targetAccountId: 'con-contract-amount',
    cascadeType: 'direct',
    impactType: 'replacement',
    weight: 1,
    description: 'Contract value drives base contract',
  },
  {
    id: 'con-c-2',
    driverId: 'con-labor-pct',
    targetAccountId: 'con-labor-budget',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Labor % drives labor budget',
  },
  {
    id: 'con-c-3',
    driverId: 'con-material-pct',
    targetAccountId: 'con-material-budget',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Material % drives material budget',
  },
  {
    id: 'con-c-4',
    driverId: 'con-subcontractor-pct',
    targetAccountId: 'con-subcontractor-budget',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Sub % drives sub budget',
  },
  {
    id: 'con-c-5',
    driverId: 'con-overhead-pct',
    targetAccountId: 'con-overhead-budget',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'OH % drives overhead',
  },
  {
    id: 'con-c-6',
    driverId: 'con-contingency-pct',
    targetAccountId: 'con-contingency',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Contingency % drives reserve',
  },
  {
    id: 'con-c-7',
    driverId: 'con-retention-pct',
    targetAccountId: 'con-retention-held',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Retention % drives holdback',
  },
  {
    id: 'con-c-8',
    driverId: 'con-change-order-rate',
    targetAccountId: 'con-change-orders',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'CO rate drives change orders',
  },
];

export function buildConstructionProjectCostingTemplate(): FPTemplate {
  return {
    id: 'tpl-construction-costing',
    name: 'Construction Project Costing',
    description:
      'Job costing template for commercial construction with cost codes, earned value analysis, change order tracking, retention management, and EAC forecasting. Pre-populated for a $50M commercial project.',
    industry: 'Manufacturing',
    category: 'cogs',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2027-12', 'monthly'),
    tags: ['construction', 'job-costing', 'earned-value', 'change-orders', 'retention', 'project'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
