// =============================================================================
// ENERGY SECTOR PLANNING TEMPLATE
// Integrated energy company model with upstream production, midstream
// throughput, downstream refining margins, and renewable energy portfolio.
// $5B revenue integrated energy company.
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from '../engines/TemplateLibrary';

function makePeriodRange(
  start: string,
  end: string,
  frequency: 'monthly' | 'quarterly' | 'annual'
) {
  return { start, end, frequency };
}

const drivers: DriverDefinition[] = [
  {
    id: 'enp-oil-production',
    name: 'Oil Production (bbl/day)',
    description: 'Daily oil production in barrels',
    unit: 'count',
    defaultValue: 85000,
    minValue: 0,
    maxValue: 2000000,
    step: 1000,
    category: 'Upstream',
    tags: ['production', 'oil'],
  },
  {
    id: 'enp-gas-production',
    name: 'Gas Production (Mcf/day)',
    description: 'Daily natural gas production',
    unit: 'count',
    defaultValue: 350000,
    minValue: 0,
    maxValue: 10000000,
    step: 10000,
    category: 'Upstream',
    tags: ['production', 'gas'],
  },
  {
    id: 'enp-wti-price',
    name: 'WTI Crude Price',
    description: 'West Texas Intermediate price per barrel',
    unit: 'currency',
    defaultValue: 78,
    minValue: 20,
    maxValue: 200,
    step: 1,
    category: 'Pricing',
    tags: ['oil', 'commodity'],
  },
  {
    id: 'enp-henry-hub',
    name: 'Henry Hub Gas Price',
    description: 'Natural gas price per MMBtu',
    unit: 'currency',
    defaultValue: 3.25,
    minValue: 0.5,
    maxValue: 20,
    step: 0.25,
    category: 'Pricing',
    tags: ['gas', 'commodity'],
  },
  {
    id: 'enp-refinery-throughput',
    name: 'Refinery Throughput (bbl/day)',
    description: 'Daily refinery processing volume',
    unit: 'count',
    defaultValue: 250000,
    minValue: 0,
    maxValue: 2000000,
    step: 10000,
    category: 'Downstream',
    tags: ['refining'],
  },
  {
    id: 'enp-crack-spread',
    name: 'Crack Spread ($/bbl)',
    description: 'Refining margin per barrel',
    unit: 'currency',
    defaultValue: 18,
    minValue: -5,
    maxValue: 50,
    step: 1,
    category: 'Downstream',
    tags: ['margin', 'refining'],
  },
  {
    id: 'enp-lifting-cost',
    name: 'Lifting Cost ($/BOE)',
    description: 'Operating cost per barrel of oil equivalent',
    unit: 'currency',
    defaultValue: 14,
    minValue: 5,
    maxValue: 80,
    step: 1,
    category: 'Upstream',
    tags: ['opex'],
  },
  {
    id: 'enp-royalty-rate',
    name: 'Royalty Rate',
    description: 'Royalty payments as % of revenue',
    unit: 'percentage',
    defaultValue: 12.5,
    minValue: 0,
    maxValue: 25,
    step: 0.5,
    category: 'Upstream',
    tags: ['royalty'],
  },
  {
    id: 'enp-capex-budget',
    name: 'CapEx Budget',
    description: 'Total capital expenditure budget',
    unit: 'currency',
    defaultValue: 3200000000,
    minValue: 0,
    maxValue: 100000000000,
    step: 100000000,
    category: 'CapEx',
    tags: ['capex'],
  },
  {
    id: 'enp-renewable-capacity-mw',
    name: 'Renewable Capacity (MW)',
    description: 'Installed renewable energy capacity',
    unit: 'count',
    defaultValue: 2500,
    minValue: 0,
    maxValue: 100000,
    step: 100,
    category: 'Renewables',
    tags: ['solar', 'wind'],
  },
  {
    id: 'enp-renewable-cf',
    name: 'Renewable Capacity Factor',
    description: 'Renewable generation capacity factor',
    unit: 'percentage',
    defaultValue: 28,
    minValue: 10,
    maxValue: 55,
    step: 1,
    category: 'Renewables',
    tags: ['capacity-factor'],
  },
  {
    id: 'enp-carbon-price',
    name: 'Carbon Price ($/ton)',
    description: 'Carbon credit/capture cost per ton CO2',
    unit: 'currency',
    defaultValue: 45,
    minValue: 0,
    maxValue: 200,
    step: 5,
    category: 'ESG',
    tags: ['carbon', 'esg'],
  },
  {
    id: 'enp-tax-rate',
    name: 'Effective Tax Rate',
    description: 'Corporate tax rate',
    unit: 'percentage',
    defaultValue: 22,
    minValue: 0,
    maxValue: 50,
    step: 1,
    category: 'Tax',
    tags: ['tax'],
  },
];

const accounts: AccountDefinition[] = [
  // Revenue by Segment
  {
    id: 'enp-total-revenue',
    name: 'Total Revenue',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Total company revenue',
    isCalculated: true,
  },
  {
    id: 'enp-upstream-revenue',
    name: 'Upstream Revenue',
    parentId: 'enp-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Oil & gas production revenue',
    isCalculated: true,
  },
  {
    id: 'enp-downstream-revenue',
    name: 'Downstream Revenue',
    parentId: 'enp-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Refining & marketing revenue',
    isCalculated: true,
  },
  {
    id: 'enp-renewable-revenue',
    name: 'Renewable Energy Revenue',
    parentId: 'enp-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Solar/wind generation revenue',
    isCalculated: true,
  },

  // Upstream Costs
  {
    id: 'enp-upstream-cost',
    name: 'Upstream Operating Cost',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Production operating costs',
    isCalculated: true,
  },
  {
    id: 'enp-royalty-expense',
    name: 'Royalty Expense',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Royalty payments',
    isCalculated: true,
  },
  {
    id: 'enp-dda',
    name: 'DD&A Expense',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Depletion, depreciation, amortization',
    isCalculated: false,
  },

  // Downstream Costs
  {
    id: 'enp-refining-cost',
    name: 'Refining Operating Cost',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Refinery operating costs',
    isCalculated: false,
  },

  // Carbon & ESG
  {
    id: 'enp-carbon-cost',
    name: 'Carbon Cost / Credits',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Carbon capture or credit cost',
    isCalculated: true,
  },

  // Profitability
  {
    id: 'enp-gross-profit',
    name: 'Gross Profit',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Revenue minus direct costs',
    isCalculated: true,
  },
  {
    id: 'enp-operating-income',
    name: 'Operating Income',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'EBIT',
    isCalculated: true,
  },
  {
    id: 'enp-net-income',
    name: 'Net Income',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Bottom line',
    isCalculated: true,
  },

  // Production Metrics
  {
    id: 'enp-boe-per-day',
    name: 'Total BOE per Day',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Barrels of oil equivalent daily',
    isCalculated: true,
  },
  {
    id: 'enp-boe-per-year',
    name: 'Annual BOE Production',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Annual production volume',
    isCalculated: true,
  },
  {
    id: 'enp-revenue-per-boe',
    name: 'Revenue per BOE',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Revenue / BOE',
    isCalculated: true,
  },
  {
    id: 'enp-fcf',
    name: 'Free Cash Flow',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Operating CF minus CapEx',
    isCalculated: true,
  },
  {
    id: 'enp-renewable-gwh',
    name: 'Renewable Generation (GWh)',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Annual renewable generation',
    isCalculated: true,
  },
];

const cascadeRules: CascadeRuleDefinition[] = [
  {
    id: 'enp-c-1',
    driverId: 'enp-oil-production',
    targetAccountId: 'enp-upstream-revenue',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'x * current * 365',
    description: 'Oil production drives upstream revenue',
  },
  {
    id: 'enp-c-2',
    driverId: 'enp-wti-price',
    targetAccountId: 'enp-upstream-revenue',
    cascadeType: 'direct',
    impactType: 'multiplicative',
    weight: 0.7,
    description: 'WTI price drives oil revenue',
  },
  {
    id: 'enp-c-3',
    driverId: 'enp-henry-hub',
    targetAccountId: 'enp-upstream-revenue',
    cascadeType: 'direct',
    impactType: 'multiplicative',
    weight: 0.3,
    description: 'Gas price drives gas revenue',
  },
  {
    id: 'enp-c-4',
    driverId: 'enp-lifting-cost',
    targetAccountId: 'enp-upstream-cost',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'x * enp_boe_per_day * 365',
    description: 'Lifting cost drives upstream opex',
  },
  {
    id: 'enp-c-5',
    driverId: 'enp-royalty-rate',
    targetAccountId: 'enp-royalty-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Royalty rate drives royalty expense',
  },
  {
    id: 'enp-c-6',
    driverId: 'enp-refinery-throughput',
    targetAccountId: 'enp-downstream-revenue',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'x * enp_crack_spread * 365',
    description: 'Throughput + crack spread drives downstream',
  },
  {
    id: 'enp-c-7',
    driverId: 'enp-carbon-price',
    targetAccountId: 'enp-carbon-cost',
    cascadeType: 'direct',
    impactType: 'multiplicative',
    weight: 1,
    description: 'Carbon price drives carbon cost',
  },
  {
    id: 'enp-c-8',
    driverId: 'enp-tax-rate',
    targetAccountId: 'enp-net-income',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * (1 - x / 100)',
    description: 'Tax rate drives net income',
  },
];

export function buildEnergySectorPlanningTemplate(): FPTemplate {
  return {
    id: 'tpl-energy-sector',
    name: 'Energy Sector Planning',
    description:
      'Integrated energy company model covering upstream production (oil & gas), downstream refining margins (crack spread), renewable energy portfolio, carbon pricing, and reserve economics. Pre-populated for a $5B integrated energy company.',
    industry: 'Energy',
    category: 'revenue',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'quarterly'),
    tags: ['energy', 'oil', 'gas', 'refining', 'renewable', 'carbon', 'upstream', 'downstream'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
