// =============================================================================
// GOVERNMENT BUDGET TEMPLATE
// Municipal/government budget with fund accounting, department appropriations,
// revenue sources, and budget-to-actual tracking. Mid-size city ($500M budget).
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from '../engines/TemplateLibrary';

function makePeriodRange(
  start: string,
  end: string,
  frequency: 'monthly' | 'quarterly' | 'annual'
) {
  return { start, end, frequency };
}

const drivers: DriverDefinition[] = [
  {
    id: 'gov-property-tax-rate',
    name: 'Property Tax Rate (mills)',
    description: 'Property tax rate in mills per $1000 assessed value',
    unit: 'absolute',
    defaultValue: 12.5,
    minValue: 0,
    maxValue: 50,
    step: 0.5,
    category: 'Revenue',
    tags: ['property-tax'],
  },
  {
    id: 'gov-assessed-valuation',
    name: 'Total Assessed Valuation',
    description: 'Total taxable property value',
    unit: 'currency',
    defaultValue: 28000000000,
    minValue: 0,
    maxValue: 500000000000,
    step: 100000000,
    category: 'Revenue',
    tags: ['assessed-value'],
  },
  {
    id: 'gov-sales-tax-rate',
    name: 'Sales Tax Rate',
    description: 'Local sales tax rate',
    unit: 'percentage',
    defaultValue: 2.5,
    minValue: 0,
    maxValue: 10,
    step: 0.1,
    category: 'Revenue',
    tags: ['sales-tax'],
  },
  {
    id: 'gov-sales-tax-base',
    name: 'Taxable Sales Base',
    description: 'Total taxable sales in jurisdiction',
    unit: 'currency',
    defaultValue: 8500000000,
    minValue: 0,
    maxValue: 200000000000,
    step: 100000000,
    category: 'Revenue',
    tags: ['sales-base'],
  },
  {
    id: 'gov-population',
    name: 'City Population',
    description: 'Total city population',
    unit: 'count',
    defaultValue: 185000,
    minValue: 0,
    maxValue: 10000000,
    step: 1000,
    category: 'Demographics',
    tags: ['population'],
  },
  {
    id: 'gov-inflation',
    name: 'Cost Inflation',
    description: 'General cost inflation factor',
    unit: 'percentage',
    defaultValue: 3.2,
    minValue: 0,
    maxValue: 15,
    step: 0.1,
    category: 'Macro',
    tags: ['inflation'],
  },
  {
    id: 'gov-public-safety-pct',
    name: 'Public Safety % of Budget',
    description: 'Police, fire, EMS as % of general fund',
    unit: 'percentage',
    defaultValue: 42,
    minValue: 20,
    maxValue: 65,
    step: 1,
    category: 'Departments',
    tags: ['police', 'fire'],
  },
  {
    id: 'gov-transportation-pct',
    name: 'Transportation % of Budget',
    description: 'Roads, transit, infrastructure as % of budget',
    unit: 'percentage',
    defaultValue: 15,
    minValue: 5,
    maxValue: 30,
    step: 1,
    category: 'Departments',
    tags: ['roads', 'transit'],
  },
  {
    id: 'gov-debt-service-pct',
    name: 'Debt Service % of Revenue',
    description: 'Debt payments as % of total revenue',
    unit: 'percentage',
    defaultValue: 8,
    minValue: 0,
    maxValue: 25,
    step: 0.5,
    category: 'Debt',
    tags: ['bonds'],
  },
  {
    id: 'gov-reserve-pct',
    name: 'Reserve Fund % of Budget',
    description: 'Rainy day fund as % of budget',
    unit: 'percentage',
    defaultValue: 15,
    minValue: 5,
    maxValue: 30,
    step: 1,
    category: 'Reserves',
    tags: ['reserve'],
  },
];

const accounts: AccountDefinition[] = [
  // General Fund Revenue
  {
    id: 'gov-total-revenue',
    name: 'Total General Fund Revenue',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Total revenue',
    isCalculated: true,
  },
  {
    id: 'gov-property-tax',
    name: 'Property Tax Revenue',
    parentId: 'gov-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Ad valorem taxes',
    isCalculated: true,
  },
  {
    id: 'gov-sales-tax',
    name: 'Sales Tax Revenue',
    parentId: 'gov-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Local sales tax',
    isCalculated: true,
  },
  {
    id: 'gov-utility-tax',
    name: 'Utility Tax Revenue',
    parentId: 'gov-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Utility franchise fees',
    isCalculated: false,
  },
  {
    id: 'gov-licenses-permits',
    name: 'Licenses & Permits',
    parentId: 'gov-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Building permits, business licenses',
    isCalculated: false,
  },
  {
    id: 'gov-intergovernmental',
    name: 'Intergovernmental Revenue',
    parentId: 'gov-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'State and federal grants',
    isCalculated: false,
  },
  {
    id: 'gov-charges-services',
    name: 'Charges for Services',
    parentId: 'gov-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Recreation, parking, fees',
    isCalculated: false,
  },
  {
    id: 'gov-fines-forfeitures',
    name: 'Fines & Forfeitures',
    parentId: 'gov-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Court fines, forfeitures',
    isCalculated: false,
  },
  {
    id: 'gov-investment-income',
    name: 'Investment Income',
    parentId: 'gov-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Interest on investments',
    isCalculated: false,
  },

  // General Fund Expenditures
  {
    id: 'gov-total-expenditure',
    name: 'Total General Fund Expenditure',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Total spending',
    isCalculated: true,
  },
  {
    id: 'gov-public-safety-exp',
    name: 'Public Safety',
    parentId: 'gov-total-expenditure',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Police, Fire, EMS',
    isCalculated: true,
  },
  {
    id: 'gov-transportation-exp',
    name: 'Transportation',
    parentId: 'gov-total-expenditure',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Roads, bridges, transit',
    isCalculated: true,
  },
  {
    id: 'gov-health-social',
    name: 'Health & Human Services',
    parentId: 'gov-total-expenditure',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Social services, health dept',
    isCalculated: false,
  },
  {
    id: 'gov-parks-recreation',
    name: 'Parks & Recreation',
    parentId: 'gov-total-expenditure',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Parks, libraries, recreation',
    isCalculated: false,
  },
  {
    id: 'gov-general-government',
    name: 'General Government',
    parentId: 'gov-total-expenditure',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'City admin, legal, HR, IT',
    isCalculated: false,
  },
  {
    id: 'gov-debt-service-exp',
    name: 'Debt Service',
    parentId: 'gov-total-expenditure',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Bond principal + interest',
    isCalculated: true,
  },
  {
    id: 'gov-capital-improvements',
    name: 'Capital Improvements',
    parentId: 'gov-total-expenditure',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Infrastructure projects',
    isCalculated: false,
  },

  // Fund Balance
  {
    id: 'gov-fund-balance-begin',
    name: 'Beginning Fund Balance',
    parentId: null,
    accountType: 'equity',
    debitSide: 'credit',
    description: 'Fund balance at start of year',
    isCalculated: false,
  },
  {
    id: 'gov-net-change',
    name: 'Net Change in Fund Balance',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Revenue minus expenditure',
    isCalculated: true,
  },
  {
    id: 'gov-fund-balance-end',
    name: 'Ending Fund Balance',
    parentId: null,
    accountType: 'equity',
    debitSide: 'credit',
    description: 'Fund balance at end of year',
    isCalculated: true,
  },
  {
    id: 'gov-reserve-fund',
    name: 'Reserve Fund Balance',
    parentId: null,
    accountType: 'equity',
    debitSide: 'credit',
    description: 'Rainy day fund',
    isCalculated: true,
  },

  // Metrics
  {
    id: 'gov-per-capita-spending',
    name: 'Per Capita Spending',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Spending / population',
    isCalculated: true,
  },
  {
    id: 'gov-debt-per-capita',
    name: 'Debt per Capita',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Total debt / population',
    isCalculated: true,
  },
  {
    id: 'gov-reserve-months',
    name: 'Reserve in Months of Spending',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Months of operating reserves',
    isCalculated: true,
  },
];

const cascadeRules: CascadeRuleDefinition[] = [
  {
    id: 'gov-c-1',
    driverId: 'gov-property-tax-rate',
    targetAccountId: 'gov-property-tax',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'assessed_valuation * x / 1000',
    description: 'Tax rate * valuation drives property tax',
  },
  {
    id: 'gov-c-2',
    driverId: 'gov-sales-tax-rate',
    targetAccountId: 'gov-sales-tax',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'sales_base * x / 100',
    description: 'Sales tax rate * base drives sales tax',
  },
  {
    id: 'gov-c-3',
    driverId: 'gov-public-safety-pct',
    targetAccountId: 'gov-public-safety-exp',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Public safety % drives spending',
  },
  {
    id: 'gov-c-4',
    driverId: 'gov-transportation-pct',
    targetAccountId: 'gov-transportation-exp',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Transportation % drives spending',
  },
  {
    id: 'gov-c-5',
    driverId: 'gov-debt-service-pct',
    targetAccountId: 'gov-debt-service-exp',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Debt service % drives debt payments',
  },
  {
    id: 'gov-c-6',
    driverId: 'gov-inflation',
    targetAccountId: 'gov-general-government',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'prev * (1 + x / 100)',
    description: 'Inflation drives cost increases',
  },
];

export function buildGovernmentBudgetTemplate(): FPTemplate {
  return {
    id: 'tpl-government-budget',
    name: 'Government Budget',
    description:
      'Municipal government budget with fund accounting, property/sales tax modeling, department appropriations, intergovernmental revenue, debt service, and reserve fund tracking. Pre-populated for a mid-size city (185K pop, $500M budget).',
    industry: 'Energy',
    category: 'opex',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'quarterly'),
    tags: ['government', 'municipal', 'fund-accounting', 'property-tax', 'public-safety', 'budget'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
