// =============================================================================
// HEADCOUNT PLAN TEMPLATE
// Department-level workforce planning with salary bands, benefits, taxes,
// hiring pipeline, and fully-loaded cost modeling. 500-person company.
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from '../engines/TemplateLibrary';

function makePeriodRange(
  start: string,
  end: string,
  frequency: 'monthly' | 'quarterly' | 'annual'
) {
  return { start, end, frequency };
}

const drivers: DriverDefinition[] = [
  {
    id: 'hc-engineer-count',
    name: 'Engineering Headcount',
    description: 'Current engineering FTEs',
    unit: 'count',
    defaultValue: 150,
    minValue: 0,
    maxValue: 10000,
    step: 1,
    category: 'Engineering',
    tags: ['headcount'],
  },
  {
    id: 'hc-engineer-salary',
    name: 'Avg Engineer Salary',
    description: 'Average engineering base salary',
    unit: 'currency',
    defaultValue: 145000,
    minValue: 50000,
    maxValue: 500000,
    step: 1000,
    category: 'Engineering',
    tags: ['salary'],
  },
  {
    id: 'hc-sales-count',
    name: 'Sales Headcount',
    description: 'Current sales FTEs',
    unit: 'count',
    defaultValue: 80,
    minValue: 0,
    maxValue: 5000,
    step: 1,
    category: 'Sales',
    tags: ['headcount'],
  },
  {
    id: 'hc-sales-salary',
    name: 'Avg Sales Salary',
    description: 'Average sales base salary',
    unit: 'currency',
    defaultValue: 95000,
    minValue: 30000,
    maxValue: 300000,
    step: 1000,
    category: 'Sales',
    tags: ['salary'],
  },
  {
    id: 'hc-marketing-count',
    name: 'Marketing Headcount',
    description: 'Current marketing FTEs',
    unit: 'count',
    defaultValue: 40,
    minValue: 0,
    maxValue: 2000,
    step: 1,
    category: 'Marketing',
    tags: ['headcount'],
  },
  {
    id: 'hc-ga-count',
    name: 'G&A Headcount',
    description: 'General & administrative FTEs',
    unit: 'count',
    defaultValue: 60,
    minValue: 0,
    maxValue: 5000,
    step: 1,
    category: 'G&A',
    tags: ['headcount'],
  },
  {
    id: 'hc-cs-count',
    name: 'Customer Success Headcount',
    description: 'Customer success FTEs',
    unit: 'count',
    defaultValue: 45,
    minValue: 0,
    maxValue: 2000,
    step: 1,
    category: 'Customer Success',
    tags: ['headcount'],
  },
  {
    id: 'hc-attrition-rate',
    name: 'Annual Attrition Rate',
    description: 'Expected annual voluntary turnover',
    unit: 'percentage',
    defaultValue: 15,
    minValue: 0,
    maxValue: 50,
    step: 1,
    category: 'Workforce',
    tags: ['attrition', 'turnover'],
  },
  {
    id: 'hc-benefits-pct',
    name: 'Benefits Load %',
    description: 'Benefits as percentage of base salary',
    unit: 'percentage',
    defaultValue: 28,
    minValue: 10,
    maxValue: 60,
    step: 1,
    category: 'Benefits',
    tags: ['benefits', 'load'],
  },
  {
    id: 'hc-bonus-pct',
    name: 'Target Bonus %',
    description: 'Target bonus as percentage of base',
    unit: 'percentage',
    defaultValue: 15,
    minValue: 0,
    maxValue: 50,
    step: 1,
    category: 'Compensation',
    tags: ['bonus'],
  },
  {
    id: 'hc-equity-pct',
    name: 'Equity Grant %',
    description: 'Annual equity grant as % of base',
    unit: 'percentage',
    defaultValue: 12,
    minValue: 0,
    maxValue: 100,
    step: 1,
    category: 'Compensation',
    tags: ['equity', 'rsu'],
  },
  {
    id: 'hc-new-hires',
    name: 'Planned New Hires',
    description: 'Total new hires for the year',
    unit: 'count',
    defaultValue: 75,
    minValue: 0,
    maxValue: 2000,
    step: 5,
    category: 'Hiring',
    tags: ['hiring'],
  },
  {
    id: 'hc-time-to-fill',
    name: 'Average Time to Fill',
    description: 'Average days to fill open positions',
    unit: 'days',
    defaultValue: 45,
    minValue: 7,
    maxValue: 180,
    step: 1,
    category: 'Hiring',
    tags: ['recruiting'],
  },
];

const accounts: AccountDefinition[] = [
  // Headcount by Department
  {
    id: 'hc-total-fte',
    name: 'Total FTEs',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Total headcount',
    isCalculated: true,
  },
  {
    id: 'hc-engineering-fte',
    name: 'Engineering FTEs',
    parentId: 'hc-total-fte',
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Engineering team',
    isCalculated: true,
  },
  {
    id: 'hc-sales-fte',
    name: 'Sales FTEs',
    parentId: 'hc-total-fte',
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Sales team',
    isCalculated: true,
  },
  {
    id: 'hc-marketing-fte',
    name: 'Marketing FTEs',
    parentId: 'hc-total-fte',
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Marketing team',
    isCalculated: false,
  },
  {
    id: 'hc-ga-fte',
    name: 'G&A FTEs',
    parentId: 'hc-total-fte',
    accountType: 'memo',
    debitSide: 'debit',
    description: 'G&A team',
    isCalculated: false,
  },
  {
    id: 'hc-cs-fte',
    name: 'Customer Success FTEs',
    parentId: 'hc-total-fte',
    accountType: 'memo',
    debitSide: 'debit',
    description: 'CS team',
    isCalculated: false,
  },

  // Compensation Components
  {
    id: 'hc-total-comp',
    name: 'Total Compensation',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'All-in compensation cost',
    isCalculated: true,
  },
  {
    id: 'hc-base-salary',
    name: 'Base Salaries',
    parentId: 'hc-total-comp',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Base salary expense',
    isCalculated: true,
  },
  {
    id: 'hc-bonus-expense',
    name: 'Bonus & Incentives',
    parentId: 'hc-total-comp',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Performance bonuses',
    isCalculated: true,
  },
  {
    id: 'hc-benefits-expense',
    name: 'Benefits (Health, 401k)',
    parentId: 'hc-total-comp',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Benefits cost',
    isCalculated: true,
  },
  {
    id: 'hc-payroll-tax',
    name: 'Payroll Taxes',
    parentId: 'hc-total-comp',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Employer payroll taxes',
    isCalculated: true,
  },
  {
    id: 'hc-equity-expense',
    name: 'Stock-Based Compensation',
    parentId: 'hc-total-comp',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'RSU/option expense',
    isCalculated: true,
  },

  // Cost per Department
  {
    id: 'hc-engineering-cost',
    name: 'Engineering Total Cost',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Fully-loaded engineering cost',
    isCalculated: true,
  },
  {
    id: 'hc-sales-cost',
    name: 'Sales Total Cost',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Fully-loaded sales cost',
    isCalculated: true,
  },
  {
    id: 'hc-marketing-cost',
    name: 'Marketing Total Cost',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Fully-loaded marketing cost',
    isCalculated: false,
  },
  {
    id: 'hc-ga-cost',
    name: 'G&A Total Cost',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Fully-loaded G&A cost',
    isCalculated: false,
  },

  // Hiring Pipeline
  {
    id: 'hc-open-positions',
    name: 'Open Positions',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Current open reqs',
    isCalculated: true,
  },
  {
    id: 'hc-new-hires-actual',
    name: 'New Hires (Actual)',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Hires completed',
    isCalculated: false,
  },
  {
    id: 'hc-attrition-count',
    name: 'Attrition Count',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Employees who left',
    isCalculated: true,
  },
  {
    id: 'hc-cost-per-hire',
    name: 'Cost per Hire',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Recruiting cost per hire',
    isCalculated: true,
  },

  // Metrics
  {
    id: 'hc-revenue-per-employee',
    name: 'Revenue per Employee',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Revenue / FTE',
    isCalculated: true,
  },
  {
    id: 'hc-cost-per-employee',
    name: 'Fully-Loaded Cost per Employee',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Total comp / FTE',
    isCalculated: true,
  },
];

const cascadeRules: CascadeRuleDefinition[] = [
  {
    id: 'hc-c-1',
    driverId: 'hc-engineer-count',
    targetAccountId: 'hc-engineering-fte',
    cascadeType: 'direct',
    impactType: 'replacement',
    weight: 1,
    description: 'Engineer count drives eng FTE',
  },
  {
    id: 'hc-c-2',
    driverId: 'hc-engineer-salary',
    targetAccountId: 'hc-base-salary',
    cascadeType: 'formula',
    impactType: 'additive',
    weight: 1,
    formula: 'x * current / 12',
    description: 'Salary drives base comp',
  },
  {
    id: 'hc-c-3',
    driverId: 'hc-benefits-pct',
    targetAccountId: 'hc-benefits-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Benefits % drives benefits cost',
  },
  {
    id: 'hc-c-4',
    driverId: 'hc-bonus-pct',
    targetAccountId: 'hc-bonus-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Bonus % drives bonus expense',
  },
  {
    id: 'hc-c-5',
    driverId: 'hc-attrition-rate',
    targetAccountId: 'hc-attrition-count',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100 / 12',
    description: 'Attrition drives departures',
  },
  {
    id: 'hc-c-6',
    driverId: 'hc-equity-pct',
    targetAccountId: 'hc-equity-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Equity % drives SBC',
  },
];

export function buildHeadcountPlanTemplate(): FPTemplate {
  return {
    id: 'tpl-headcount-plan',
    name: 'Headcount Plan',
    description:
      'Department-level workforce planning with salary bands, benefits modeling, hiring pipeline tracking, attrition forecasting, and fully-loaded cost analysis. Pre-populated for a 500-person tech company.',
    industry: 'SaaS',
    category: 'workforce',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: ['headcount', 'workforce', 'compensation', 'hiring', 'benefits', 'attrition', 'planning'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
