// =============================================================================
// HEALTHCARE REVENUE CYCLE TEMPLATE
// Hospital/health system revenue cycle with payer mix, CPT coding,
// denial management, and AR days tracking. 400-bed community hospital.
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from '../engines/TemplateLibrary';

function makePeriodRange(
  start: string,
  end: string,
  frequency: 'monthly' | 'quarterly' | 'annual'
) {
  return { start, end, frequency };
}

const drivers: DriverDefinition[] = [
  {
    id: 'hrc-patient-days',
    name: 'Annual Patient Days',
    description: 'Total inpatient days',
    unit: 'count',
    defaultValue: 110000,
    minValue: 0,
    maxValue: 5000000,
    step: 1000,
    category: 'Volume',
    tags: ['patient-days'],
  },
  {
    id: 'hrc-occupancy',
    name: 'Bed Occupancy Rate',
    description: 'Average bed occupancy %',
    unit: 'percentage',
    defaultValue: 75,
    minValue: 30,
    maxValue: 100,
    step: 1,
    category: 'Volume',
    tags: ['occupancy'],
  },
  {
    id: 'hrc-avg-reimbursement',
    name: 'Avg Reimbursement per Day',
    description: 'Average daily reimbursement rate',
    unit: 'currency',
    defaultValue: 2800,
    minValue: 500,
    maxValue: 15000,
    step: 50,
    category: 'Revenue',
    tags: ['reimbursement'],
  },
  {
    id: 'hrc-medicare-pct',
    name: 'Medicare Payer Mix %',
    description: 'Medicare as % of payer mix',
    unit: 'percentage',
    defaultValue: 38,
    minValue: 0,
    maxValue: 100,
    step: 1,
    category: 'Payer Mix',
    tags: ['medicare'],
  },
  {
    id: 'hrc-medicaid-pct',
    name: 'Medicaid Payer Mix %',
    description: 'Medicaid as % of payer mix',
    unit: 'percentage',
    defaultValue: 15,
    minValue: 0,
    maxValue: 100,
    step: 1,
    category: 'Payer Mix',
    tags: ['medicaid'],
  },
  {
    id: 'hrc-commercial-pct',
    name: 'Commercial Payer Mix %',
    description: 'Commercial insurance as % of mix',
    unit: 'percentage',
    defaultValue: 35,
    minValue: 0,
    maxValue: 100,
    step: 1,
    category: 'Payer Mix',
    tags: ['commercial'],
  },
  {
    id: 'hrc-self-pay-pct',
    name: 'Self-Pay %',
    description: 'Self-pay as % of payer mix',
    unit: 'percentage',
    defaultValue: 8,
    minValue: 0,
    maxValue: 50,
    step: 1,
    category: 'Payer Mix',
    tags: ['self-pay'],
  },
  {
    id: 'hrc-cost-per-day',
    name: 'Cost per Patient Day',
    description: 'Operating cost per patient day',
    unit: 'currency',
    defaultValue: 2200,
    minValue: 500,
    maxValue: 10000,
    step: 50,
    category: 'Cost',
    tags: ['cost'],
  },
  {
    id: 'hrc-denial-rate',
    name: 'Claim Denial Rate',
    description: 'Percentage of claims denied',
    unit: 'percentage',
    defaultValue: 8,
    minValue: 0,
    maxValue: 30,
    step: 0.5,
    category: 'Revenue Cycle',
    tags: ['denial'],
  },
  {
    id: 'hrc-ar-days',
    name: 'Days in AR',
    description: 'Average days in accounts receivable',
    unit: 'days',
    defaultValue: 52,
    minValue: 20,
    maxValue: 120,
    step: 1,
    category: 'Revenue Cycle',
    tags: ['ar-days'],
  },
  {
    id: 'hrc-collections-rate',
    name: 'Net Collection Rate',
    description: 'Collections as % of charges',
    unit: 'percentage',
    defaultValue: 92,
    minValue: 60,
    maxValue: 100,
    step: 1,
    category: 'Revenue Cycle',
    tags: ['collections'],
  },
  {
    id: 'hrc-outpatient-visits',
    name: 'Outpatient Visits',
    description: 'Annual outpatient visits',
    unit: 'count',
    defaultValue: 280000,
    minValue: 0,
    maxValue: 5000000,
    step: 5000,
    category: 'Volume',
    tags: ['outpatient'],
  },
  {
    id: 'hrc-ed-visits',
    name: 'ED Visits',
    description: 'Annual emergency department visits',
    unit: 'count',
    defaultValue: 85000,
    minValue: 0,
    maxValue: 500000,
    step: 1000,
    category: 'Volume',
    tags: ['emergency'],
  },
];

const accounts: AccountDefinition[] = [
  // Revenue
  {
    id: 'hrc-gross-revenue',
    name: 'Gross Patient Revenue',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Total charges before adjustments',
    isCalculated: true,
  },
  {
    id: 'hrc-contractual-adj',
    name: 'Contractual Adjustments',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'debit',
    description: 'Payer contractual write-offs',
    isCalculated: true,
  },
  {
    id: 'hrc-bad-debt',
    name: 'Bad Debt & Charity',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Uncollectible accounts',
    isCalculated: true,
  },
  {
    id: 'hrc-net-revenue',
    name: 'Net Patient Revenue',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Revenue after adjustments',
    isCalculated: true,
  },
  {
    id: 'hrc-ip-revenue',
    name: 'Inpatient Revenue',
    parentId: 'hrc-net-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'IP net revenue',
    isCalculated: true,
  },
  {
    id: 'hrc-op-revenue',
    name: 'Outpatient Revenue',
    parentId: 'hrc-net-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'OP net revenue',
    isCalculated: true,
  },

  // Operating Expenses
  {
    id: 'hrc-total-expense',
    name: 'Total Operating Expense',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Total operating costs',
    isCalculated: true,
  },
  {
    id: 'hrc-salary-expense',
    name: 'Salaries & Benefits',
    parentId: 'hrc-total-expense',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Total compensation',
    isCalculated: false,
  },
  {
    id: 'hrc-supplies-expense',
    name: 'Supplies',
    parentId: 'hrc-total-expense',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Medical and surgical supplies',
    isCalculated: false,
  },
  {
    id: 'hrc-pharmacy-expense',
    name: 'Pharmacy',
    parentId: 'hrc-total-expense',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Drug costs',
    isCalculated: false,
  },
  {
    id: 'hrc-purchased-services',
    name: 'Purchased Services',
    parentId: 'hrc-total-expense',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Contracted services',
    isCalculated: false,
  },
  {
    id: 'hrc-depreciation',
    name: 'Depreciation',
    parentId: 'hrc-total-expense',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'D&A',
    isCalculated: false,
  },

  // Operating Income
  {
    id: 'hrc-operating-income',
    name: 'Operating Income',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Net revenue minus expenses',
    isCalculated: true,
  },
  {
    id: 'hrc-operating-margin',
    name: 'Operating Margin %',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Operating income / net revenue',
    isCalculated: true,
  },

  // Revenue Cycle Metrics
  {
    id: 'hrc-denied-claims',
    name: 'Denied Claims ($)',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Dollar value of denied claims',
    isCalculated: true,
  },
  {
    id: 'hrc-appeal-recovery',
    name: 'Appeal Recovery ($)',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Recovered from appeals',
    isCalculated: true,
  },
  {
    id: 'hrc-accounts-receivable',
    name: 'Accounts Receivable',
    parentId: null,
    accountType: 'asset',
    debitSide: 'debit',
    description: 'Outstanding AR',
    isCalculated: true,
  },
  {
    id: 'hrc-cost-per-patient-day',
    name: 'Cost per Patient Day',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Total cost / patient days',
    isCalculated: true,
  },
  {
    id: 'hrc-rev-per-patient-day',
    name: 'Revenue per Patient Day',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Net revenue / patient days',
    isCalculated: true,
  },
  {
    id: 'hrc-case-mix-index',
    name: 'Case Mix Index',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Average DRG weight',
    isCalculated: false,
  },
];

const cascadeRules: CascadeRuleDefinition[] = [
  {
    id: 'hrc-c-1',
    driverId: 'hrc-patient-days',
    targetAccountId: 'hrc-gross-revenue',
    cascadeType: 'direct',
    impactType: 'multiplicative',
    weight: 1,
    description: 'Patient days drive gross revenue',
  },
  {
    id: 'hrc-c-2',
    driverId: 'hrc-avg-reimbursement',
    targetAccountId: 'hrc-gross-revenue',
    cascadeType: 'direct',
    impactType: 'multiplicative',
    weight: 1,
    description: 'Reimbursement rate drives revenue',
  },
  {
    id: 'hrc-c-3',
    driverId: 'hrc-collections-rate',
    targetAccountId: 'hrc-net-revenue',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Collection rate drives net revenue',
  },
  {
    id: 'hrc-c-4',
    driverId: 'hrc-denial-rate',
    targetAccountId: 'hrc-denied-claims',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Denial rate drives denied claims',
  },
  {
    id: 'hrc-c-5',
    driverId: 'hrc-cost-per-day',
    targetAccountId: 'hrc-total-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'patient_days * x',
    description: 'Cost per day drives total expense',
  },
  {
    id: 'hrc-c-6',
    driverId: 'hrc-ar-days',
    targetAccountId: 'hrc-accounts-receivable',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'net_revenue * x / 365',
    description: 'AR days drives receivables',
  },
];

export function buildHealthcareRevenueCycleTemplate(): FPTemplate {
  return {
    id: 'tpl-healthcare-revenue-cycle',
    name: 'Healthcare Revenue Cycle',
    description:
      'Hospital revenue cycle model with payer mix analysis (Medicare/Medicaid/Commercial/Self-pay), denial management, AR days tracking, and case mix index. Pre-populated for a 400-bed community hospital with 110K patient days.',
    industry: 'Healthcare',
    category: 'revenue',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: ['healthcare', 'hospital', 'revenue-cycle', 'payer-mix', 'denial-management', 'ar-days'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
