// =============================================================================
// MANUFACTURING COGS TEMPLATE
// Standard cost model with BOM, labor routing, overhead allocation,
// yield analysis, and variance decomposition. Discrete manufacturer.
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from '../engines/TemplateLibrary';

function makePeriodRange(
  start: string,
  end: string,
  frequency: 'monthly' | 'quarterly' | 'annual'
) {
  return { start, end, frequency };
}

const drivers: DriverDefinition[] = [
  {
    id: 'mct-production-volume',
    name: 'Monthly Production Volume',
    description: 'Units produced per month',
    unit: 'count',
    defaultValue: 25000,
    minValue: 0,
    maxValue: 1000000,
    step: 500,
    category: 'Production',
    tags: ['volume'],
  },
  {
    id: 'mct-material-cost-bom',
    name: 'BOM Material Cost',
    description: 'Bill of materials cost per unit',
    unit: 'currency',
    defaultValue: 42,
    minValue: 0,
    maxValue: 10000,
    step: 1,
    category: 'Materials',
    tags: ['bom'],
  },
  {
    id: 'mct-material-usage-var',
    name: 'Material Usage Variance %',
    description: 'Actual vs standard material usage',
    unit: 'percentage',
    defaultValue: 3,
    minValue: -10,
    maxValue: 30,
    step: 0.5,
    category: 'Variance',
    tags: ['usage-variance'],
  },
  {
    id: 'mct-material-price-var',
    name: 'Material Price Variance %',
    description: 'Actual vs standard material price',
    unit: 'percentage',
    defaultValue: 2,
    minValue: -10,
    maxValue: 30,
    step: 0.5,
    category: 'Variance',
    tags: ['price-variance'],
  },
  {
    id: 'mct-labor-hours',
    name: 'Labor Hours per Unit',
    description: 'Standard labor hours per unit',
    unit: 'absolute',
    defaultValue: 0.75,
    minValue: 0,
    maxValue: 100,
    step: 0.05,
    category: 'Labor',
    tags: ['labor-hours'],
  },
  {
    id: 'mct-labor-rate',
    name: 'Labor Rate per Hour',
    description: 'Average hourly labor rate',
    unit: 'currency',
    defaultValue: 28,
    minValue: 10,
    maxValue: 200,
    step: 1,
    category: 'Labor',
    tags: ['labor-rate'],
  },
  {
    id: 'mct-labor-efficiency-var',
    name: 'Labor Efficiency Variance %',
    description: 'Actual vs standard labor hours',
    unit: 'percentage',
    defaultValue: 4,
    minValue: -10,
    maxValue: 30,
    step: 0.5,
    category: 'Variance',
    tags: ['efficiency-variance'],
  },
  {
    id: 'mct-overhead-rate',
    name: 'Overhead Rate per DLH',
    description: 'Manufacturing overhead per direct labor hour',
    unit: 'currency',
    defaultValue: 18,
    minValue: 0,
    maxValue: 200,
    step: 1,
    category: 'Overhead',
    tags: ['overhead'],
  },
  {
    id: 'mct-overhead-volume-var',
    name: 'Overhead Volume Variance %',
    description: 'Capacity utilization variance',
    unit: 'percentage',
    defaultValue: 5,
    minValue: -20,
    maxValue: 30,
    step: 1,
    category: 'Variance',
    tags: ['volume-variance'],
  },
  {
    id: 'mct-yield',
    name: 'First Pass Yield',
    description: 'Percentage of good units on first pass',
    unit: 'percentage',
    defaultValue: 96,
    minValue: 70,
    maxValue: 100,
    step: 0.5,
    category: 'Quality',
    tags: ['yield'],
  },
  {
    id: 'mct-scrap-rate',
    name: 'Scrap Rate',
    description: 'Percentage of materials scrapped',
    unit: 'percentage',
    defaultValue: 2.5,
    minValue: 0,
    maxValue: 20,
    step: 0.5,
    category: 'Quality',
    tags: ['scrap'],
  },
  {
    id: 'mct-rework-rate',
    name: 'Rework Rate',
    description: 'Percentage of units requiring rework',
    unit: 'percentage',
    defaultValue: 3,
    minValue: 0,
    maxValue: 20,
    step: 0.5,
    category: 'Quality',
    tags: ['rework'],
  },
  {
    id: 'mct-selling-price',
    name: 'Selling Price per Unit',
    description: 'Average selling price',
    unit: 'currency',
    defaultValue: 125,
    minValue: 0,
    maxValue: 50000,
    step: 5,
    category: 'Revenue',
    tags: ['price'],
  },
];

const accounts: AccountDefinition[] = [
  // Standard Cost Build-up
  {
    id: 'mct-std-cost',
    name: 'Standard Cost per Unit',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Total standard cost',
    isCalculated: true,
  },
  {
    id: 'mct-std-material',
    name: 'Standard Material Cost',
    parentId: 'mct-std-cost',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'BOM cost',
    isCalculated: true,
  },
  {
    id: 'mct-std-labor',
    name: 'Standard Labor Cost',
    parentId: 'mct-std-cost',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Labor cost per unit',
    isCalculated: true,
  },
  {
    id: 'mct-std-overhead',
    name: 'Standard Overhead',
    parentId: 'mct-std-cost',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Overhead per unit',
    isCalculated: true,
  },

  // Actual Costs
  {
    id: 'mct-actual-material',
    name: 'Actual Material Cost',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Actual material spend',
    isCalculated: true,
  },
  {
    id: 'mct-actual-labor',
    name: 'Actual Labor Cost',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Actual labor spend',
    isCalculated: true,
  },
  {
    id: 'mct-actual-overhead',
    name: 'Actual Overhead',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Actual overhead',
    isCalculated: true,
  },
  {
    id: 'mct-actual-cogs',
    name: 'Actual COGS',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Total actual COGS',
    isCalculated: true,
  },

  // Variances
  {
    id: 'mct-total-variance',
    name: 'Total Cost Variance',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Standard - Actual',
    isCalculated: true,
  },
  {
    id: 'mct-material-price-var',
    name: 'Material Price Variance',
    parentId: 'mct-total-variance',
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Price difference',
    isCalculated: true,
  },
  {
    id: 'mct-material-usage-var',
    name: 'Material Usage Variance',
    parentId: 'mct-total-variance',
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Usage difference',
    isCalculated: true,
  },
  {
    id: 'mct-labor-rate-var',
    name: 'Labor Rate Variance',
    parentId: 'mct-total-variance',
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Rate difference',
    isCalculated: false,
  },
  {
    id: 'mct-labor-efficiency-var',
    name: 'Labor Efficiency Variance',
    parentId: 'mct-total-variance',
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Hours difference',
    isCalculated: true,
  },
  {
    id: 'mct-overhead-spending-var',
    name: 'Overhead Spending Variance',
    parentId: 'mct-total-variance',
    accountType: 'memo',
    debitSide: 'debit',
    description: 'OH spending diff',
    isCalculated: false,
  },
  {
    id: 'mct-overhead-volume-var',
    name: 'Overhead Volume Variance',
    parentId: 'mct-total-variance',
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Capacity utilization',
    isCalculated: true,
  },

  // Quality
  {
    id: 'mct-good-units',
    name: 'Good Units Produced',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Units passing QC',
    isCalculated: true,
  },
  {
    id: 'mct-scrap-cost',
    name: 'Scrap Cost',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Cost of scrapped materials',
    isCalculated: true,
  },
  {
    id: 'mct-rework-cost',
    name: 'Rework Cost',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Cost of rework labor/materials',
    isCalculated: true,
  },

  // Revenue & Margin
  {
    id: 'mct-revenue',
    name: 'Net Revenue',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Total product revenue',
    isCalculated: true,
  },
  {
    id: 'mct-gross-profit',
    name: 'Gross Profit',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Revenue minus COGS',
    isCalculated: true,
  },
  {
    id: 'mct-gross-margin',
    name: 'Gross Margin %',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Gross margin percentage',
    isCalculated: true,
  },
  {
    id: 'mct-cost-per-unit',
    name: 'Actual Cost per Good Unit',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'COGS / good units',
    isCalculated: true,
  },
];

const cascadeRules: CascadeRuleDefinition[] = [
  {
    id: 'mct-c-1',
    driverId: 'mct-material-cost-bom',
    targetAccountId: 'mct-std-material',
    cascadeType: 'direct',
    impactType: 'replacement',
    weight: 1,
    description: 'BOM drives standard material',
  },
  {
    id: 'mct-c-2',
    driverId: 'mct-labor-hours',
    targetAccountId: 'mct-std-labor',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'x * labor_rate',
    description: 'Hours * rate = standard labor',
  },
  {
    id: 'mct-c-3',
    driverId: 'mct-labor-rate',
    targetAccountId: 'mct-std-labor',
    cascadeType: 'direct',
    impactType: 'multiplicative',
    weight: 1,
    description: 'Rate drives standard labor',
  },
  {
    id: 'mct-c-4',
    driverId: 'mct-overhead-rate',
    targetAccountId: 'mct-std-overhead',
    cascadeType: 'direct',
    impactType: 'multiplicative',
    weight: 1,
    description: 'OH rate drives standard overhead',
  },
  {
    id: 'mct-c-5',
    driverId: 'mct-yield',
    targetAccountId: 'mct-good-units',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'production_volume * x / 100',
    description: 'Yield drives good units',
  },
  {
    id: 'mct-c-6',
    driverId: 'mct-material-price-var',
    targetAccountId: 'mct-material-price-var',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'actual_material * x / 100',
    description: 'Price variance % drives dollar variance',
  },
  {
    id: 'mct-c-7',
    driverId: 'mct-material-usage-var',
    targetAccountId: 'mct-material-usage-var',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'actual_material * x / 100',
    description: 'Usage variance % drives dollar variance',
  },
  {
    id: 'mct-c-8',
    driverId: 'mct-selling-price',
    targetAccountId: 'mct-revenue',
    cascadeType: 'direct',
    impactType: 'multiplicative',
    weight: 1,
    description: 'Price drives revenue',
  },
  {
    id: 'mct-c-9',
    driverId: 'mct-scrap-rate',
    targetAccountId: 'mct-scrap-cost',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'actual_material * x / 100',
    description: 'Scrap rate drives scrap cost',
  },
];

export function buildManufacturingCOGSTemplate(): FPTemplate {
  return {
    id: 'tpl-manufacturing-cogs',
    name: 'Manufacturing COGS',
    description:
      'Standard cost model with BOM costing, labor routing, overhead allocation, variance decomposition (price/usage/rate/efficiency/volume), yield analysis, and scrap/rework tracking. Pre-populated for a discrete manufacturer producing 25K units/month.',
    industry: 'Manufacturing',
    category: 'cogs',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: ['manufacturing', 'cogs', 'standard-cost', 'variance', 'bom', 'yield', 'scrap'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
