// =============================================================================
// REAL ESTATE PORTFOLIO TEMPLATE
// Multi-property portfolio with NOI, cap rate valuation, debt service,
// and investor returns. Mixed-use portfolio (office + multifamily + retail).
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from '../engines/TemplateLibrary';

function makePeriodRange(
  start: string,
  end: string,
  frequency: 'monthly' | 'quarterly' | 'annual'
) {
  return { start, end, frequency };
}

const drivers: DriverDefinition[] = [
  {
    id: 'rep-office-units',
    name: 'Office Units (SF)',
    description: 'Total office square footage',
    unit: 'count',
    defaultValue: 500000,
    minValue: 0,
    maxValue: 10000000,
    step: 10000,
    category: 'Office',
    tags: ['office'],
  },
  {
    id: 'rep-office-rent-psf',
    name: 'Office Rent per SF',
    description: 'Annual office rent per square foot',
    unit: 'currency',
    defaultValue: 38,
    minValue: 10,
    maxValue: 200,
    step: 1,
    category: 'Office',
    tags: ['rent'],
  },
  {
    id: 'rep-office-occupancy',
    name: 'Office Occupancy',
    description: 'Office occupancy rate',
    unit: 'percentage',
    defaultValue: 88,
    minValue: 50,
    maxValue: 100,
    step: 1,
    category: 'Office',
    tags: ['occupancy'],
  },
  {
    id: 'rep-mf-units',
    name: 'Multifamily Units',
    description: 'Total apartment units',
    unit: 'count',
    defaultValue: 800,
    minValue: 0,
    maxValue: 50000,
    step: 10,
    category: 'Multifamily',
    tags: ['apartments'],
  },
  {
    id: 'rep-mf-rent',
    name: 'Avg Monthly Rent',
    description: 'Average monthly rent per unit',
    unit: 'currency',
    defaultValue: 1950,
    minValue: 500,
    maxValue: 10000,
    step: 50,
    category: 'Multifamily',
    tags: ['rent'],
  },
  {
    id: 'rep-mf-occupancy',
    name: 'Multifamily Occupancy',
    description: 'Multifamily occupancy rate',
    unit: 'percentage',
    defaultValue: 95,
    minValue: 70,
    maxValue: 100,
    step: 1,
    category: 'Multifamily',
    tags: ['occupancy'],
  },
  {
    id: 'rep-retail-sf',
    name: 'Retail Square Footage',
    description: 'Total retail SF',
    unit: 'count',
    defaultValue: 120000,
    minValue: 0,
    maxValue: 5000000,
    step: 5000,
    category: 'Retail',
    tags: ['retail'],
  },
  {
    id: 'rep-retail-rent-psf',
    name: 'Retail Rent per SF',
    description: 'Annual retail rent per SF',
    unit: 'currency',
    defaultValue: 28,
    minValue: 5,
    maxValue: 150,
    step: 1,
    category: 'Retail',
    tags: ['rent'],
  },
  {
    id: 'rep-opex-ratio',
    name: 'Operating Expense Ratio',
    description: 'OpEx as % of effective revenue',
    unit: 'percentage',
    defaultValue: 38,
    minValue: 20,
    maxValue: 60,
    step: 1,
    category: 'Expenses',
    tags: ['opex'],
  },
  {
    id: 'rep-cap-rate',
    name: 'Portfolio Cap Rate',
    description: 'Weighted average cap rate',
    unit: 'percentage',
    defaultValue: 5.8,
    minValue: 3,
    maxValue: 12,
    step: 0.25,
    category: 'Valuation',
    tags: ['cap-rate'],
  },
  {
    id: 'rep-rent-growth',
    name: 'Annual Rent Growth',
    description: 'Annual rent escalation',
    unit: 'percentage',
    defaultValue: 3.5,
    minValue: -5,
    maxValue: 15,
    step: 0.5,
    category: 'Growth',
    tags: ['escalation'],
  },
  {
    id: 'rep-ltv',
    name: 'Loan-to-Value',
    description: 'Portfolio LTV ratio',
    unit: 'percentage',
    defaultValue: 60,
    minValue: 0,
    maxValue: 90,
    step: 5,
    category: 'Debt',
    tags: ['leverage'],
  },
  {
    id: 'rep-interest-rate',
    name: 'Weighted Avg Interest Rate',
    description: 'Portfolio interest rate',
    unit: 'percentage',
    defaultValue: 5.75,
    minValue: 2,
    maxValue: 15,
    step: 0.25,
    category: 'Debt',
    tags: ['interest'],
  },
];

const accounts: AccountDefinition[] = [
  // Revenue
  {
    id: 'rep-gross-revenue',
    name: 'Gross Potential Revenue',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Max at 100% occupancy',
    isCalculated: true,
  },
  {
    id: 'rep-vacancy-loss',
    name: 'Vacancy Loss',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'debit',
    description: 'Revenue lost to vacancy',
    isCalculated: true,
  },
  {
    id: 'rep-effective-revenue',
    name: 'Effective Revenue',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'After vacancy',
    isCalculated: true,
  },
  {
    id: 'rep-office-revenue',
    name: 'Office Revenue',
    parentId: 'rep-effective-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Office segment',
    isCalculated: true,
  },
  {
    id: 'rep-mf-revenue',
    name: 'Multifamily Revenue',
    parentId: 'rep-effective-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'MF segment',
    isCalculated: true,
  },
  {
    id: 'rep-retail-revenue',
    name: 'Retail Revenue',
    parentId: 'rep-effective-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Retail segment',
    isCalculated: true,
  },

  // Expenses
  {
    id: 'rep-operating-expense',
    name: 'Total Operating Expense',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Property operating costs',
    isCalculated: true,
  },
  {
    id: 'rep-noi',
    name: 'Net Operating Income',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'NOI',
    isCalculated: true,
  },
  {
    id: 'rep-noi-margin',
    name: 'NOI Margin',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'NOI / Revenue',
    isCalculated: true,
  },

  // Debt Service
  {
    id: 'rep-debt-service',
    name: 'Annual Debt Service',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Principal + interest',
    isCalculated: true,
  },
  {
    id: 'rep-dscr',
    name: 'Debt Service Coverage',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'NOI / Debt Service',
    isCalculated: true,
  },

  // Valuation
  {
    id: 'rep-property-value',
    name: 'Implied Portfolio Value',
    parentId: null,
    accountType: 'asset',
    debitSide: 'debit',
    description: 'NOI / Cap Rate',
    isCalculated: true,
  },
  {
    id: 'rep-total-debt',
    name: 'Total Debt',
    parentId: null,
    accountType: 'liability',
    debitSide: 'credit',
    description: 'Outstanding mortgages',
    isCalculated: true,
  },
  {
    id: 'rep-equity',
    name: 'Total Equity',
    parentId: null,
    accountType: 'equity',
    debitSide: 'credit',
    description: 'Value minus debt',
    isCalculated: true,
  },
  {
    id: 'rep-cash-flow',
    name: 'Cash Flow After Debt',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'NOI minus debt service',
    isCalculated: true,
  },
  {
    id: 'rep-cash-on-cash',
    name: 'Cash-on-Cash Return',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'CF / equity invested',
    isCalculated: true,
  },
  {
    id: 'rep-cap-rate-actual',
    name: 'Actual Cap Rate',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'NOI / value',
    isCalculated: true,
  },
];

const cascadeRules: CascadeRuleDefinition[] = [
  {
    id: 'rep-c-1',
    driverId: 'rep-office-units',
    targetAccountId: 'rep-office-revenue',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'x * office_rent_psf * office_occupancy / 100',
    description: 'Office units drive revenue',
  },
  {
    id: 'rep-c-2',
    driverId: 'rep-mf-units',
    targetAccountId: 'rep-mf-revenue',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'x * mf_rent * 12 * mf_occupancy / 100',
    description: 'MF units drive revenue',
  },
  {
    id: 'rep-c-3',
    driverId: 'rep-retail-sf',
    targetAccountId: 'rep-retail-revenue',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'x * retail_rent_psf',
    description: 'Retail SF drives revenue',
  },
  {
    id: 'rep-c-4',
    driverId: 'rep-opex-ratio',
    targetAccountId: 'rep-operating-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'effective_revenue * x / 100',
    description: 'OER drives OpEx',
  },
  {
    id: 'rep-c-5',
    driverId: 'rep-cap-rate',
    targetAccountId: 'rep-property-value',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'noi / (x / 100)',
    description: 'Cap rate drives valuation',
  },
  {
    id: 'rep-c-6',
    driverId: 'rep-ltv',
    targetAccountId: 'rep-total-debt',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'property_value * x / 100',
    description: 'LTV drives debt',
  },
  {
    id: 'rep-c-7',
    driverId: 'rep-interest-rate',
    targetAccountId: 'rep-debt-service',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'total_debt * x / 100',
    description: 'Rate drives debt service',
  },
];

export function buildRealEstatePortfolioTemplate(): FPTemplate {
  return {
    id: 'tpl-real-estate-portfolio',
    name: 'Real Estate Portfolio',
    description:
      'Mixed-use real estate portfolio model covering office, multifamily, and retail segments with NOI analysis, cap rate valuation, DSCR, LTV, and investor return metrics. Pre-populated for a $500M+ portfolio.',
    industry: 'Real Estate',
    category: 'cashflow',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: ['real-estate', 'noi', 'cap-rate', 'dscr', 'mixed-use', 'portfolio', 'valuation'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
