// =============================================================================
// RETAIL STORE PERFORMANCE TEMPLATE
// Multi-unit retail with same-store sales, traffic/conversion funnel,
// inventory management, and store-level P&L. 150-store specialty retailer.
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from '../engines/TemplateLibrary';

function makePeriodRange(
  start: string,
  end: string,
  frequency: 'monthly' | 'quarterly' | 'annual'
) {
  return { start, end, frequency };
}

const drivers: DriverDefinition[] = [
  {
    id: 'rsp-store-count',
    name: 'Store Count',
    description: 'Number of operating stores',
    unit: 'count',
    defaultValue: 150,
    minValue: 0,
    maxValue: 10000,
    step: 1,
    category: 'Operations',
    tags: ['stores'],
  },
  {
    id: 'rsp-avg-sqft',
    name: 'Average Store Size (sqft)',
    description: 'Average square footage per store',
    unit: 'count',
    defaultValue: 3200,
    minValue: 500,
    maxValue: 50000,
    step: 100,
    category: 'Operations',
    tags: ['sqft'],
  },
  {
    id: 'rsp-traffic-per-store',
    name: 'Monthly Traffic per Store',
    description: 'Average monthly customer visits',
    unit: 'count',
    defaultValue: 8500,
    minValue: 0,
    maxValue: 200000,
    step: 100,
    category: 'Traffic',
    tags: ['footfall'],
  },
  {
    id: 'rsp-conversion-rate',
    name: 'Conversion Rate',
    description: 'Percentage of visitors who buy',
    unit: 'percentage',
    defaultValue: 24,
    minValue: 5,
    maxValue: 80,
    step: 1,
    category: 'Sales',
    tags: ['conversion'],
  },
  {
    id: 'rsp-avg-ticket',
    name: 'Average Ticket Size',
    description: 'Average transaction value',
    unit: 'currency',
    defaultValue: 72,
    minValue: 5,
    maxValue: 5000,
    step: 1,
    category: 'Revenue',
    tags: ['atv'],
  },
  {
    id: 'rsp-units-per-transaction',
    name: 'Units per Transaction',
    description: 'Average items per transaction',
    unit: 'ratio',
    defaultValue: 2.4,
    minValue: 1,
    maxValue: 20,
    step: 0.1,
    category: 'Sales',
    tags: ['upt'],
  },
  {
    id: 'rsp-gross-margin',
    name: 'Gross Margin',
    description: 'Merchandise gross margin',
    unit: 'percentage',
    defaultValue: 52,
    minValue: 20,
    maxValue: 80,
    step: 1,
    category: 'Margin',
    tags: ['margin'],
  },
  {
    id: 'rsp-shrinkage-rate',
    name: 'Shrinkage Rate',
    description: 'Inventory shrinkage as % of revenue',
    unit: 'percentage',
    defaultValue: 1.8,
    minValue: 0,
    maxValue: 10,
    step: 0.1,
    category: 'Loss Prevention',
    tags: ['shrinkage'],
  },
  {
    id: 'rsp-rent-psf',
    name: 'Rent per Square Foot',
    description: 'Annual rent cost per sqft',
    unit: 'currency',
    defaultValue: 28,
    minValue: 5,
    maxValue: 200,
    step: 1,
    category: 'Occupancy',
    tags: ['rent'],
  },
  {
    id: 'rsp-labor-pct',
    name: 'Store Labor % of Revenue',
    description: 'Store payroll as % of store revenue',
    unit: 'percentage',
    defaultValue: 14,
    minValue: 5,
    maxValue: 30,
    step: 0.5,
    category: 'Labor',
    tags: ['payroll'],
  },
  {
    id: 'rsp-new-stores',
    name: 'New Store Openings',
    description: 'Planned new store openings',
    unit: 'count',
    defaultValue: 12,
    minValue: 0,
    maxValue: 200,
    step: 1,
    category: 'Growth',
    tags: ['expansion'],
  },
  {
    id: 'rsp-closures',
    name: 'Store Closures',
    description: 'Planned store closures',
    unit: 'count',
    defaultValue: 3,
    minValue: 0,
    maxValue: 100,
    step: 1,
    category: 'Growth',
    tags: ['closure'],
  },
  {
    id: 'rsp-e-commerce-pct',
    name: 'E-Commerce % of Revenue',
    description: 'Online sales as % of total',
    unit: 'percentage',
    defaultValue: 18,
    minValue: 0,
    maxValue: 100,
    step: 1,
    category: 'Channel',
    tags: ['ecommerce'],
  },
];

const accounts: AccountDefinition[] = [
  // Revenue
  {
    id: 'rsp-total-revenue',
    name: 'Total Net Revenue',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Total retail sales',
    isCalculated: true,
  },
  {
    id: 'rsp-store-revenue',
    name: 'Store Revenue',
    parentId: 'rsp-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'In-store sales',
    isCalculated: true,
  },
  {
    id: 'rsp-ecommerce-revenue',
    name: 'E-Commerce Revenue',
    parentId: 'rsp-total-revenue',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Online sales',
    isCalculated: true,
  },
  {
    id: 'rsp-transactions',
    name: 'Total Transactions',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Total transaction count',
    isCalculated: true,
  },
  {
    id: 'rsp-units-sold',
    name: 'Units Sold',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Total units sold',
    isCalculated: true,
  },

  // COGS
  {
    id: 'rsp-cogs',
    name: 'Cost of Goods Sold',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Product cost',
    isCalculated: true,
  },
  {
    id: 'rsp-gross-profit',
    name: 'Gross Profit',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Revenue minus COGS',
    isCalculated: true,
  },
  {
    id: 'rsp-shrinkage',
    name: 'Shrinkage Expense',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Inventory loss',
    isCalculated: true,
  },

  // Store Operating Expenses
  {
    id: 'rsp-store-opex',
    name: 'Store Operating Expenses',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Total store-level expenses',
    isCalculated: true,
  },
  {
    id: 'rsp-store-payroll',
    name: 'Store Payroll',
    parentId: 'rsp-store-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Store labor',
    isCalculated: true,
  },
  {
    id: 'rsp-occupancy-cost',
    name: 'Occupancy Cost',
    parentId: 'rsp-store-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Rent + CAM + utilities',
    isCalculated: true,
  },
  {
    id: 'rsp-store-supplies',
    name: 'Store Supplies',
    parentId: 'rsp-store-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Packaging, supplies',
    isCalculated: false,
  },
  {
    id: 'rsp-marketing-alloc',
    name: 'Marketing Allocation',
    parentId: 'rsp-store-opex',
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Local marketing',
    isCalculated: false,
  },

  // Store Profitability
  {
    id: 'rsp-store-profit',
    name: 'Store-Level Contribution',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Gross profit minus store OpEx',
    isCalculated: true,
  },
  {
    id: 'rsp-store-margin',
    name: 'Store Contribution Margin %',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Store profit / revenue',
    isCalculated: true,
  },

  // Corporate Overhead
  {
    id: 'rsp-corporate-expense',
    name: 'Corporate Overhead',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'HQ expenses',
    isCalculated: false,
  },
  {
    id: 'rsp-operating-income',
    name: 'Operating Income',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Store profit minus corporate',
    isCalculated: true,
  },

  // Key Metrics
  {
    id: 'rsp-sales-per-sqft',
    name: 'Sales per Square Foot',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Revenue / total sqft',
    isCalculated: true,
  },
  {
    id: 'rsp-sales-per-store',
    name: 'Average Sales per Store',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Revenue / store count',
    isCalculated: true,
  },
  {
    id: 'rsp-comp-sales-growth',
    name: 'Comparable Store Sales Growth',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Same-store sales growth %',
    isCalculated: true,
  },
  {
    id: 'rsp-inventory-turns',
    name: 'Inventory Turns',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'COGS / average inventory',
    isCalculated: true,
  },
];

const cascadeRules: CascadeRuleDefinition[] = [
  {
    id: 'rsp-c-1',
    driverId: 'rsp-traffic-per-store',
    targetAccountId: 'rsp-transactions',
    cascadeType: 'direct',
    impactType: 'multiplicative',
    weight: 1,
    description: 'Traffic drives transactions',
  },
  {
    id: 'rsp-c-2',
    driverId: 'rsp-conversion-rate',
    targetAccountId: 'rsp-transactions',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'x / 100',
    description: 'Conversion drives transactions',
  },
  {
    id: 'rsp-c-3',
    driverId: 'rsp-avg-ticket',
    targetAccountId: 'rsp-store-revenue',
    cascadeType: 'direct',
    impactType: 'multiplicative',
    weight: 1,
    description: 'Ticket size drives revenue',
  },
  {
    id: 'rsp-c-4',
    driverId: 'rsp-store-count',
    targetAccountId: 'rsp-store-revenue',
    cascadeType: 'direct',
    impactType: 'multiplicative',
    weight: 1,
    description: 'Store count drives revenue',
  },
  {
    id: 'rsp-c-5',
    driverId: 'rsp-gross-margin',
    targetAccountId: 'rsp-cogs',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * (100 - x) / 100',
    description: 'Margin drives COGS',
  },
  {
    id: 'rsp-c-6',
    driverId: 'rsp-shrinkage-rate',
    targetAccountId: 'rsp-shrinkage',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Shrinkage rate drives loss',
  },
  {
    id: 'rsp-c-7',
    driverId: 'rsp-rent-psf',
    targetAccountId: 'rsp-occupancy-cost',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'rsp_store_count * rsp_avg_sqft * x',
    description: 'Rent PSF drives occupancy',
  },
  {
    id: 'rsp-c-8',
    driverId: 'rsp-labor-pct',
    targetAccountId: 'rsp-store-payroll',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Labor % drives payroll',
  },
];

export function buildRetailStorePerformanceTemplate(): FPTemplate {
  return {
    id: 'tpl-retail-store-performance',
    name: 'Retail Store Performance',
    description:
      'Multi-unit retail model with traffic/conversion funnel, same-store sales, gross margin analysis, shrinkage tracking, store-level P&L, and omnichannel (e-commerce) split. Pre-populated for a 150-store specialty retailer.',
    industry: 'Retail',
    category: 'revenue',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: [
      'retail',
      'store-performance',
      'traffic',
      'conversion',
      'same-store-sales',
      'omnichannel',
    ],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
