// =============================================================================
// TECHNOLOGY / SaaS COMPANY TEMPLATE
// Full SaaS company model with ARR waterfall, cohort analysis, unit economics,
// Rule of 40, and path-to-profitability. Growth-stage company ($30M ARR).
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from '../engines/TemplateLibrary';

function makePeriodRange(
  start: string,
  end: string,
  frequency: 'monthly' | 'quarterly' | 'annual'
) {
  return { start, end, frequency };
}

const drivers: DriverDefinition[] = [
  {
    id: 'tsa-arr-begin',
    name: 'Beginning ARR',
    description: 'ARR at start of period',
    unit: 'currency',
    defaultValue: 30000000,
    minValue: 0,
    maxValue: 10000000000,
    step: 1000000,
    category: 'ARR',
    tags: ['arr'],
  },
  {
    id: 'tsa-new-arr-rate',
    name: 'New ARR Growth Rate',
    description: 'Net new ARR as % of beginning ARR',
    unit: 'percentage',
    defaultValue: 35,
    minValue: -20,
    maxValue: 200,
    step: 5,
    category: 'Growth',
    tags: ['new-arr'],
  },
  {
    id: 'tsa-gross-churn',
    name: 'Gross Dollar Churn',
    description: 'Lost ARR as % of beginning ARR',
    unit: 'percentage',
    defaultValue: 8,
    minValue: 0,
    maxValue: 50,
    step: 1,
    category: 'Retention',
    tags: ['churn'],
  },
  {
    id: 'tsa-expansion-rate',
    name: 'Net Expansion Rate',
    description: 'Expansion ARR as % of beginning ARR',
    unit: 'percentage',
    defaultValue: 15,
    minValue: 0,
    maxValue: 100,
    step: 1,
    category: 'Retention',
    tags: ['expansion', 'nrr'],
  },
  {
    id: 'tsa-gross-margin',
    name: 'Gross Margin',
    description: 'SaaS gross margin',
    unit: 'percentage',
    defaultValue: 78,
    minValue: 40,
    maxValue: 95,
    step: 1,
    category: 'Profitability',
    tags: ['margin'],
  },
  {
    id: 'tsa-sm-pct',
    name: 'S&M % of Revenue',
    description: 'Sales & marketing as % of revenue',
    unit: 'percentage',
    defaultValue: 45,
    minValue: 10,
    maxValue: 80,
    step: 5,
    category: 'OpEx',
    tags: ['sales', 'marketing'],
  },
  {
    id: 'tsa-rd-pct',
    name: 'R&D % of Revenue',
    description: 'R&D as % of revenue',
    unit: 'percentage',
    defaultValue: 25,
    minValue: 5,
    maxValue: 50,
    step: 1,
    category: 'OpEx',
    tags: ['engineering'],
  },
  {
    id: 'tsa-ga-pct',
    name: 'G&A % of Revenue',
    description: 'G&A as % of revenue',
    unit: 'percentage',
    defaultValue: 12,
    minValue: 3,
    maxValue: 30,
    step: 1,
    category: 'OpEx',
    tags: ['admin'],
  },
  {
    id: 'tsa-cac',
    name: 'Customer Acquisition Cost',
    description: 'Blended CAC',
    unit: 'currency',
    defaultValue: 18000,
    minValue: 100,
    maxValue: 500000,
    step: 1000,
    category: 'Unit Economics',
    tags: ['cac'],
  },
  {
    id: 'tsa-arpu',
    name: 'Average ARR per Customer',
    description: 'Average annual revenue per customer',
    unit: 'currency',
    defaultValue: 24000,
    minValue: 100,
    maxValue: 1000000,
    step: 1000,
    category: 'Unit Economics',
    tags: ['arpu'],
  },
  {
    id: 'tsa-customer-count-begin',
    name: 'Beginning Customer Count',
    description: 'Customers at start of period',
    unit: 'count',
    defaultValue: 1250,
    minValue: 0,
    maxValue: 1000000,
    step: 50,
    category: 'Customers',
    tags: ['customers'],
  },
  {
    id: 'tsa-net-new-customers',
    name: 'Net New Customers / Month',
    description: 'Monthly net customer additions',
    unit: 'count',
    defaultValue: 45,
    minValue: -100,
    maxValue: 10000,
    step: 5,
    category: 'Customers',
    tags: ['acquisition'],
  },
  {
    id: 'tsa-months-to-recover-cac',
    name: 'Months to Recover CAC',
    description: 'Payback period in months',
    unit: 'months',
    defaultValue: 14,
    minValue: 1,
    maxValue: 60,
    step: 1,
    category: 'Unit Economics',
    tags: ['payback'],
  },
];

const accounts: AccountDefinition[] = [
  // ARR Waterfall
  {
    id: 'tsa-arr',
    name: 'Ending ARR',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Annual recurring revenue',
    isCalculated: true,
  },
  {
    id: 'tsa-beginning-arr',
    name: 'Beginning ARR',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'ARR at period start',
    isCalculated: true,
  },
  {
    id: 'tsa-new-arr',
    name: 'New ARR',
    parentId: 'tsa-arr',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'ARR from new customers',
    isCalculated: true,
  },
  {
    id: 'tsa-expansion-arr',
    name: 'Expansion ARR',
    parentId: 'tsa-arr',
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'ARR from upsells',
    isCalculated: true,
  },
  {
    id: 'tsa-churned-arr',
    name: 'Churned ARR',
    parentId: 'tsa-arr',
    accountType: 'revenue',
    debitSide: 'debit',
    description: 'Lost ARR',
    isCalculated: true,
  },
  {
    id: 'tsa-net-new-arr',
    name: 'Net New ARR',
    parentId: 'tsa-arr',
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Net change in ARR',
    isCalculated: true,
  },

  // Revenue
  {
    id: 'tsa-mrr',
    name: 'Monthly Recurring Revenue',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'MRR = ARR / 12',
    isCalculated: true,
  },
  {
    id: 'tsa-total-revenue',
    name: 'Total Revenue',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'MRR + services + other',
    isCalculated: true,
  },

  // P&L
  {
    id: 'tsa-cogs',
    name: 'Cost of Revenue',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Hosting, support, CS',
    isCalculated: true,
  },
  {
    id: 'tsa-gross-profit',
    name: 'Gross Profit',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Revenue minus COGS',
    isCalculated: true,
  },
  {
    id: 'tsa-sm-expense',
    name: 'Sales & Marketing',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'S&M spend',
    isCalculated: true,
  },
  {
    id: 'tsa-rd-expense',
    name: 'R&D Expense',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Engineering',
    isCalculated: true,
  },
  {
    id: 'tsa-ga-expense',
    name: 'G&A Expense',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Admin',
    isCalculated: true,
  },
  {
    id: 'tsa-total-opex',
    name: 'Total Operating Expense',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Total OpEx',
    isCalculated: true,
  },
  {
    id: 'tsa-ebitda',
    name: 'EBITDA',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Operating income',
    isCalculated: true,
  },
  {
    id: 'tsa-fcf',
    name: 'Free Cash Flow',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'FCF proxy',
    isCalculated: true,
  },

  // Unit Economics
  {
    id: 'tsa-ltv',
    name: 'Customer LTV',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'ARPU * Gross Margin / Churn',
    isCalculated: true,
  },
  {
    id: 'tsa-ltv-cac',
    name: 'LTV/CAC Ratio',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Unit economics ratio',
    isCalculated: true,
  },
  {
    id: 'tsa-nrr',
    name: 'Net Revenue Retention',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'NRR %',
    isCalculated: true,
  },
  {
    id: 'tsa-rule-of-40',
    name: 'Rule of 40 Score',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Growth % + FCF Margin %',
    isCalculated: true,
  },
  {
    id: 'tsa-burn-multiple',
    name: 'Burn Multiple',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Net burn / Net new ARR',
    isCalculated: true,
  },
  {
    id: 'tsa-magic-number',
    name: 'Magic Number',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Net new ARR / S&M spend (prior Q)',
    isCalculated: true,
  },
];

const cascadeRules: CascadeRuleDefinition[] = [
  {
    id: 'tsa-c-1',
    driverId: 'tsa-new-arr-rate',
    targetAccountId: 'tsa-new-arr',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'beginning_arr * x / 100',
    description: 'New ARR rate drives new ARR',
  },
  {
    id: 'tsa-c-2',
    driverId: 'tsa-gross-churn',
    targetAccountId: 'tsa-churned-arr',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'beginning_arr * x / 100',
    description: 'Churn drives lost ARR',
  },
  {
    id: 'tsa-c-3',
    driverId: 'tsa-expansion-rate',
    targetAccountId: 'tsa-expansion-arr',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'beginning_arr * x / 100',
    description: 'Expansion rate drives expansion ARR',
  },
  {
    id: 'tsa-c-4',
    driverId: 'tsa-gross-margin',
    targetAccountId: 'tsa-cogs',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * (100 - x) / 100',
    description: 'Margin drives COGS',
  },
  {
    id: 'tsa-c-5',
    driverId: 'tsa-sm-pct',
    targetAccountId: 'tsa-sm-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'S&M % drives S&M expense',
  },
  {
    id: 'tsa-c-6',
    driverId: 'tsa-rd-pct',
    targetAccountId: 'tsa-rd-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'R&D % drives R&D expense',
  },
  {
    id: 'tsa-c-7',
    driverId: 'tsa-ga-pct',
    targetAccountId: 'tsa-ga-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'G&A % drives G&A expense',
  },
];

export function buildTechSaaSCompanyTemplate(): FPTemplate {
  return {
    id: 'tpl-tech-saas-company',
    name: 'Technology / SaaS Company',
    description:
      'Full SaaS company model with ARR waterfall, cohort-based growth, unit economics (LTV/CAC, NRR, Rule of 40, Magic Number, Burn Multiple), and path-to-profitability analysis. Pre-populated for a $30M ARR growth-stage company.',
    industry: 'SaaS',
    category: 'revenue',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: ['saas', 'arr', 'unit-economics', 'ltv', 'cac', 'nrr', 'rule-of-40', 'magic-number'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
