// =============================================================================
// THREE-STATEMENT FINANCIAL MODEL
// Integrated Income Statement, Balance Sheet, and Cash Flow Statement
// with circular references resolved via iterative calculation.
// Mid-cap industrial company ($200M revenue).
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from '../engines/TemplateLibrary';

function makePeriodRange(
  start: string,
  end: string,
  frequency: 'monthly' | 'quarterly' | 'annual'
) {
  return { start, end, frequency };
}

const drivers: DriverDefinition[] = [
  {
    id: '3s-revenue-growth',
    name: 'Revenue Growth',
    description: 'YoY revenue growth rate',
    unit: 'percentage',
    defaultValue: 8,
    minValue: -20,
    maxValue: 50,
    step: 1,
    category: 'Revenue',
    tags: ['growth'],
  },
  {
    id: '3s-gross-margin',
    name: 'Gross Margin',
    description: 'Target gross margin',
    unit: 'percentage',
    defaultValue: 45,
    minValue: 15,
    maxValue: 80,
    step: 1,
    category: 'Profitability',
    tags: ['margin'],
  },
  {
    id: '3s-opex-pct',
    name: 'OpEx as % of Revenue',
    description: 'Operating expenses percentage',
    unit: 'percentage',
    defaultValue: 28,
    minValue: 10,
    maxValue: 60,
    step: 1,
    category: 'OpEx',
    tags: ['opex'],
  },
  {
    id: '3s-tax-rate',
    name: 'Effective Tax Rate',
    description: 'Corporate tax rate',
    unit: 'percentage',
    defaultValue: 25,
    minValue: 0,
    maxValue: 50,
    step: 1,
    category: 'Tax',
    tags: ['tax'],
  },
  {
    id: '3s-dso',
    name: 'Days Sales Outstanding',
    description: 'Average collection period',
    unit: 'days',
    defaultValue: 45,
    minValue: 0,
    maxValue: 180,
    step: 1,
    category: 'Working Capital',
    tags: ['receivables'],
  },
  {
    id: '3s-dio',
    name: 'Days Inventory Outstanding',
    description: 'Average inventory days',
    unit: 'days',
    defaultValue: 60,
    minValue: 0,
    maxValue: 365,
    step: 1,
    category: 'Working Capital',
    tags: ['inventory'],
  },
  {
    id: '3s-dpo',
    name: 'Days Payable Outstanding',
    description: 'Average payment period',
    unit: 'days',
    defaultValue: 35,
    minValue: 0,
    maxValue: 180,
    step: 1,
    category: 'Working Capital',
    tags: ['payables'],
  },
  {
    id: '3s-capex-pct',
    name: 'CapEx as % of Revenue',
    description: 'Capital expenditure ratio',
    unit: 'percentage',
    defaultValue: 5,
    minValue: 0,
    maxValue: 30,
    step: 0.5,
    category: 'CapEx',
    tags: ['capex'],
  },
  {
    id: '3s-debt-to-equity',
    name: 'Debt-to-Equity Ratio',
    description: 'Target leverage ratio',
    unit: 'ratio',
    defaultValue: 0.8,
    minValue: 0,
    maxValue: 5,
    step: 0.1,
    category: 'Capital Structure',
    tags: ['leverage'],
  },
  {
    id: '3s-interest-rate',
    name: 'Cost of Debt',
    description: 'Weighted average interest rate',
    unit: 'percentage',
    defaultValue: 5.5,
    minValue: 0,
    maxValue: 20,
    step: 0.25,
    category: 'Capital Structure',
    tags: ['interest'],
  },
  {
    id: '3s-dividend-payout',
    name: 'Dividend Payout Ratio',
    description: 'Dividends as % of net income',
    unit: 'percentage',
    defaultValue: 30,
    minValue: 0,
    maxValue: 100,
    step: 5,
    category: 'Shareholder Returns',
    tags: ['dividend'],
  },
  {
    id: '3s-depreciation-rate',
    name: 'Depreciation Rate',
    description: 'Annual depreciation as % of PP&E',
    unit: 'percentage',
    defaultValue: 10,
    minValue: 2,
    maxValue: 30,
    step: 1,
    category: 'D&A',
    tags: ['depreciation'],
  },
];

const accounts: AccountDefinition[] = [
  // Income Statement
  {
    id: '3s-revenue',
    name: 'Net Revenue',
    parentId: null,
    accountType: 'revenue',
    debitSide: 'credit',
    description: 'Total net revenue',
    isCalculated: true,
  },
  {
    id: '3s-cogs',
    name: 'Cost of Goods Sold',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Total COGS',
    isCalculated: true,
  },
  {
    id: '3s-gross-profit',
    name: 'Gross Profit',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Revenue minus COGS',
    isCalculated: true,
  },
  {
    id: '3s-sga',
    name: 'SG&A Expense',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Selling, general & admin',
    isCalculated: true,
  },
  {
    id: '3s-rd',
    name: 'R&D Expense',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Research & development',
    isCalculated: false,
  },
  {
    id: '3s-da',
    name: 'Depreciation & Amortization',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'D&A',
    isCalculated: true,
  },
  {
    id: '3s-operating-income',
    name: 'Operating Income (EBIT)',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'EBIT',
    isCalculated: true,
  },
  {
    id: '3s-interest-expense',
    name: 'Interest Expense',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Debt interest',
    isCalculated: true,
  },
  {
    id: '3s-pre-tax-income',
    name: 'Pre-Tax Income',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'EBT',
    isCalculated: true,
  },
  {
    id: '3s-tax-expense',
    name: 'Income Tax Expense',
    parentId: null,
    accountType: 'expense',
    debitSide: 'debit',
    description: 'Corporate tax',
    isCalculated: true,
  },
  {
    id: '3s-net-income',
    name: 'Net Income',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Bottom line',
    isCalculated: true,
  },

  // Balance Sheet - Assets
  {
    id: '3s-cash',
    name: 'Cash & Equivalents',
    parentId: null,
    accountType: 'asset',
    debitSide: 'debit',
    description: 'Cash balance',
    isCalculated: true,
  },
  {
    id: '3s-accounts-receivable',
    name: 'Accounts Receivable',
    parentId: null,
    accountType: 'asset',
    debitSide: 'debit',
    description: 'Trade receivables',
    isCalculated: true,
  },
  {
    id: '3s-inventory',
    name: 'Inventory',
    parentId: null,
    accountType: 'asset',
    debitSide: 'debit',
    description: 'Inventory on hand',
    isCalculated: true,
  },
  {
    id: '3s-total-current-assets',
    name: 'Total Current Assets',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Current assets sum',
    isCalculated: true,
  },
  {
    id: '3s-ppe-net',
    name: 'PP&E, Net',
    parentId: null,
    accountType: 'asset',
    debitSide: 'debit',
    description: 'Property, plant & equipment net of depreciation',
    isCalculated: true,
  },
  {
    id: '3s-total-assets',
    name: 'Total Assets',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Total assets',
    isCalculated: true,
  },

  // Balance Sheet - Liabilities
  {
    id: '3s-accounts-payable',
    name: 'Accounts Payable',
    parentId: null,
    accountType: 'liability',
    debitSide: 'credit',
    description: 'Trade payables',
    isCalculated: true,
  },
  {
    id: '3s-total-current-liabilities',
    name: 'Total Current Liabilities',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Current liabilities sum',
    isCalculated: true,
  },
  {
    id: '3s-long-term-debt',
    name: 'Long-Term Debt',
    parentId: null,
    accountType: 'liability',
    debitSide: 'credit',
    description: 'Outstanding debt',
    isCalculated: true,
  },
  {
    id: '3s-total-liabilities',
    name: 'Total Liabilities',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Total liabilities',
    isCalculated: true,
  },

  // Balance Sheet - Equity
  {
    id: '3s-total-equity',
    name: 'Total Shareholders Equity',
    parentId: null,
    accountType: 'equity',
    debitSide: 'credit',
    description: 'Total equity',
    isCalculated: true,
  },
  {
    id: '3s-retained-earnings',
    name: 'Retained Earnings',
    parentId: null,
    accountType: 'equity',
    debitSide: 'credit',
    description: 'Cumulative retained earnings',
    isCalculated: true,
  },

  // Cash Flow Statement
  {
    id: '3s-cfo',
    name: 'Cash from Operations',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Operating cash flow',
    isCalculated: true,
  },
  {
    id: '3s-cfi',
    name: 'Cash from Investing',
    parentId: null,
    accountType: 'memo',
    debitSide: 'debit',
    description: 'Investing cash flow',
    isCalculated: true,
  },
  {
    id: '3s-cff',
    name: 'Cash from Financing',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Financing cash flow',
    isCalculated: true,
  },
  {
    id: '3s-net-cash-change',
    name: 'Net Change in Cash',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'Net cash change',
    isCalculated: true,
  },

  // Key Metrics
  {
    id: '3s-fcf',
    name: 'Free Cash Flow',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'FCF = CFO - CapEx',
    isCalculated: true,
  },
  {
    id: '3s-roe',
    name: 'Return on Equity',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'ROE',
    isCalculated: true,
  },
  {
    id: '3s-roa',
    name: 'Return on Assets',
    parentId: null,
    accountType: 'memo',
    debitSide: 'credit',
    description: 'ROA',
    isCalculated: true,
  },
];

const cascadeRules: CascadeRuleDefinition[] = [
  {
    id: '3s-c-1',
    driverId: '3s-revenue-growth',
    targetAccountId: '3s-revenue',
    cascadeType: 'formula',
    impactType: 'multiplicative',
    weight: 1,
    formula: 'prev * (1 + x / 100)',
    description: 'Growth drives revenue',
  },
  {
    id: '3s-c-2',
    driverId: '3s-gross-margin',
    targetAccountId: '3s-cogs',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * (100 - x) / 100',
    description: 'Margin drives COGS',
  },
  {
    id: '3s-c-3',
    driverId: '3s-opex-pct',
    targetAccountId: '3s-sga',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'OpEx % drives SG&A',
  },
  {
    id: '3s-c-4',
    driverId: '3s-tax-rate',
    targetAccountId: '3s-tax-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Tax rate drives tax expense',
  },
  {
    id: '3s-c-5',
    driverId: '3s-dso',
    targetAccountId: '3s-accounts-receivable',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 365',
    description: 'DSO drives receivables',
  },
  {
    id: '3s-c-6',
    driverId: '3s-dio',
    targetAccountId: '3s-inventory',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 365',
    description: 'DIO drives inventory',
  },
  {
    id: '3s-c-7',
    driverId: '3s-dpo',
    targetAccountId: '3s-accounts-payable',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 365',
    description: 'DPO drives payables',
  },
  {
    id: '3s-c-8',
    driverId: '3s-capex-pct',
    targetAccountId: '3s-cfi',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'CapEx % drives investing outflow',
  },
  {
    id: '3s-c-9',
    driverId: '3s-interest-rate',
    targetAccountId: '3s-interest-expense',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Rate drives interest expense',
  },
  {
    id: '3s-c-10',
    driverId: '3s-depreciation-rate',
    targetAccountId: '3s-da',
    cascadeType: 'formula',
    impactType: 'replacement',
    weight: 1,
    formula: 'current * x / 100',
    description: 'Rate drives depreciation',
  },
];

export function buildThreeStatementModel(): FPTemplate {
  return {
    id: 'tpl-three-statement',
    name: '3-Statement Financial Model',
    description:
      'Integrated Income Statement, Balance Sheet, and Cash Flow model with working capital drivers, debt scheduling, and circular reference resolution. Pre-populated for a $200M industrial company.',
    industry: 'Manufacturing',
    category: 'balance-sheet',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'quarterly'),
    tags: ['3-statement', 'income-statement', 'balance-sheet', 'cash-flow', 'integrated', 'dcf'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
