import type { FormulaFunction } from './formulaData';

export const FINANCIAL_FUNCTIONS: FormulaFunction[] = [
  {
    name: 'IRR',
    category: 'Financial',
    syntax: 'IRR(values, [guess])',
    description: 'Internal rate of return',
    params: ['values', 'guess'],
  },
  {
    name: 'XIRR',
    category: 'Financial',
    syntax: 'XIRR(values, dates, [guess])',
    description: 'IRR with specific dates',
    params: ['values', 'dates', 'guess'],
  },
  {
    name: 'NPV',
    category: 'Financial',
    syntax: 'NPV(rate, value1, [value2], ...)',
    description: 'Net present value',
    params: ['rate', 'value1', 'value2'],
  },
  {
    name: 'XNPV',
    category: 'Financial',
    syntax: 'XNPV(rate, values, dates)',
    description: 'NPV with specific dates',
    params: ['rate', 'values', 'dates'],
  },
  {
    name: 'PV',
    category: 'Financial',
    syntax: 'PV(rate, nper, pmt, [fv], [type])',
    description: 'Present value',
    params: ['rate', 'nper', 'pmt', 'fv', 'type'],
  },
  {
    name: 'FV',
    category: 'Financial',
    syntax: 'FV(rate, nper, pmt, [pv], [type])',
    description: 'Future value',
    params: ['rate', 'nper', 'pmt', 'pv', 'type'],
  },
  {
    name: 'PMT',
    category: 'Financial',
    syntax: 'PMT(rate, nper, pv, [fv], [type])',
    description: 'Payment per period',
    params: ['rate', 'nper', 'pv', 'fv', 'type'],
  },
  {
    name: 'IPMT',
    category: 'Financial',
    syntax: 'IPMT(rate, per, nper, pv, [fv], [type])',
    description: 'Interest payment',
    params: ['rate', 'per', 'nper', 'pv', 'fv', 'type'],
  },
  {
    name: 'PPMT',
    category: 'Financial',
    syntax: 'PPMT(rate, per, nper, pv, [fv], [type])',
    description: 'Principal payment',
    params: ['rate', 'per', 'nper', 'pv', 'fv', 'type'],
  },
  {
    name: 'NPER',
    category: 'Financial',
    syntax: 'NPER(rate, pmt, pv, [fv], [type])',
    description: 'Number of periods',
    params: ['rate', 'pmt', 'pv', 'fv', 'type'],
  },
  {
    name: 'RATE',
    category: 'Financial',
    syntax: 'RATE(nper, pmt, pv, [fv], [type], [guess])',
    description: 'Interest rate per period',
    params: ['nper', 'pmt', 'pv', 'fv', 'type', 'guess'],
  },
  {
    name: 'CAGR',
    category: 'Financial',
    syntax: 'CAGR(begin_value, end_value, periods)',
    description: 'Compound annual growth rate',
    params: ['begin_value', 'end_value', 'periods'],
  },
  {
    name: 'SLN',
    category: 'Financial',
    syntax: 'SLN(cost, salvage, life)',
    description: 'Straight-line depreciation',
    params: ['cost', 'salvage', 'life'],
  },
  {
    name: 'DB',
    category: 'Financial',
    syntax: 'DB(cost, salvage, life, period, [month])',
    description: 'Declining balance depreciation',
    params: ['cost', 'salvage', 'life', 'period', 'month'],
  },
  {
    name: 'SYD',
    category: 'Financial',
    syntax: 'SYD(cost, salvage, life, per)',
    description: 'Sum-of-years depreciation',
    params: ['cost', 'salvage', 'life', 'per'],
  },
  {
    name: 'DDB',
    category: 'Financial',
    syntax: 'DDB(cost, salvage, life, period, [factor])',
    description: 'Double declining depreciation',
    params: ['cost', 'salvage', 'life', 'period', 'factor'],
  },
];

export const LOGICAL_FUNCTIONS: FormulaFunction[] = [
  {
    name: 'IF',
    category: 'Logical',
    syntax: 'IF(logical_test, value_if_true, value_if_false)',
    description: 'Conditional value',
    params: ['logical_test', 'value_if_true', 'value_if_false'],
  },
  {
    name: 'IFS',
    category: 'Logical',
    syntax: 'IFS(test1, val1, test2, val2, ...)',
    description: 'Multiple conditions',
    params: ['test1', 'val1', 'test2', 'val2'],
  },
  {
    name: 'AND',
    category: 'Logical',
    syntax: 'AND(logical1, [logical2], ...)',
    description: 'All conditions true',
    params: ['logical1', 'logical2'],
  },
  {
    name: 'OR',
    category: 'Logical',
    syntax: 'OR(logical1, [logical2], ...)',
    description: 'Any condition true',
    params: ['logical1', 'logical2'],
  },
  {
    name: 'NOT',
    category: 'Logical',
    syntax: 'NOT(logical)',
    description: 'Reverse logical',
    params: ['logical'],
  },
  {
    name: 'IFERROR',
    category: 'Logical',
    syntax: 'IFERROR(value, value_if_error)',
    description: 'Value or fallback on error',
    params: ['value', 'value_if_error'],
  },
  {
    name: 'IFNA',
    category: 'Logical',
    syntax: 'IFNA(value, value_if_na)',
    description: 'Value or fallback on #N/A',
    params: ['value', 'value_if_na'],
  },
  {
    name: 'SWITCH',
    category: 'Logical',
    syntax: 'SWITCH(expression, val1, result1, ..., [default])',
    description: 'Match and return',
    params: ['expression', 'val1', 'result1', 'default'],
  },
];

export const TEXT_FUNCTIONS: FormulaFunction[] = [
  {
    name: 'CONCATENATE',
    category: 'Text',
    syntax: 'CONCATENATE(text1, [text2], ...)',
    description: 'Join text strings',
    params: ['text1', 'text2'],
  },
  {
    name: 'LEFT',
    category: 'Text',
    syntax: 'LEFT(text, [num_chars])',
    description: 'Left characters',
    params: ['text', 'num_chars'],
  },
  {
    name: 'RIGHT',
    category: 'Text',
    syntax: 'RIGHT(text, [num_chars])',
    description: 'Right characters',
    params: ['text', 'num_chars'],
  },
  {
    name: 'MID',
    category: 'Text',
    syntax: 'MID(text, start_num, num_chars)',
    description: 'Middle characters',
    params: ['text', 'start_num', 'num_chars'],
  },
  {
    name: 'LEN',
    category: 'Text',
    syntax: 'LEN(text)',
    description: 'Text length',
    params: ['text'],
  },
  {
    name: 'TRIM',
    category: 'Text',
    syntax: 'TRIM(text)',
    description: 'Remove extra spaces',
    params: ['text'],
  },
  {
    name: 'UPPER',
    category: 'Text',
    syntax: 'UPPER(text)',
    description: 'To uppercase',
    params: ['text'],
  },
  {
    name: 'LOWER',
    category: 'Text',
    syntax: 'LOWER(text)',
    description: 'To lowercase',
    params: ['text'],
  },
  {
    name: 'SUBSTITUTE',
    category: 'Text',
    syntax: 'SUBSTITUTE(text, old_text, new_text, [instance])',
    description: 'Replace text',
    params: ['text', 'old_text', 'new_text', 'instance'],
  },
  {
    name: 'TEXT',
    category: 'Text',
    syntax: 'TEXT(value, format_text)',
    description: 'Format number as text',
    params: ['value', 'format_text'],
  },
];

export const DATE_FUNCTIONS: FormulaFunction[] = [
  {
    name: 'DATE',
    category: 'Date',
    syntax: 'DATE(year, month, day)',
    description: 'Create a date',
    params: ['year', 'month', 'day'],
  },
  {
    name: 'YEAR',
    category: 'Date',
    syntax: 'YEAR(date)',
    description: 'Year from date',
    params: ['date'],
  },
  {
    name: 'MONTH',
    category: 'Date',
    syntax: 'MONTH(date)',
    description: 'Month from date',
    params: ['date'],
  },
  {
    name: 'DAY',
    category: 'Date',
    syntax: 'DAY(date)',
    description: 'Day from date',
    params: ['date'],
  },
  {
    name: 'EOMONTH',
    category: 'Date',
    syntax: 'EOMONTH(start_date, months)',
    description: 'End of month',
    params: ['start_date', 'months'],
  },
  {
    name: 'EDATE',
    category: 'Date',
    syntax: 'EDATE(start_date, months)',
    description: 'Date +/- months',
    params: ['start_date', 'months'],
  },
  {
    name: 'DATEDIF',
    category: 'Date',
    syntax: 'DATEDIF(start_date, end_date, unit)',
    description: 'Difference between dates',
    params: ['start_date', 'end_date', 'unit'],
  },
  {
    name: 'NETWORKDAYS',
    category: 'Date',
    syntax: 'NETWORKDAYS(start_date, end_date, [holidays])',
    description: 'Working days between dates',
    params: ['start_date', 'end_date', 'holidays'],
  },
  {
    name: 'WORKDAY',
    category: 'Date',
    syntax: 'WORKDAY(start_date, days, [holidays])',
    description: 'Date after working days',
    params: ['start_date', 'days', 'holidays'],
  },
];

export const STATISTICAL_FUNCTIONS: FormulaFunction[] = [
  {
    name: 'MEDIAN',
    category: 'Statistical',
    syntax: 'MEDIAN(number1, [number2], ...)',
    description: 'Median value',
    params: ['number1', 'number2'],
  },
  {
    name: 'MODE',
    category: 'Statistical',
    syntax: 'MODE(number1, [number2], ...)',
    description: 'Most frequent value',
    params: ['number1', 'number2'],
  },
  {
    name: 'STDEV',
    category: 'Statistical',
    syntax: 'STDEV(number1, [number2], ...)',
    description: 'Standard deviation (sample)',
    params: ['number1', 'number2'],
  },
  {
    name: 'STDEVP',
    category: 'Statistical',
    syntax: 'STDEVP(number1, [number2], ...)',
    description: 'Standard deviation (population)',
    params: ['number1', 'number2'],
  },
  {
    name: 'VAR',
    category: 'Statistical',
    syntax: 'VAR(number1, [number2], ...)',
    description: 'Variance (sample)',
    params: ['number1', 'number2'],
  },
  {
    name: 'VARP',
    category: 'Statistical',
    syntax: 'VARP(number1, [number2], ...)',
    description: 'Variance (population)',
    params: ['number1', 'number2'],
  },
  {
    name: 'PERCENTILE',
    category: 'Statistical',
    syntax: 'PERCENTILE(array, k)',
    description: 'k-th percentile',
    params: ['array', 'k'],
  },
  {
    name: 'CORREL',
    category: 'Statistical',
    syntax: 'CORREL(array1, array2)',
    description: 'Correlation coefficient',
    params: ['array1', 'array2'],
  },
  {
    name: 'FORECAST',
    category: 'Statistical',
    syntax: 'FORECAST(x, known_ys, known_xs)',
    description: 'Linear forecast',
    params: ['x', 'known_ys', 'known_xs'],
  },
];
