export interface FormulaFunction {
  name: string;
  category: string;
  syntax: string;
  description: string;
  params: string[];
}

export const FUNCTIONS: FormulaFunction[] = [
  // Lookup
  {
    name: 'VLOOKUP',
    category: 'Lookup',
    syntax: 'VLOOKUP(lookup_value, table_array, col_index, [range_lookup])',
    description: 'Search vertically for a value',
    params: ['lookup_value', 'table_array', 'col_index', 'range_lookup'],
  },
  {
    name: 'HLOOKUP',
    category: 'Lookup',
    syntax: 'HLOOKUP(lookup_value, table_array, row_index, [range_lookup])',
    description: 'Search horizontally for a value',
    params: ['lookup_value', 'table_array', 'row_index', 'range_lookup'],
  },
  {
    name: 'INDEX',
    category: 'Lookup',
    syntax: 'INDEX(array, row_num, [col_num])',
    description: 'Return a value from a table by position',
    params: ['array', 'row_num', 'col_num'],
  },
  {
    name: 'MATCH',
    category: 'Lookup',
    syntax: 'MATCH(lookup_value, lookup_array, [match_type])',
    description: 'Return position of a value in a range',
    params: ['lookup_value', 'lookup_array', 'match_type'],
  },
  {
    name: 'XLOOKUP',
    category: 'Lookup',
    syntax: 'XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found])',
    description: 'Modern lookup with fallback',
    params: ['lookup_value', 'lookup_array', 'return_array', 'if_not_found'],
  },
  {
    name: 'OFFSET',
    category: 'Lookup',
    syntax: 'OFFSET(reference, rows, cols, [height], [width])',
    description: 'Return a range offset from a reference',
    params: ['reference', 'rows', 'cols', 'height', 'width'],
  },
  // Math
  {
    name: 'SUM',
    category: 'Math',
    syntax: 'SUM(number1, [number2], ...)',
    description: 'Sum all numbers',
    params: ['number1', 'number2'],
  },
  {
    name: 'SUMIF',
    category: 'Math',
    syntax: 'SUMIF(range, criteria, [sum_range])',
    description: 'Sum with condition',
    params: ['range', 'criteria', 'sum_range'],
  },
  {
    name: 'SUMIFS',
    category: 'Math',
    syntax: 'SUMIFS(sum_range, criteria_range1, criteria1, ...)',
    description: 'Sum with multiple conditions',
    params: ['sum_range', 'criteria_range1', 'criteria1'],
  },
  {
    name: 'SUMPRODUCT',
    category: 'Math',
    syntax: 'SUMPRODUCT(array1, [array2], ...)',
    description: 'Sum of products of arrays',
    params: ['array1', 'array2'],
  },
  {
    name: 'COUNT',
    category: 'Math',
    syntax: 'COUNT(value1, [value2], ...)',
    description: 'Count numbers',
    params: ['value1', 'value2'],
  },
  {
    name: 'COUNTIF',
    category: 'Math',
    syntax: 'COUNTIF(range, criteria)',
    description: 'Count with condition',
    params: ['range', 'criteria'],
  },
  {
    name: 'COUNTIFS',
    category: 'Math',
    syntax: 'COUNTIFS(range1, criteria1, ...)',
    description: 'Count with multiple conditions',
    params: ['range1', 'criteria1'],
  },
  {
    name: 'AVERAGE',
    category: 'Math',
    syntax: 'AVERAGE(number1, [number2], ...)',
    description: 'Average of numbers',
    params: ['number1', 'number2'],
  },
  {
    name: 'AVERAGEIF',
    category: 'Math',
    syntax: 'AVERAGEIF(range, criteria, [average_range])',
    description: 'Average with condition',
    params: ['range', 'criteria', 'average_range'],
  },
  {
    name: 'AVERAGEIFS',
    category: 'Math',
    syntax: 'AVERAGEIFS(avg_range, criteria_range1, criteria1, ...)',
    description: 'Average with multiple conditions',
    params: ['avg_range', 'criteria_range1', 'criteria1'],
  },
  {
    name: 'MIN',
    category: 'Math',
    syntax: 'MIN(number1, [number2], ...)',
    description: 'Minimum value',
    params: ['number1', 'number2'],
  },
  {
    name: 'MAX',
    category: 'Math',
    syntax: 'MAX(number1, [number2], ...)',
    description: 'Maximum value',
    params: ['number1', 'number2'],
  },
  {
    name: 'ABS',
    category: 'Math',
    syntax: 'ABS(number)',
    description: 'Absolute value',
    params: ['number'],
  },
  {
    name: 'ROUND',
    category: 'Math',
    syntax: 'ROUND(number, num_digits)',
    description: 'Round to digits',
    params: ['number', 'num_digits'],
  },
  {
    name: 'ROUNDUP',
    category: 'Math',
    syntax: 'ROUNDUP(number, num_digits)',
    description: 'Round up',
    params: ['number', 'num_digits'],
  },
  {
    name: 'ROUNDDOWN',
    category: 'Math',
    syntax: 'ROUNDDOWN(number, num_digits)',
    description: 'Round down',
    params: ['number', 'num_digits'],
  },
  {
    name: 'MOD',
    category: 'Math',
    syntax: 'MOD(number, divisor)',
    description: 'Remainder after division',
    params: ['number', 'divisor'],
  },
  {
    name: 'POWER',
    category: 'Math',
    syntax: 'POWER(number, power)',
    description: 'Raise to power',
    params: ['number', 'power'],
  },
  {
    name: 'SQRT',
    category: 'Math',
    syntax: 'SQRT(number)',
    description: 'Square root',
    params: ['number'],
  },
  // Financial
  {
    name: 'IRR',
    category: 'Financial',
    syntax: 'IRR(values, [guess])',
    description: 'Internal rate of return',
    params: ['values', 'guess'],
  },
  {
    name: 'XIRR',
    category: 'Financial',
    syntax: 'XIRR(values, dates, [guess])',
    description: 'IRR with specific dates',
    params: ['values', 'dates', 'guess'],
  },
  {
    name: 'NPV',
    category: 'Financial',
    syntax: 'NPV(rate, value1, [value2], ...)',
    description: 'Net present value',
    params: ['rate', 'value1', 'value2'],
  },
  {
    name: 'XNPV',
    category: 'Financial',
    syntax: 'XNPV(rate, values, dates)',
    description: 'NPV with specific dates',
    params: ['rate', 'values', 'dates'],
  },
  {
    name: 'PV',
    category: 'Financial',
    syntax: 'PV(rate, nper, pmt, [fv], [type])',
    description: 'Present value',
    params: ['rate', 'nper', 'pmt', 'fv', 'type'],
  },
  {
    name: 'FV',
    category: 'Financial',
    syntax: 'FV(rate, nper, pmt, [pv], [type])',
    description: 'Future value',
    params: ['rate', 'nper', 'pmt', 'pv', 'type'],
  },
  {
    name: 'PMT',
    category: 'Financial',
    syntax: 'PMT(rate, nper, pv, [fv], [type])',
    description: 'Payment per period',
    params: ['rate', 'nper', 'pv', 'fv', 'type'],
  },
  {
    name: 'IPMT',
    category: 'Financial',
    syntax: 'IPMT(rate, per, nper, pv, [fv], [type])',
    description: 'Interest payment',
    params: ['rate', 'per', 'nper', 'pv', 'fv', 'type'],
  },
  {
    name: 'PPMT',
    category: 'Financial',
    syntax: 'PPMT(rate, per, nper, pv, [fv], [type])',
    description: 'Principal payment',
    params: ['rate', 'per', 'nper', 'pv', 'fv', 'type'],
  },
  {
    name: 'NPER',
    category: 'Financial',
    syntax: 'NPER(rate, pmt, pv, [fv], [type])',
    description: 'Number of periods',
    params: ['rate', 'pmt', 'pv', 'fv', 'type'],
  },
  {
    name: 'RATE',
    category: 'Financial',
    syntax: 'RATE(nper, pmt, pv, [fv], [type], [guess])',
    description: 'Interest rate per period',
    params: ['nper', 'pmt', 'pv', 'fv', 'type', 'guess'],
  },
  {
    name: 'CAGR',
    category: 'Financial',
    syntax: 'CAGR(begin_value, end_value, periods)',
    description: 'Compound annual growth rate',
    params: ['begin_value', 'end_value', 'periods'],
  },
  {
    name: 'SLN',
    category: 'Financial',
    syntax: 'SLN(cost, salvage, life)',
    description: 'Straight-line depreciation',
    params: ['cost', 'salvage', 'life'],
  },
  {
    name: 'DB',
    category: 'Financial',
    syntax: 'DB(cost, salvage, life, period, [month])',
    description: 'Declining balance depreciation',
    params: ['cost', 'salvage', 'life', 'period', 'month'],
  },
  {
    name: 'SYD',
    category: 'Financial',
    syntax: 'SYD(cost, salvage, life, per)',
    description: 'Sum-of-years depreciation',
    params: ['cost', 'salvage', 'life', 'per'],
  },
  {
    name: 'DDB',
    category: 'Financial',
    syntax: 'DDB(cost, salvage, life, period, [factor])',
    description: 'Double declining depreciation',
    params: ['cost', 'salvage', 'life', 'period', 'factor'],
  },
  // Logical
  {
    name: 'IF',
    category: 'Logical',
    syntax: 'IF(logical_test, value_if_true, value_if_false)',
    description: 'Conditional value',
    params: ['logical_test', 'value_if_true', 'value_if_false'],
  },
  {
    name: 'IFS',
    category: 'Logical',
    syntax: 'IFS(test1, val1, test2, val2, ...)',
    description: 'Multiple conditions',
    params: ['test1', 'val1', 'test2', 'val2'],
  },
  {
    name: 'AND',
    category: 'Logical',
    syntax: 'AND(logical1, [logical2], ...)',
    description: 'All conditions true',
    params: ['logical1', 'logical2'],
  },
  {
    name: 'OR',
    category: 'Logical',
    syntax: 'OR(logical1, [logical2], ...)',
    description: 'Any condition true',
    params: ['logical1', 'logical2'],
  },
  {
    name: 'NOT',
    category: 'Logical',
    syntax: 'NOT(logical)',
    description: 'Reverse logical',
    params: ['logical'],
  },
  {
    name: 'IFERROR',
    category: 'Logical',
    syntax: 'IFERROR(value, value_if_error)',
    description: 'Value or fallback on error',
    params: ['value', 'value_if_error'],
  },
  {
    name: 'IFNA',
    category: 'Logical',
    syntax: 'IFNA(value, value_if_na)',
    description: 'Value or fallback on #N/A',
    params: ['value', 'value_if_na'],
  },
  {
    name: 'SWITCH',
    category: 'Logical',
    syntax: 'SWITCH(expression, val1, result1, ..., [default])',
    description: 'Match and return',
    params: ['expression', 'val1', 'result1', 'default'],
  },
  // Text
  {
    name: 'CONCATENATE',
    category: 'Text',
    syntax: 'CONCATENATE(text1, [text2], ...)',
    description: 'Join text strings',
    params: ['text1', 'text2'],
  },
  {
    name: 'LEFT',
    category: 'Text',
    syntax: 'LEFT(text, [num_chars])',
    description: 'Left characters',
    params: ['text', 'num_chars'],
  },
  {
    name: 'RIGHT',
    category: 'Text',
    syntax: 'RIGHT(text, [num_chars])',
    description: 'Right characters',
    params: ['text', 'num_chars'],
  },
  {
    name: 'MID',
    category: 'Text',
    syntax: 'MID(text, start_num, num_chars)',
    description: 'Middle characters',
    params: ['text', 'start_num', 'num_chars'],
  },
  {
    name: 'LEN',
    category: 'Text',
    syntax: 'LEN(text)',
    description: 'Text length',
    params: ['text'],
  },
  {
    name: 'TRIM',
    category: 'Text',
    syntax: 'TRIM(text)',
    description: 'Remove extra spaces',
    params: ['text'],
  },
  {
    name: 'UPPER',
    category: 'Text',
    syntax: 'UPPER(text)',
    description: 'To uppercase',
    params: ['text'],
  },
  {
    name: 'LOWER',
    category: 'Text',
    syntax: 'LOWER(text)',
    description: 'To lowercase',
    params: ['text'],
  },
  {
    name: 'SUBSTITUTE',
    category: 'Text',
    syntax: 'SUBSTITUTE(text, old_text, new_text, [instance])',
    description: 'Replace text',
    params: ['text', 'old_text', 'new_text', 'instance'],
  },
  {
    name: 'TEXT',
    category: 'Text',
    syntax: 'TEXT(value, format_text)',
    description: 'Format number as text',
    params: ['value', 'format_text'],
  },
  // Date
  {
    name: 'DATE',
    category: 'Date',
    syntax: 'DATE(year, month, day)',
    description: 'Create a date',
    params: ['year', 'month', 'day'],
  },
  {
    name: 'YEAR',
    category: 'Date',
    syntax: 'YEAR(date)',
    description: 'Year from date',
    params: ['date'],
  },
  {
    name: 'MONTH',
    category: 'Date',
    syntax: 'MONTH(date)',
    description: 'Month from date',
    params: ['date'],
  },
  {
    name: 'DAY',
    category: 'Date',
    syntax: 'DAY(date)',
    description: 'Day from date',
    params: ['date'],
  },
  {
    name: 'EOMONTH',
    category: 'Date',
    syntax: 'EOMONTH(start_date, months)',
    description: 'End of month',
    params: ['start_date', 'months'],
  },
  {
    name: 'EDATE',
    category: 'Date',
    syntax: 'EDATE(start_date, months)',
    description: 'Date +/- months',
    params: ['start_date', 'months'],
  },
  {
    name: 'DATEDIF',
    category: 'Date',
    syntax: 'DATEDIF(start_date, end_date, unit)',
    description: 'Difference between dates',
    params: ['start_date', 'end_date', 'unit'],
  },
  {
    name: 'NETWORKDAYS',
    category: 'Date',
    syntax: 'NETWORKDAYS(start_date, end_date, [holidays])',
    description: 'Working days between dates',
    params: ['start_date', 'end_date', 'holidays'],
  },
  {
    name: 'WORKDAY',
    category: 'Date',
    syntax: 'WORKDAY(start_date, days, [holidays])',
    description: 'Date after working days',
    params: ['start_date', 'days', 'holidays'],
  },
  // Statistical
  {
    name: 'MEDIAN',
    category: 'Statistical',
    syntax: 'MEDIAN(number1, [number2], ...)',
    description: 'Median value',
    params: ['number1', 'number2'],
  },
  {
    name: 'MODE',
    category: 'Statistical',
    syntax: 'MODE(number1, [number2], ...)',
    description: 'Most frequent value',
    params: ['number1', 'number2'],
  },
  {
    name: 'STDEV',
    category: 'Statistical',
    syntax: 'STDEV(number1, [number2], ...)',
    description: 'Standard deviation (sample)',
    params: ['number1', 'number2'],
  },
  {
    name: 'STDEVP',
    category: 'Statistical',
    syntax: 'STDEVP(number1, [number2], ...)',
    description: 'Standard deviation (population)',
    params: ['number1', 'number2'],
  },
  {
    name: 'VAR',
    category: 'Statistical',
    syntax: 'VAR(number1, [number2], ...)',
    description: 'Variance (sample)',
    params: ['number1', 'number2'],
  },
  {
    name: 'VARP',
    category: 'Statistical',
    syntax: 'VARP(number1, [number2], ...)',
    description: 'Variance (population)',
    params: ['number1', 'number2'],
  },
  {
    name: 'PERCENTILE',
    category: 'Statistical',
    syntax: 'PERCENTILE(array, k)',
    description: 'k-th percentile',
    params: ['array', 'k'],
  },
  {
    name: 'CORREL',
    category: 'Statistical',
    syntax: 'CORREL(array1, array2)',
    description: 'Correlation coefficient',
    params: ['array1', 'array2'],
  },
  {
    name: 'FORECAST',
    category: 'Statistical',
    syntax: 'FORECAST(x, known_ys, known_xs)',
    description: 'Linear forecast',
    params: ['x', 'known_ys', 'known_xs'],
  },
];
