import type { FormulaFunction } from './formulaData';

export const LOOKUP_FUNCTIONS: FormulaFunction[] = [
  {
    name: 'VLOOKUP',
    category: 'Lookup',
    syntax: 'VLOOKUP(lookup_value, table_array, col_index, [range_lookup])',
    description: 'Search vertically for a value',
    params: ['lookup_value', 'table_array', 'col_index', 'range_lookup'],
  },
  {
    name: 'HLOOKUP',
    category: 'Lookup',
    syntax: 'HLOOKUP(lookup_value, table_array, row_index, [range_lookup])',
    description: 'Search horizontally for a value',
    params: ['lookup_value', 'table_array', 'row_index', 'range_lookup'],
  },
  {
    name: 'INDEX',
    category: 'Lookup',
    syntax: 'INDEX(array, row_num, [col_num])',
    description: 'Return a value from a table by position',
    params: ['array', 'row_num', 'col_num'],
  },
  {
    name: 'MATCH',
    category: 'Lookup',
    syntax: 'MATCH(lookup_value, lookup_array, [match_type])',
    description: 'Return position of a value in a range',
    params: ['lookup_value', 'lookup_array', 'match_type'],
  },
  {
    name: 'XLOOKUP',
    category: 'Lookup',
    syntax: 'XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found])',
    description: 'Modern lookup with fallback',
    params: ['lookup_value', 'lookup_array', 'return_array', 'if_not_found'],
  },
  {
    name: 'OFFSET',
    category: 'Lookup',
    syntax: 'OFFSET(reference, rows, cols, [height], [width])',
    description: 'Return a range offset from a reference',
    params: ['reference', 'rows', 'cols', 'height', 'width'],
  },
];

export const MATH_FUNCTIONS: FormulaFunction[] = [
  {
    name: 'SUM',
    category: 'Math',
    syntax: 'SUM(number1, [number2], ...)',
    description: 'Sum all numbers',
    params: ['number1', 'number2'],
  },
  {
    name: 'SUMIF',
    category: 'Math',
    syntax: 'SUMIF(range, criteria, [sum_range])',
    description: 'Sum with condition',
    params: ['range', 'criteria', 'sum_range'],
  },
  {
    name: 'SUMIFS',
    category: 'Math',
    syntax: 'SUMIFS(sum_range, criteria_range1, criteria1, ...)',
    description: 'Sum with multiple conditions',
    params: ['sum_range', 'criteria_range1', 'criteria1'],
  },
  {
    name: 'SUMPRODUCT',
    category: 'Math',
    syntax: 'SUMPRODUCT(array1, [array2], ...)',
    description: 'Sum of products of arrays',
    params: ['array1', 'array2'],
  },
  {
    name: 'COUNT',
    category: 'Math',
    syntax: 'COUNT(value1, [value2], ...)',
    description: 'Count numbers',
    params: ['value1', 'value2'],
  },
  {
    name: 'COUNTIF',
    category: 'Math',
    syntax: 'COUNTIF(range, criteria)',
    description: 'Count with condition',
    params: ['range', 'criteria'],
  },
  {
    name: 'COUNTIFS',
    category: 'Math',
    syntax: 'COUNTIFS(range1, criteria1, ...)',
    description: 'Count with multiple conditions',
    params: ['range1', 'criteria1'],
  },
  {
    name: 'AVERAGE',
    category: 'Math',
    syntax: 'AVERAGE(number1, [number2], ...)',
    description: 'Average of numbers',
    params: ['number1', 'number2'],
  },
  {
    name: 'AVERAGEIF',
    category: 'Math',
    syntax: 'AVERAGEIF(range, criteria, [average_range])',
    description: 'Average with condition',
    params: ['range', 'criteria', 'average_range'],
  },
  {
    name: 'AVERAGEIFS',
    category: 'Math',
    syntax: 'AVERAGEIFS(avg_range, criteria_range1, criteria1, ...)',
    description: 'Average with multiple conditions',
    params: ['avg_range', 'criteria_range1', 'criteria1'],
  },
  {
    name: 'MIN',
    category: 'Math',
    syntax: 'MIN(number1, [number2], ...)',
    description: 'Minimum value',
    params: ['number1', 'number2'],
  },
  {
    name: 'MAX',
    category: 'Math',
    syntax: 'MAX(number1, [number2], ...)',
    description: 'Maximum value',
    params: ['number1', 'number2'],
  },
  {
    name: 'ABS',
    category: 'Math',
    syntax: 'ABS(number)',
    description: 'Absolute value',
    params: ['number'],
  },
  {
    name: 'ROUND',
    category: 'Math',
    syntax: 'ROUND(number, num_digits)',
    description: 'Round to digits',
    params: ['number', 'num_digits'],
  },
  {
    name: 'ROUNDUP',
    category: 'Math',
    syntax: 'ROUNDUP(number, num_digits)',
    description: 'Round up',
    params: ['number', 'num_digits'],
  },
  {
    name: 'ROUNDDOWN',
    category: 'Math',
    syntax: 'ROUNDDOWN(number, num_digits)',
    description: 'Round down',
    params: ['number', 'num_digits'],
  },
  {
    name: 'MOD',
    category: 'Math',
    syntax: 'MOD(number, divisor)',
    description: 'Remainder after division',
    params: ['number', 'divisor'],
  },
  {
    name: 'POWER',
    category: 'Math',
    syntax: 'POWER(number, power)',
    description: 'Raise to power',
    params: ['number', 'power'],
  },
  {
    name: 'SQRT',
    category: 'Math',
    syntax: 'SQRT(number)',
    description: 'Square root',
    params: ['number'],
  },
];
