import type { GLAccount } from '@/types';

export const glAccounts: GLAccount[] = [
  // === Revenue (4000-4300) ===
  {
    id: 'acct-4000',
    code: '4000',
    name: 'Revenue',
    type: 'Revenue',
    category: 'Operating',
    subCategory: 'Revenue',
    parentId: null,
    level: 0,
    sortOrder: 100,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-4100',
    code: '4100',
    name: 'Subscription Revenue',
    type: 'Revenue',
    category: 'Operating',
    subCategory: 'Revenue',
    parentId: 'acct-4000',
    level: 1,
    sortOrder: 110,
    isActive: true,
    entityId: 'ent-us',
    departmentId: 'dept-sales',
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-4200',
    code: '4200',
    name: 'Professional Services Revenue',
    type: 'Revenue',
    category: 'Operating',
    subCategory: 'Revenue',
    parentId: 'acct-4000',
    level: 1,
    sortOrder: 120,
    isActive: true,
    entityId: 'ent-us',
    departmentId: 'dept-sales',
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-4300',
    code: '4300',
    name: 'Other Revenue',
    type: 'Revenue',
    category: 'Operating',
    subCategory: 'Revenue',
    parentId: 'acct-4000',
    level: 1,
    sortOrder: 130,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },

  // === COGS (5000-5300) ===
  {
    id: 'acct-5000',
    code: '5000',
    name: 'Cost of Goods Sold',
    type: 'COGS',
    category: 'Operating',
    subCategory: 'COGS',
    parentId: null,
    level: 0,
    sortOrder: 200,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-5100',
    code: '5100',
    name: 'Cloud Infrastructure',
    type: 'COGS',
    category: 'Operating',
    subCategory: 'COGS',
    parentId: 'acct-5000',
    level: 1,
    sortOrder: 210,
    isActive: true,
    entityId: 'ent-us',
    departmentId: 'dept-operations',
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-5200',
    code: '5200',
    name: 'Direct Labor',
    type: 'COGS',
    category: 'Operating',
    subCategory: 'COGS',
    parentId: 'acct-5000',
    level: 1,
    sortOrder: 220,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-5300',
    code: '5300',
    name: 'Licensing & Royalties',
    type: 'COGS',
    category: 'Operating',
    subCategory: 'COGS',
    parentId: 'acct-5000',
    level: 1,
    sortOrder: 230,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },

  // === Gross Profit ===
  {
    id: 'acct-6000',
    code: '6000',
    name: 'Gross Profit',
    type: 'Revenue',
    category: 'Summary',
    subCategory: 'GrossProfit',
    parentId: null,
    level: 0,
    sortOrder: 300,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: true,
    formula: '4000 - 5000',
    children: [],
  },

  // === OpEx (7000-7900) ===
  {
    id: 'acct-7000',
    code: '7000',
    name: 'Operating Expenses',
    type: 'OpEx',
    category: 'Operating',
    subCategory: 'OpEx',
    parentId: null,
    level: 0,
    sortOrder: 400,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-7100',
    code: '7100',
    name: 'Salaries & Wages',
    type: 'OpEx',
    category: 'Operating',
    subCategory: 'OpEx',
    parentId: 'acct-7000',
    level: 1,
    sortOrder: 410,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-7200',
    code: '7200',
    name: 'Employee Benefits',
    type: 'OpEx',
    category: 'Operating',
    subCategory: 'OpEx',
    parentId: 'acct-7000',
    level: 1,
    sortOrder: 420,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-7300',
    code: '7300',
    name: 'Marketing & Advertising',
    type: 'OpEx',
    category: 'Operating',
    subCategory: 'OpEx',
    parentId: 'acct-7000',
    level: 1,
    sortOrder: 430,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-7400',
    code: '7400',
    name: 'Travel & Entertainment',
    type: 'OpEx',
    category: 'Operating',
    subCategory: 'OpEx',
    parentId: 'acct-7000',
    level: 1,
    sortOrder: 440,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-7500',
    code: '7500',
    name: 'Software & Tools',
    type: 'OpEx',
    category: 'Operating',
    subCategory: 'OpEx',
    parentId: 'acct-7000',
    level: 1,
    sortOrder: 450,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-7600',
    code: '7600',
    name: 'Rent & Facilities',
    type: 'OpEx',
    category: 'Operating',
    subCategory: 'OpEx',
    parentId: 'acct-7000',
    level: 1,
    sortOrder: 460,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-7700',
    code: '7700',
    name: 'Professional Services',
    type: 'OpEx',
    category: 'Operating',
    subCategory: 'OpEx',
    parentId: 'acct-7000',
    level: 1,
    sortOrder: 470,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-7800',
    code: '7800',
    name: 'Depreciation & Amortization',
    type: 'OpEx',
    category: 'Operating',
    subCategory: 'OpEx',
    parentId: 'acct-7000',
    level: 1,
    sortOrder: 480,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-7900',
    code: '7900',
    name: 'Other Operating Expenses',
    type: 'OpEx',
    category: 'Operating',
    subCategory: 'OpEx',
    parentId: 'acct-7000',
    level: 1,
    sortOrder: 490,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },

  // === Summary Metrics ===
  {
    id: 'acct-8000',
    code: '8000',
    name: 'EBITDA',
    type: 'OpEx',
    category: 'Summary',
    subCategory: 'Profitability',
    parentId: null,
    level: 0,
    sortOrder: 500,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: true,
    formula: '6000 - 7000 + 7800',
    children: [],
  },
  {
    id: 'acct-8100',
    code: '8100',
    name: 'Operating Income',
    type: 'OpEx',
    category: 'Summary',
    subCategory: 'Profitability',
    parentId: null,
    level: 0,
    sortOrder: 510,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: true,
    formula: '6000 - 7000',
    children: [],
  },
  {
    id: 'acct-8200',
    code: '8200',
    name: 'Net Income',
    type: 'Equity',
    category: 'Summary',
    subCategory: 'Profitability',
    parentId: null,
    level: 0,
    sortOrder: 520,
    isActive: true,
    entityId: 'ent-us',
    departmentId: null,
    isCalculated: true,
    formula: '8100 - tax - interest',
    children: [],
  },
];

export function getAccountsByType(type: GLAccount['type']): GLAccount[] {
  return glAccounts.filter((a) => a.type === type);
}

export function getAccountById(id: string): GLAccount | undefined {
  return glAccounts.find((a) => a.id === id);
}

export function getAccountByCode(code: string): GLAccount | undefined {
  return glAccounts.find((a) => a.code === code);
}
