import type { ActivityLog, Notification, Task, ApprovalRequest } from '@/types';

export const ACTIVITIES: ActivityLog[] = [
  {
    id: 'act-001',
    userId: 'usr-001',
    userName: 'Sarah Chen',
    userEmail: 'sarah.chen@finplan.com',
    action: 'Submitted Budget',
    resourceType: 'Budget',
    resourceId: 'bgt-001',
    resourceName: 'FY2024 Annual Operating Budget',
    details: { newValue: 'InReview', oldValue: 'Draft', field: 'status' },
    timestamp: '2024-12-01T12:00:00Z',
  },
  {
    id: 'act-002',
    userId: 'usr-008',
    userName: 'John Mitchell',
    userEmail: 'john.mitchell@finplan.com',
    action: 'Approved Budget',
    resourceType: 'Budget',
    resourceId: 'bgt-001',
    resourceName: 'FY2024 Annual Operating Budget',
    details: { newValue: 'Approved', oldValue: 'InReview', field: 'status' },
    timestamp: '2024-12-20T16:30:00Z',
  },
  {
    id: 'act-003',
    userId: 'usr-003',
    userName: 'Jessica Park',
    userEmail: 'jessica.park@finplan.com',
    action: 'Updated Forecast',
    resourceType: 'Forecast',
    resourceId: 'fcst-001',
    resourceName: 'Q4 2024 Rolling Forecast',
    details: { newValue: '4800000', oldValue: '4500000', field: 'Q4 Revenue Projection' },
    timestamp: '2024-11-28T14:20:00Z',
  },
  {
    id: 'act-004',
    userId: 'usr-004',
    userName: 'David Kim',
    userEmail: 'david.kim@finplan.com',
    action: 'Added Commentary',
    resourceType: 'Variance',
    resourceId: 'acct-5100',
    resourceName: 'Cloud Infrastructure',
    details: { field: 'commentary' },
    timestamp: '2024-11-27T10:45:00Z',
  },
  {
    id: 'act-005',
    userId: 'usr-006',
    userName: 'Tom Baker',
    userEmail: 'tom.baker@finplan.com',
    action: 'Reviewed Department Budget',
    resourceType: 'Budget',
    resourceId: 'bgt-004',
    resourceName: 'FY2024 Sales Plan',
    details: { newValue: 'Approved', oldValue: 'InReview', field: 'status' },
    timestamp: '2024-12-15T10:00:00Z',
  },
  {
    id: 'act-006',
    userId: 'usr-005',
    userName: 'Emily Wu',
    userEmail: 'emily.wu@finplan.com',
    action: 'Exported Report',
    resourceType: 'Report',
    resourceId: 'rpt-001',
    resourceName: 'P&L Summary Report',
    details: null,
    timestamp: '2024-11-25T16:00:00Z',
  },
  {
    id: 'act-007',
    userId: 'usr-002',
    userName: 'Mike Torres',
    userEmail: 'mike.torres@finplan.com',
    action: 'Data Import',
    resourceType: 'Import',
    resourceId: 'imp-001',
    resourceName: 'October 2024 Actuals',
    details: { newValue: 'Completed', oldValue: 'Processing', field: 'status' },
    timestamp: '2024-11-10T09:30:00Z',
  },
  {
    id: 'act-008',
    userId: 'usr-001',
    userName: 'Sarah Chen',
    userEmail: 'sarah.chen@finplan.com',
    action: 'Created Scenario',
    resourceType: 'Scenario',
    resourceId: 'scn-002',
    resourceName: 'Best Case',
    details: null,
    timestamp: '2024-01-10T09:00:00Z',
  },
  {
    id: 'act-009',
    userId: 'usr-003',
    userName: 'Jessica Park',
    userEmail: 'jessica.park@finplan.com',
    action: 'Updated Assumption',
    resourceType: 'Scenario',
    resourceId: 'scn-004',
    resourceName: 'Cost Cutting',
    details: { newValue: '-2', oldValue: '6', field: 'OpEx Growth' },
    timestamp: '2024-11-14T09:30:00Z',
  },
  {
    id: 'act-010',
    userId: 'usr-008',
    userName: 'John Mitchell',
    userEmail: 'john.mitchell@finplan.com',
    action: 'Logged In',
    resourceType: 'Session',
    resourceId: 'sess-001',
    resourceName: 'User Session',
    details: null,
    timestamp: '2024-12-02T06:00:00Z',
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    type: 'approval',
    title: 'Budget Approval Required',
    message: 'FY2024 Annual Operating Budget has been submitted for review by Sarah Chen.',
    isRead: false,
    actionUrl: '/budgets/bgt-001',
    createdAt: '2024-12-02T09:30:00Z',
  },
  {
    id: 'notif-002',
    type: 'success',
    title: 'Forecast Published',
    message: 'Q4 2024 Rolling Forecast has been published and is now available for review.',
    isRead: false,
    actionUrl: '/forecasts/fcst-001',
    createdAt: '2024-12-02T08:00:00Z',
  },
  {
    id: 'notif-003',
    type: 'warning',
    title: 'Variance Threshold Breach',
    message: 'Marketing budget is 15% over threshold for November. Review required.',
    isRead: true,
    actionUrl: '/variance',
    createdAt: '2024-12-01T16:45:00Z',
  },
  {
    id: 'notif-004',
    type: 'info',
    title: 'Data Import Complete',
    message: 'October actuals import completed with 2 minor warnings.',
    isRead: true,
    actionUrl: '/data/import',
    createdAt: '2024-12-01T12:00:00Z',
  },
  {
    id: 'notif-005',
    type: 'mention',
    title: 'Mention in Commentary',
    message: 'David Kim mentioned you in the variance commentary for Cloud Infrastructure.',
    isRead: false,
    actionUrl: '/variance/acct-5100',
    createdAt: '2024-12-02T10:15:00Z',
  },
  {
    id: 'notif-006',
    type: 'deadline',
    title: 'Budget Submission Deadline',
    message: 'Department budgets for FY2025 are due in 5 business days.',
    isRead: true,
    actionUrl: '/budgets',
    createdAt: '2024-12-01T09:00:00Z',
  },
  {
    id: 'notif-007',
    type: 'error',
    title: 'ERP Sync Failure',
    message: 'SAP connection timed out during scheduled sync. Retry in progress.',
    isRead: false,
    actionUrl: '/data/import',
    createdAt: '2024-12-02T11:30:00Z',
  },
  {
    id: 'notif-008',
    type: 'info',
    title: 'Scenario Updated',
    message: 'Cost Cutting scenario metrics have been recalculated based on new assumptions.',
    isRead: true,
    actionUrl: '/scenarios/scn-004',
    createdAt: '2024-11-30T14:00:00Z',
  },
];

export const TASKS: Task[] = [
  {
    id: 'task-001',
    title: 'Review Q4 Forecast Variance',
    description:
      'Review and provide commentary on the Q4 forecast variance for subscription revenue.',
    assigneeId: 'usr-003',
    assigneeName: 'Jessica Park',
    dueDate: '2024-12-10T17:00:00Z',
    priority: 'High',
    status: 'InProgress',
    relatedResourceType: 'Forecast',
    relatedResourceId: 'fcst-001',
    createdBy: 'usr-001',
    createdAt: '2024-12-01T08:00:00Z',
  },
  {
    id: 'task-002',
    title: 'Update Headcount Assumptions',
    description:
      'Update headcount assumptions in the FY2025 Preliminary Forecast based on VP-level approvals.',
    assigneeId: 'usr-002',
    assigneeName: 'Mike Torres',
    dueDate: '2024-12-15T17:00:00Z',
    priority: 'Medium',
    status: 'Todo',
    relatedResourceType: 'Forecast',
    relatedResourceId: 'fcst-003',
    createdBy: 'usr-001',
    createdAt: '2024-12-02T09:00:00Z',
  },
  {
    id: 'task-003',
    title: 'Submit October Commentary',
    description: 'Complete and submit variance commentary for all Marketing accounts.',
    assigneeId: 'usr-003',
    assigneeName: 'Jessica Park',
    dueDate: '2024-11-20T17:00:00Z',
    priority: 'High',
    status: 'Done',
    relatedResourceType: 'Variance',
    relatedResourceId: 'acct-7300',
    createdBy: 'usr-001',
    createdAt: '2024-11-10T09:00:00Z',
  },
  {
    id: 'task-004',
    title: 'Audit Cloud Infrastructure Costs',
    description:
      'Investigate the 8% overspend in cloud infrastructure and identify optimization opportunities.',
    assigneeId: 'usr-004',
    assigneeName: 'David Kim',
    dueDate: '2024-12-20T17:00:00Z',
    priority: 'Critical',
    status: 'Todo',
    relatedResourceType: 'Variance',
    relatedResourceId: 'acct-5100',
    createdBy: 'usr-001',
    createdAt: '2024-12-01T10:00:00Z',
  },
  {
    id: 'task-005',
    title: 'Prepare Board Report',
    description:
      'Assemble Q4 board report with variance analysis, forecast updates, and scenario projections.',
    assigneeId: 'usr-001',
    assigneeName: 'Sarah Chen',
    dueDate: '2025-01-05T17:00:00Z',
    priority: 'High',
    status: 'Todo',
    relatedResourceType: 'Report',
    relatedResourceId: 'rpt-001',
    createdBy: 'usr-008',
    createdAt: '2024-12-01T07:00:00Z',
  },
  {
    id: 'task-006',
    title: 'Reconcile UK Entity FX Differences',
    description: 'Reconcile FX rate differences in UK subsidiary accounts for November close.',
    assigneeId: 'usr-005',
    assigneeName: 'Emily Wu',
    dueDate: '2024-12-12T17:00:00Z',
    priority: 'Medium',
    status: 'InProgress',
    relatedResourceType: null,
    relatedResourceId: null,
    createdBy: 'usr-001',
    createdAt: '2024-12-01T08:30:00Z',
  },
];

export const APPROVALS: ApprovalRequest[] = [
  {
    id: 'apr-001',
    resourceType: 'Budget',
    resourceId: 'bgt-002',
    resourceName: 'Q2 2024 Marketing Budget',
    requesterId: 'usr-003',
    requesterName: 'Jessica Park',
    amount: 2_450_000,
    status: 'Pending',
    submittedAt: '2024-03-15T14:20:00Z',
    reviewedAt: null,
    reviewedBy: null,
    comments: null,
  },
  {
    id: 'apr-002',
    resourceType: 'Budget',
    resourceId: 'bgt-001',
    resourceName: 'FY2024 Annual Operating Budget',
    requesterId: 'usr-001',
    requesterName: 'Sarah Chen',
    amount: 54_800_000,
    status: 'Approved',
    submittedAt: '2023-12-01T12:00:00Z',
    reviewedAt: '2023-12-20T16:30:00Z',
    reviewedBy: 'John Mitchell',
    comments: 'Approved with minor adjustments to marketing spend.',
  },
  {
    id: 'apr-003',
    resourceType: 'Forecast',
    resourceId: 'fcst-004',
    resourceName: 'UK Entity Rolling Forecast',
    requesterId: 'usr-004',
    requesterName: 'David Kim',
    amount: 0,
    status: 'ChangesRequested',
    submittedAt: '2024-11-28T09:30:00Z',
    reviewedAt: '2024-11-29T14:00:00Z',
    reviewedBy: 'Sarah Chen',
    comments: 'Please update FX rate assumptions to reflect current spot rates.',
  },
];
