import type { Comment, Task, ApprovalRequest, ActivityLog } from '@/types';

export const mockComments: Comment[] = [
  {
    id: 'cmt-001',
    resourceType: 'budget',
    resourceId: 'bgt-001',
    cellId: null,
    parentId: null,
    authorId: 'usr-003',
    authorName: 'Jessica Park',
    authorInitials: 'JP',
    content: 'Should we adjust the marketing budget for Q2 campaign spend?',
    mentions: ['usr-001'],
    isResolved: false,
    resolvedAt: null,
    createdAt: '2024-11-20T14:30:00Z',
    replies: [
      {
        id: 'cmt-001-r1',
        resourceType: 'budget',
        resourceId: 'bgt-001',
        cellId: null,
        parentId: 'cmt-001',
        authorId: 'usr-001',
        authorName: 'Sarah Chen',
        authorInitials: 'SC',
        content: "Yes, let's bump it by 15% to align with the new product launch.",
        mentions: ['usr-003'],
        isResolved: false,
        resolvedAt: null,
        createdAt: '2024-11-20T15:45:00Z',
        replies: [],
      },
    ],
  },
  {
    id: 'cmt-002',
    resourceType: 'variance',
    resourceId: 'acct-5100',
    cellId: 'cell-5100-oct',
    parentId: null,
    authorId: 'usr-004',
    authorName: 'David Kim',
    authorInitials: 'DK',
    content: 'Cloud infra spike due to new product launch. Reserved instances being evaluated.',
    mentions: ['usr-001', 'usr-003'],
    isResolved: true,
    resolvedAt: '2024-11-22T10:00:00Z',
    createdAt: '2024-11-19T16:45:00Z',
    replies: [],
  },
  {
    id: 'cmt-003',
    resourceType: 'scenario',
    resourceId: 'scn-002',
    cellId: null,
    parentId: null,
    authorId: 'usr-002',
    authorName: 'Mike Torres',
    authorInitials: 'MT',
    content: 'This pessimistic case assumes 20% churn. Is that too aggressive?',
    mentions: ['usr-001'],
    isResolved: false,
    resolvedAt: null,
    createdAt: '2024-12-01T09:15:00Z',
    replies: [],
  },
  {
    id: 'cmt-004',
    resourceType: 'forecast',
    resourceId: 'fcst-001',
    cellId: 'cell-rev-nov',
    parentId: null,
    authorId: 'usr-001',
    authorName: 'Sarah Chen',
    authorInitials: 'SC',
    content: 'Revenue looks low here. Did we account for the expansion deals?',
    mentions: [],
    isResolved: false,
    resolvedAt: null,
    createdAt: '2024-12-02T11:20:00Z',
    replies: [],
  },
  {
    id: 'cmt-005',
    resourceType: 'entity',
    resourceId: 'ent-uk',
    cellId: null,
    parentId: null,
    authorId: 'usr-005',
    authorName: 'Alex Rivera',
    authorInitials: 'AR',
    content: 'UK FX rates need to be updated for the latest spot price.',
    mentions: ['usr-002'],
    isResolved: false,
    resolvedAt: null,
    createdAt: '2024-12-03T14:00:00Z',
    replies: [],
  },
  {
    id: 'cmt-006',
    resourceType: 'budget',
    resourceId: 'bgt-001',
    cellId: 'cell-7200-q1',
    parentId: null,
    authorId: 'usr-003',
    authorName: 'Jessica Park',
    authorInitials: 'JP',
    content: 'Travel expenses were cut too deep in Q1.',
    mentions: ['usr-001'],
    isResolved: false,
    resolvedAt: null,
    createdAt: '2024-12-04T10:30:00Z',
    replies: [],
  },
  {
    id: 'cmt-007',
    resourceType: 'report',
    resourceId: 'rpt-bs',
    cellId: null,
    parentId: null,
    authorId: 'usr-004',
    authorName: 'David Kim',
    authorInitials: 'DK',
    content: 'Balance sheet reconciliation is missing for the CA entity.',
    mentions: ['usr-005'],
    isResolved: false,
    resolvedAt: null,
    createdAt: '2024-12-05T08:45:00Z',
    replies: [],
  },
  {
    id: 'cmt-008',
    resourceType: 'variance',
    resourceId: 'acct-6100',
    cellId: 'cell-6100-sep',
    parentId: null,
    authorId: 'usr-002',
    authorName: 'Mike Torres',
    authorInitials: 'MT',
    content: 'Salaries are over budget due to un-forecasted contractor spend.',
    mentions: [],
    isResolved: true,
    resolvedAt: '2024-12-05T16:00:00Z',
    createdAt: '2024-12-04T15:20:00Z',
    replies: [],
  },
  {
    id: 'cmt-009',
    resourceType: 'forecast',
    resourceId: 'fcst-001',
    cellId: null,
    parentId: null,
    authorId: 'usr-001',
    authorName: 'Sarah Chen',
    authorInitials: 'SC',
    content: 'Rolling forecast looks solid. Ready for board review.',
    mentions: ['usr-003', 'usr-004'],
    isResolved: false,
    resolvedAt: null,
    createdAt: '2024-12-06T13:10:00Z',
    replies: [],
  },
  {
    id: 'cmt-010',
    resourceType: 'budget',
    resourceId: 'bgt-003',
    cellId: null,
    parentId: null,
    authorId: 'usr-004',
    authorName: 'David Kim',
    authorInitials: 'DK',
    content: 'Capex for server racks was moved to Q3.',
    mentions: [],
    isResolved: false,
    resolvedAt: null,
    createdAt: '2024-12-07T11:00:00Z',
    replies: [],
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-001',
    title: 'Complete Q4 Variance Commentary',
    description: 'All department heads must submit variance explanations',
    assigneeId: 'usr-003',
    assigneeName: 'Jessica Park',
    dueDate: '2024-12-15',
    priority: 'High',
    status: 'InProgress',
    relatedResourceType: 'variance',
    relatedResourceId: null,
    createdBy: 'usr-001',
    createdAt: '2024-12-01T09:00:00Z',
  },
  {
    id: 'task-002',
    title: 'Review FY2025 Budget Assumptions',
    description: 'Review growth rates and market assumptions',
    assigneeId: 'usr-001',
    assigneeName: 'Sarah Chen',
    dueDate: '2024-12-20',
    priority: 'Critical',
    status: 'Todo',
    relatedResourceType: 'budget',
    relatedResourceId: 'bgt-001',
    createdBy: 'usr-005',
    createdAt: '2024-12-01T10:00:00Z',
  },
  {
    id: 'task-003',
    title: 'Update Headcount Forecast',
    description: 'Reflect latest hiring plan changes',
    assigneeId: 'usr-004',
    assigneeName: 'David Kim',
    dueDate: '2024-12-18',
    priority: 'Medium',
    status: 'Todo',
    relatedResourceType: 'forecast',
    relatedResourceId: 'fcst-001',
    createdBy: 'usr-001',
    createdAt: '2024-12-02T08:00:00Z',
  },
  {
    id: 'task-004',
    title: 'Upload Nov Actuals',
    description: 'Ensure all GL accounts are mapped correctly',
    assigneeId: 'usr-002',
    assigneeName: 'Mike Torres',
    dueDate: '2024-12-05',
    priority: 'High',
    status: 'Done',
    relatedResourceType: 'data',
    relatedResourceId: null,
    createdBy: 'usr-001',
    createdAt: '2024-12-01T14:00:00Z',
  },
  {
    id: 'task-005',
    title: 'Verify EMEA Tax Provisions',
    description: 'Check deferred tax assets calculation',
    assigneeId: 'usr-005',
    assigneeName: 'Alex Rivera',
    dueDate: '2024-12-22',
    priority: 'Medium',
    status: 'Todo',
    relatedResourceType: 'tax',
    relatedResourceId: null,
    createdBy: 'usr-001',
    createdAt: '2024-12-03T11:00:00Z',
  },
  {
    id: 'task-006',
    title: 'Prepare Board Deck Charts',
    description: 'Export waterfall and tornado charts',
    assigneeId: 'usr-003',
    assigneeName: 'Jessica Park',
    dueDate: '2024-12-10',
    priority: 'High',
    status: 'InProgress',
    relatedResourceType: 'report',
    relatedResourceId: null,
    createdBy: 'usr-001',
    createdAt: '2024-12-04T09:00:00Z',
  },
  {
    id: 'task-007',
    title: 'Review Audit Log Spikes',
    description: 'Investigate manual adjustments in Sales OpEx',
    assigneeId: 'usr-001',
    assigneeName: 'Sarah Chen',
    dueDate: '2024-12-12',
    priority: 'Low',
    status: 'Todo',
    relatedResourceType: 'audit',
    relatedResourceId: null,
    createdBy: 'usr-004',
    createdAt: '2024-12-05T15:30:00Z',
  },
  {
    id: 'task-008',
    title: 'Submit Q3 Expense Report',
    description: 'Finalize all travel and entertainment costs',
    assigneeId: 'usr-002',
    assigneeName: 'Mike Torres',
    dueDate: '2024-12-08',
    priority: 'Medium',
    status: 'InProgress',
    relatedResourceType: 'budget',
    relatedResourceId: null,
    createdBy: 'usr-003',
    createdAt: '2024-12-06T10:00:00Z',
  },
  {
    id: 'task-009',
    title: 'Update SaaS Churn Model',
    description: 'Update for the new retention strategy',
    assigneeId: 'usr-004',
    assigneeName: 'David Kim',
    dueDate: '2024-12-25',
    priority: 'High',
    status: 'Todo',
    relatedResourceType: 'sector',
    relatedResourceId: 'saas',
    createdBy: 'usr-001',
    createdAt: '2024-12-07T14:00:00Z',
  },
  {
    id: 'task-010',
    title: 'Finalize FY24 Close',
    description: 'Lock all periods for the fiscal year',
    assigneeId: 'usr-001',
    assigneeName: 'Sarah Chen',
    dueDate: '2025-01-15',
    priority: 'Critical',
    status: 'Todo',
    relatedResourceType: 'period',
    relatedResourceId: null,
    createdBy: 'usr-001',
    createdAt: '2024-12-08T09:00:00Z',
  },
];

export const mockApprovals: ApprovalRequest[] = [
  {
    id: 'apr-001',
    resourceType: 'budget',
    resourceId: 'bgt-002',
    resourceName: 'Q2 2024 Marketing Budget',
    requesterId: 'usr-003',
    requesterName: 'Jessica Park',
    amount: 2450000,
    status: 'Pending',
    submittedAt: '2024-03-15T14:20:00Z',
    reviewedAt: null,
    reviewedBy: null,
    comments: null,
  },
  {
    id: 'apr-002',
    resourceType: 'budget',
    resourceId: 'bgt-001',
    resourceName: 'FY2024 Annual Operating Budget',
    requesterId: 'usr-001',
    requesterName: 'Sarah Chen',
    amount: 54800000,
    status: 'Approved',
    submittedAt: '2023-12-01T12:00:00Z',
    reviewedAt: '2023-12-20T16:30:00Z',
    reviewedBy: 'John Mitchell',
    comments: 'Approved with minor adjustments to T&E budget.',
  },
  {
    id: 'apr-003',
    resourceType: 'forecast',
    resourceId: 'fcst-004',
    resourceName: 'UK Entity Rolling Forecast',
    requesterId: 'usr-002',
    requesterName: 'Mike Torres',
    amount: 12500000,
    status: 'ChangesRequested',
    submittedAt: '2024-11-28T10:00:00Z',
    reviewedAt: '2024-11-30T14:00:00Z',
    reviewedBy: 'Sarah Chen',
    comments: 'Please update FX assumptions and re-submit.',
  },
  {
    id: 'apr-004',
    resourceType: 'scenario',
    resourceId: 'scn-005',
    resourceName: 'High Growth Expansion Case',
    requesterId: 'usr-004',
    requesterName: 'David Kim',
    amount: 8500000,
    status: 'Pending',
    submittedAt: '2024-12-05T11:00:00Z',
    reviewedAt: null,
    reviewedBy: null,
    comments: null,
  },
  {
    id: 'apr-005',
    resourceType: 'budget',
    resourceId: 'bgt-005',
    resourceName: 'APAC 2025 Hiring Plan',
    requesterId: 'usr-005',
    requesterName: 'Alex Rivera',
    amount: 4200000,
    status: 'Rejected',
    submittedAt: '2024-12-01T09:00:00Z',
    reviewedAt: '2024-12-03T15:00:00Z',
    reviewedBy: 'Sarah Chen',
    comments: 'Budget exceeded allocation for the region.',
  },
];

export const mockActivityLog: ActivityLog[] = [
  {
    id: 'act-001',
    userId: 'usr-003',
    userName: 'Jessica Park',
    userEmail: 'jessica.park@example.com',
    action: 'submitted',
    resourceType: 'budget',
    resourceId: 'bgt-002',
    resourceName: 'Q2 2024 Marketing Budget',
    details: null,
    timestamp: '2024-12-02T10:30:00Z',
  },
  {
    id: 'act-002',
    userId: 'usr-001',
    userName: 'Sarah Chen',
    userEmail: 'sarah.chen@example.com',
    action: 'approved',
    resourceType: 'budget',
    resourceId: 'bgt-001',
    resourceName: 'FY2024 Annual Operating Budget',
    details: { oldValue: 'InReview', newValue: 'Approved', field: 'status' },
    timestamp: '2024-12-02T09:00:00Z',
  },
  {
    id: 'act-003',
    userId: 'usr-004',
    userName: 'David Kim',
    userEmail: 'david.kim@example.com',
    action: 'updated',
    resourceType: 'forecast',
    resourceId: 'fcst-001',
    resourceName: 'Q4 2024 Rolling Forecast',
    details: { field: 'headcount', oldValue: 137, newValue: 142 },
    timestamp: '2024-12-01T16:00:00Z',
  },
  {
    id: 'act-004',
    userId: 'usr-003',
    userName: 'Jessica Park',
    userEmail: 'jessica.park@example.com',
    action: 'added commentary',
    resourceType: 'variance',
    resourceId: 'acct-7300',
    resourceName: 'Marketing & Advertising',
    details: null,
    timestamp: '2024-12-01T14:30:00Z',
  },
  {
    id: 'act-005',
    userId: 'usr-001',
    userName: 'Sarah Chen',
    userEmail: 'sarah.chen@example.com',
    action: 'exported',
    resourceType: 'report',
    resourceId: 'rpt-pl',
    resourceName: 'P&L Summary Report',
    details: { newValue: 'PDF', field: 'format' },
    timestamp: '2024-12-01T11:00:00Z',
  },
  {
    id: 'act-006',
    userId: 'usr-002',
    userName: 'Mike Torres',
    userEmail: 'mike.torres@example.com',
    action: 'logged in',
    resourceType: 'session',
    resourceId: 'sess-001',
    resourceName: 'Web Session',
    details: null,
    timestamp: '2024-12-03T08:00:00Z',
  },
  {
    id: 'act-007',
    userId: 'usr-005',
    userName: 'Alex Rivera',
    userEmail: 'alex.rivera@example.com',
    action: 'changed password',
    resourceType: 'user',
    resourceId: 'usr-005',
    resourceName: 'Security Settings',
    details: null,
    timestamp: '2024-12-03T09:15:00Z',
  },
  {
    id: 'act-008',
    userId: 'usr-001',
    userName: 'Sarah Chen',
    userEmail: 'sarah.chen@example.com',
    action: 'deleted',
    resourceType: 'scenario',
    resourceId: 'scn-012',
    resourceName: 'Obsolete Expansion Case',
    details: null,
    timestamp: '2024-12-03T16:45:00Z',
  },
  {
    id: 'act-009',
    userId: 'usr-004',
    userName: 'David Kim',
    userEmail: 'david.kim@example.com',
    action: 'invited user',
    resourceType: 'organization',
    resourceId: 'org-001',
    resourceName: 'New Analyst Account',
    details: { newValue: 'tom.clark@example.com', field: 'email' },
    timestamp: '2024-12-04T10:00:00Z',
  },
  {
    id: 'act-010',
    userId: 'usr-003',
    userName: 'Jessica Park',
    userEmail: 'jessica.park@example.com',
    action: 'locked',
    resourceType: 'budget',
    resourceId: 'bgt-001',
    resourceName: 'FY2024 Final Budget',
    details: { oldValue: 'Approved', newValue: 'Locked', field: 'status' },
    timestamp: '2024-12-04T15:20:00Z',
  },
  {
    id: 'act-011',
    userId: 'usr-002',
    userName: 'Mike Torres',
    userEmail: 'mike.torres@example.com',
    action: 'mapped columns',
    resourceType: 'data',
    resourceId: 'imp-044',
    resourceName: 'Q3 Actuals Import',
    details: null,
    timestamp: '2024-12-05T09:00:00Z',
  },
  {
    id: 'act-012',
    userId: 'usr-001',
    userName: 'Sarah Chen',
    userEmail: 'sarah.chen@example.com',
    action: 'rejected',
    resourceType: 'approval',
    resourceId: 'apr-005',
    resourceName: 'APAC Hiring Plan',
    details: { oldValue: 'Pending', newValue: 'Rejected', field: 'status' },
    timestamp: '2024-12-05T14:30:00Z',
  },
  {
    id: 'act-013',
    userId: 'usr-005',
    userName: 'Alex Rivera',
    userEmail: 'alex.rivera@example.com',
    action: 'updated',
    resourceType: 'entity',
    resourceId: 'ent-uk',
    resourceName: 'UK subsidiary Ltd',
    details: { field: 'currency', oldValue: 'USD', newValue: 'GBP' },
    timestamp: '2024-12-06T11:00:00Z',
  },
  {
    id: 'act-014',
    userId: 'usr-004',
    userName: 'David Kim',
    userEmail: 'david.kim@example.com',
    action: 'commented',
    resourceType: 'variance',
    resourceId: 'acct-6100',
    resourceName: 'Salaries Expense',
    details: null,
    timestamp: '2024-12-06T13:45:00Z',
  },
  {
    id: 'act-015',
    userId: 'usr-001',
    userName: 'Sarah Chen',
    userEmail: 'sarah.chen@example.com',
    action: 'created',
    resourceType: 'report',
    resourceId: 'rpt-99',
    resourceName: 'Consolidated Global P&L',
    details: null,
    timestamp: '2024-12-07T08:30:00Z',
  },
  {
    id: 'act-016',
    userId: 'usr-003',
    userName: 'Jessica Park',
    userEmail: 'jessica.park@example.com',
    action: 'shared',
    resourceType: 'dashboard',
    resourceId: 'dash-main',
    resourceName: 'Executive Dashboard',
    details: { newValue: 'usr-002', field: 'sharedWith' },
    timestamp: '2024-12-07T10:15:00Z',
  },
  {
    id: 'act-017',
    userId: 'usr-002',
    userName: 'Mike Torres',
    userEmail: 'mike.torres@example.com',
    action: 'adjusted',
    resourceType: 'forecast',
    resourceId: 'fcst-001',
    resourceName: 'Q4 Rolling Forecast',
    details: { field: 'revenue_growth', oldValue: '5%', newValue: '7.5%' },
    timestamp: '2024-12-08T11:30:00Z',
  },
  {
    id: 'act-018',
    userId: 'usr-005',
    userName: 'Alex Rivera',
    userEmail: 'alex.rivera@example.com',
    action: 'uploaded',
    resourceType: 'document',
    resourceId: 'doc-101',
    resourceName: 'Tax Audit 2023.pdf',
    details: null,
    timestamp: '2024-12-08T14:00:00Z',
  },
  {
    id: 'act-019',
    userId: 'usr-004',
    userName: 'David Kim',
    userEmail: 'david.kim@example.com',
    action: 'switched entity',
    resourceType: 'context',
    resourceId: 'ent-global',
    resourceName: 'Global View',
    details: null,
    timestamp: '2024-12-09T09:00:00Z',
  },
  {
    id: 'act-020',
    userId: 'usr-001',
    userName: 'Sarah Chen',
    userEmail: 'sarah.chen@example.com',
    action: 'scheduled',
    resourceType: 'report',
    resourceId: 'rpt-001',
    resourceName: 'Weekly Performance Mailer',
    details: { field: 'frequency', newValue: 'weekly' },
    timestamp: '2024-12-09T10:45:00Z',
  },
];
