import type { GLAccount, ImportJob } from '@/types';

export const mockGLAccounts: GLAccount[] = [
  {
    id: 'acct-1000',
    code: '1000',
    name: 'Cash & Cash Equivalents',
    type: 'Asset',
    category: 'Current Assets',
    subCategory: 'Cash',
    parentId: null,
    level: 0,
    sortOrder: 1,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-1100',
    code: '1100',
    name: 'Accounts Receivable',
    type: 'Asset',
    category: 'Current Assets',
    subCategory: 'Receivables',
    parentId: null,
    level: 0,
    sortOrder: 2,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-1200',
    code: '1200',
    name: 'Prepaid Expenses',
    type: 'Asset',
    category: 'Current Assets',
    subCategory: 'Prepaids',
    parentId: null,
    level: 0,
    sortOrder: 3,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-2000',
    code: '2000',
    name: 'Accounts Payable',
    type: 'Liability',
    category: 'Current Liabilities',
    subCategory: 'Payables',
    parentId: null,
    level: 0,
    sortOrder: 4,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-2100',
    code: '2100',
    name: 'Accrued Expenses',
    type: 'Liability',
    category: 'Current Liabilities',
    subCategory: 'Accruals',
    parentId: null,
    level: 0,
    sortOrder: 5,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-3000',
    code: '3000',
    name: 'Retained Earnings',
    type: 'Equity',
    category: 'Equity',
    subCategory: 'Retained Earnings',
    parentId: null,
    level: 0,
    sortOrder: 6,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-4000',
    code: '4000',
    name: 'Revenue',
    type: 'Revenue',
    category: 'Income',
    subCategory: 'Revenue',
    parentId: null,
    level: 0,
    sortOrder: 7,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: true,
    formula: '4100 + 4200 + 4300',
    children: [],
  },
  {
    id: 'acct-4100',
    code: '4100',
    name: 'Subscription Revenue',
    type: 'Revenue',
    category: 'Income',
    subCategory: 'Revenue',
    parentId: 'acct-4000',
    level: 1,
    sortOrder: 8,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-4200',
    code: '4200',
    name: 'Professional Services',
    type: 'Revenue',
    category: 'Income',
    subCategory: 'Revenue',
    parentId: 'acct-4000',
    level: 1,
    sortOrder: 9,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-5000',
    code: '5000',
    name: 'Cost of Goods Sold',
    type: 'COGS',
    category: 'COGS',
    subCategory: 'COGS',
    parentId: null,
    level: 0,
    sortOrder: 10,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: true,
    formula: '5100 + 5200',
    children: [],
  },
  {
    id: 'acct-5100',
    code: '5100',
    name: 'Cloud Infrastructure',
    type: 'COGS',
    category: 'COGS',
    subCategory: 'Infrastructure',
    parentId: 'acct-5000',
    level: 1,
    sortOrder: 11,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-7000',
    code: '7000',
    name: 'Operating Expenses',
    type: 'OpEx',
    category: 'OpEx',
    subCategory: 'Operating Expenses',
    parentId: null,
    level: 0,
    sortOrder: 12,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: true,
    formula: '7100 + 7200 + 7300 + 7400 + 7500',
    children: [],
  },
  {
    id: 'acct-7100',
    code: '7100',
    name: 'Salaries & Wages',
    type: 'OpEx',
    category: 'OpEx',
    subCategory: 'Personnel',
    parentId: 'acct-7000',
    level: 1,
    sortOrder: 13,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-7200',
    code: '7200',
    name: 'Employee Benefits',
    type: 'OpEx',
    category: 'OpEx',
    subCategory: 'Personnel',
    parentId: 'acct-7000',
    level: 1,
    sortOrder: 14,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-7300',
    code: '7300',
    name: 'Marketing & Advertising',
    type: 'OpEx',
    category: 'OpEx',
    subCategory: 'Sales & Marketing',
    parentId: 'acct-7000',
    level: 1,
    sortOrder: 15,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-7400',
    code: '7400',
    name: 'Travel & Entertainment',
    type: 'OpEx',
    category: 'OpEx',
    subCategory: 'Travel',
    parentId: 'acct-7000',
    level: 1,
    sortOrder: 16,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
  {
    id: 'acct-7500',
    code: '7500',
    name: 'Software & Tools',
    type: 'OpEx',
    category: 'OpEx',
    subCategory: 'Technology',
    parentId: 'acct-7000',
    level: 1,
    sortOrder: 17,
    isActive: true,
    entityId: 'ent-1',
    departmentId: null,
    isCalculated: false,
    formula: null,
    children: [],
  },
];

export const mockImportJobs: ImportJob[] = [
  {
    id: 'imp-001',
    filename: 'GL_Export_Q4_2024.xlsx',
    fileType: 'xlsx',
    status: 'Completed',
    rowCount: 1250,
    successCount: 1248,
    errorCount: 2,
    startedAt: '2024-10-01T09:00:00Z',
    completedAt: '2024-10-01T09:02:30Z',
    startedBy: 'usr-001',
    startedByName: 'Sarah Chen',
  },
  {
    id: 'imp-002',
    filename: 'October_Actuals.csv',
    fileType: 'csv',
    status: 'Completed',
    rowCount: 850,
    successCount: 850,
    errorCount: 0,
    startedAt: '2024-11-05T10:00:00Z',
    completedAt: '2024-11-05T10:01:15Z',
    startedBy: 'usr-003',
    startedByName: 'Jessica Park',
  },
  {
    id: 'imp-003',
    filename: 'November_Payroll.xlsx',
    fileType: 'xlsx',
    status: 'Processing',
    rowCount: 500,
    successCount: 0,
    errorCount: 0,
    startedAt: '2024-12-01T08:30:00Z',
    completedAt: null,
    startedBy: 'usr-003',
    startedByName: 'Jessica Park',
  },
  {
    id: 'imp-004',
    filename: 'Q3_Budget_Upload.csv',
    fileType: 'csv',
    status: 'Failed',
    rowCount: 320,
    successCount: 180,
    errorCount: 140,
    startedAt: '2024-09-15T14:00:00Z',
    completedAt: '2024-09-15T14:00:45Z',
    startedBy: 'usr-004',
    startedByName: 'David Kim',
  },
];
