import type { Forecast, ForecastDriver } from '@/types';

export const forecasts: Forecast[] = [
  {
    id: 'fcst-001',
    name: 'Q4 2024 Rolling Forecast',
    description:
      'Rolling 12-month forecast incorporating latest actuals and revised growth assumptions.',
    type: 'Rolling',
    baseBudgetId: 'bgt-001',
    baseBudgetName: 'FY2024 Annual Operating Budget',
    status: 'Completed',
    rollingWindowMonths: 12,
    confidenceLevel: 'High',
    createdBy: 'usr-001',
    createdByName: 'Sarah Chen',
    lastUpdated: '2024-11-30T16:00:00Z',
    createdAt: '2024-10-01T08:00:00Z',
  },
  {
    id: 'fcst-002',
    name: 'Q3 2024 Quarterly Forecast',
    description: 'Quarterly forecast for Q3 with updated revenue projections from the sales team.',
    type: 'Quarterly',
    baseBudgetId: 'bgt-001',
    baseBudgetName: 'FY2024 Annual Operating Budget',
    status: 'Completed',
    rollingWindowMonths: 3,
    confidenceLevel: 'High',
    createdBy: 'usr-003',
    createdByName: 'Jessica Park',
    lastUpdated: '2024-07-15T14:00:00Z',
    createdAt: '2024-06-15T09:00:00Z',
  },
  {
    id: 'fcst-003',
    name: 'FY2025 Preliminary Forecast',
    description: 'Early-stage forecast for FY2025 based on preliminary guidance and market trends.',
    type: 'Annual',
    baseBudgetId: 'bgt-001',
    baseBudgetName: 'FY2024 Annual Operating Budget',
    status: 'Draft',
    rollingWindowMonths: 12,
    confidenceLevel: 'Low',
    createdBy: 'usr-001',
    createdByName: 'Sarah Chen',
    lastUpdated: '2024-11-20T11:00:00Z',
    createdAt: '2024-11-01T08:00:00Z',
  },
  {
    id: 'fcst-004',
    name: 'UK Entity Rolling Forecast',
    description:
      '12-month rolling forecast specific to UK subsidiary with local currency adjustments.',
    type: 'Rolling',
    baseBudgetId: 'bgt-001',
    baseBudgetName: 'FY2024 Annual Operating Budget',
    status: 'InProgress',
    rollingWindowMonths: 12,
    confidenceLevel: 'Medium',
    createdBy: 'usr-004',
    createdByName: 'David Kim',
    lastUpdated: '2024-11-28T09:30:00Z',
    createdAt: '2024-09-01T10:00:00Z',
  },
  {
    id: 'fcst-005',
    name: 'DE Entity Rolling Forecast',
    description: '12-month rolling forecast for German subsidiary with IFRS adjustments.',
    type: 'Rolling',
    baseBudgetId: 'bgt-001',
    baseBudgetName: 'FY2024 Annual Operating Budget',
    status: 'InProgress',
    rollingWindowMonths: 12,
    confidenceLevel: 'Medium',
    createdBy: 'usr-005',
    createdByName: 'Emily Wu',
    lastUpdated: '2024-11-27T15:00:00Z',
    createdAt: '2024-09-01T10:00:00Z',
  },
];

export const forecastDrivers: ForecastDriver[] = [
  {
    id: 'drv-001',
    name: 'Headcount Growth',
    description: 'Planned headcount additions across all departments',
    driverType: 'Headcount',
    baseValue: 137,
    currentValue: 145,
    unit: 'FTE',
    affectedAccountIds: ['acct-7100', 'acct-7200'],
    formula: 'base_headcount + new_hires - attrition',
  },
  {
    id: 'drv-002',
    name: 'Subscription Revenue Growth',
    description: 'Expected growth rate for subscription revenue',
    driverType: 'Revenue',
    baseValue: 15,
    currentValue: 18,
    unit: '%',
    affectedAccountIds: ['acct-4100'],
    formula: 'prior_period_revenue * (1 + growth_rate)',
  },
  {
    id: 'drv-003',
    name: 'Pricing Adjustment',
    description: 'Annual price increase assumption for subscription tiers',
    driverType: 'Price',
    baseValue: 5,
    currentValue: 7,
    unit: '%',
    affectedAccountIds: ['acct-4100', 'acct-4200'],
    formula: 'base_price * (1 + price_increase_pct)',
  },
  {
    id: 'drv-004',
    name: 'Deal Volume',
    description: 'Expected number of new deals closed per quarter',
    driverType: 'Volume',
    baseValue: 40,
    currentValue: 52,
    unit: 'Deals',
    affectedAccountIds: ['acct-4100', 'acct-4200'],
    formula: 'deals_per_rep * rep_count * close_rate',
  },
  {
    id: 'drv-005',
    name: 'FX Rate Impact',
    description: 'Foreign exchange rate assumptions for GBP and EUR entities',
    driverType: 'Rate',
    baseValue: 1.27,
    currentValue: 1.24,
    unit: 'USD/GBP',
    affectedAccountIds: ['acct-4100', 'acct-4200', 'acct-5100'],
    formula: 'local_currency_amount * fx_rate',
  },
];

export function getForecastById(id: string): Forecast | undefined {
  return forecasts.find((f) => f.id === id);
}

export function getForecastsByStatus(status: Forecast['status']): Forecast[] {
  return forecasts.filter((f) => f.status === status);
}
