import type { GLEntry } from '@/types';
import Decimal from 'decimal.js';

interface RawGLEntry {
  readonly id: string;
  readonly accountCode: string;
  readonly accountName: string;
  readonly description: string;
  readonly debit: number;
  readonly credit: number;
  readonly postDate: string;
  readonly fiscalPeriod: string;
  readonly department: string;
  readonly entity: string;
  readonly journalId: string;
  readonly journalLine: number;
  readonly source: string;
}

function toGLEntry(raw: RawGLEntry): GLEntry {
  const netChange = new Decimal(raw.credit).minus(raw.debit).toNumber();
  return {
    ...raw,
    accountId: raw.id,
    period: raw.fiscalPeriod,
    periodName: raw.fiscalPeriod,
    netChange,
    amount: new Decimal(raw.debit).plus(raw.credit).toNumber(),
    date: raw.postDate,
    reference: raw.journalId,
    entityId: raw.entity,
    departmentId: raw.department,
    currency: 'USD',
  };
}

export interface TrialBalanceItem {
  readonly accountCode: string;
  readonly accountName: string;
  readonly totalDebit: number;
  readonly totalCredit: number;
  readonly netBalance: number;
  readonly entryCount: number;
}

const rawGLEntries: RawGLEntry[] = [
  // === Revenue Entries (4100 - Subscription) ===
  {
    id: 'gl-0001',
    accountCode: '4100',
    accountName: 'Subscription Revenue',
    description: 'Jan SaaS subscriptions - Enterprise',
    debit: 0,
    credit: 850_000,
    postDate: '2024-01-15',
    fiscalPeriod: '2024-01',
    department: 'Sales',
    entity: 'US',
    journalId: 'JRNL-2024-001',
    journalLine: 1,
    source: 'Billing System',
  },
  {
    id: 'gl-0002',
    accountCode: '4100',
    accountName: 'Subscription Revenue',
    description: 'Jan SaaS subscriptions - SMB',
    debit: 0,
    credit: 480_000,
    postDate: '2024-01-15',
    fiscalPeriod: '2024-01',
    department: 'Sales',
    entity: 'US',
    journalId: 'JRNL-2024-001',
    journalLine: 2,
    source: 'Billing System',
  },
  {
    id: 'gl-0003',
    accountCode: '4100',
    accountName: 'Subscription Revenue',
    description: 'Jan SaaS subscriptions - Enterprise UK',
    debit: 0,
    credit: 320_000,
    postDate: '2024-01-15',
    fiscalPeriod: '2024-01',
    department: 'Sales',
    entity: 'UK',
    journalId: 'JRNL-2024-002',
    journalLine: 1,
    source: 'Billing System',
  },
  {
    id: 'gl-0004',
    accountCode: '4100',
    accountName: 'Subscription Revenue',
    description: 'Feb SaaS subscriptions - Enterprise',
    debit: 0,
    credit: 870_000,
    postDate: '2024-02-15',
    fiscalPeriod: '2024-02',
    department: 'Sales',
    entity: 'US',
    journalId: 'JRNL-2024-003',
    journalLine: 1,
    source: 'Billing System',
  },
  {
    id: 'gl-0005',
    accountCode: '4100',
    accountName: 'Subscription Revenue',
    description: 'Feb SaaS subscriptions - SMB',
    debit: 0,
    credit: 490_000,
    postDate: '2024-02-15',
    fiscalPeriod: '2024-02',
    department: 'Sales',
    entity: 'US',
    journalId: 'JRNL-2024-003',
    journalLine: 2,
    source: 'Billing System',
  },
  {
    id: 'gl-0006',
    accountCode: '4100',
    accountName: 'Subscription Revenue',
    description: 'Mar SaaS subscriptions - Enterprise',
    debit: 0,
    credit: 920_000,
    postDate: '2024-03-15',
    fiscalPeriod: '2024-03',
    department: 'Sales',
    entity: 'US',
    journalId: 'JRNL-2024-005',
    journalLine: 1,
    source: 'Billing System',
  },
  {
    id: 'gl-0007',
    accountCode: '4100',
    accountName: 'Subscription Revenue',
    description: 'Mar SaaS subscriptions - SMB + DE',
    debit: 0,
    credit: 580_000,
    postDate: '2024-03-15',
    fiscalPeriod: '2024-03',
    department: 'Sales',
    entity: 'DE',
    journalId: 'JRNL-2024-005',
    journalLine: 2,
    source: 'Billing System',
  },

  // === Revenue Entries (4200 - Professional Services) ===
  {
    id: 'gl-0008',
    accountCode: '4200',
    accountName: 'Professional Services Revenue',
    description: 'Consulting engagement - Acme Corp',
    debit: 0,
    credit: 120_000,
    postDate: '2024-01-20',
    fiscalPeriod: '2024-01',
    department: 'Sales',
    entity: 'US',
    journalId: 'JRNL-2024-001',
    journalLine: 3,
    source: 'PS System',
  },
  {
    id: 'gl-0009',
    accountCode: '4200',
    accountName: 'Professional Services Revenue',
    description: 'Implementation services - Beta Inc',
    debit: 0,
    credit: 95_000,
    postDate: '2024-01-25',
    fiscalPeriod: '2024-01',
    department: 'Sales',
    entity: 'US',
    journalId: 'JRNL-2024-001',
    journalLine: 4,
    source: 'PS System',
  },
  {
    id: 'gl-0010',
    accountCode: '4200',
    accountName: 'Professional Services Revenue',
    description: 'Training & onboarding - Q1 cohort',
    debit: 0,
    credit: 85_000,
    postDate: '2024-02-10',
    fiscalPeriod: '2024-02',
    department: 'Sales',
    entity: 'US',
    journalId: 'JRNL-2024-003',
    journalLine: 3,
    source: 'PS System',
  },
  {
    id: 'gl-0011',
    accountCode: '4200',
    accountName: 'Professional Services Revenue',
    description: 'Consulting - Delta Partners UK',
    debit: 0,
    credit: 110_000,
    postDate: '2024-03-05',
    fiscalPeriod: '2024-03',
    department: 'Sales',
    entity: 'UK',
    journalId: 'JRNL-2024-005',
    journalLine: 3,
    source: 'PS System',
  },
  {
    id: 'gl-0012',
    accountCode: '4200',
    accountName: 'Professional Services Revenue',
    description: 'Migration services - existing clients',
    debit: 0,
    credit: 140_000,
    postDate: '2024-03-20',
    fiscalPeriod: '2024-03',
    department: 'Sales',
    entity: 'US',
    journalId: 'JRNL-2024-005',
    journalLine: 4,
    source: 'PS System',
  },

  // === COGS Entries (5100 - Cloud Infrastructure) ===
  {
    id: 'gl-0013',
    accountCode: '5100',
    accountName: 'Cloud Infrastructure',
    description: 'AWS hosting - production',
    debit: 180_000,
    credit: 0,
    postDate: '2024-01-05',
    fiscalPeriod: '2024-01',
    department: 'Operations',
    entity: 'US',
    journalId: 'JRNL-2024-006',
    journalLine: 1,
    source: 'AWS Billing',
  },
  {
    id: 'gl-0014',
    accountCode: '5100',
    accountName: 'Cloud Infrastructure',
    description: 'AWS hosting - staging/dev',
    debit: 55_000,
    credit: 0,
    postDate: '2024-01-05',
    fiscalPeriod: '2024-01',
    department: 'Engineering',
    entity: 'US',
    journalId: 'JRNL-2024-006',
    journalLine: 2,
    source: 'AWS Billing',
  },
  {
    id: 'gl-0015',
    accountCode: '5100',
    accountName: 'Cloud Infrastructure',
    description: 'Azure hosting - UK region',
    debit: 85_000,
    credit: 0,
    postDate: '2024-01-05',
    fiscalPeriod: '2024-01',
    department: 'Operations',
    entity: 'UK',
    journalId: 'JRNL-2024-007',
    journalLine: 1,
    source: 'Azure Billing',
  },
  {
    id: 'gl-0016',
    accountCode: '5100',
    accountName: 'Cloud Infrastructure',
    description: 'GCP hosting - DE region',
    debit: 42_000,
    credit: 0,
    postDate: '2024-01-05',
    fiscalPeriod: '2024-01',
    department: 'Operations',
    entity: 'DE',
    journalId: 'JRNL-2024-008',
    journalLine: 1,
    source: 'GCP Billing',
  },
  {
    id: 'gl-0017',
    accountCode: '5100',
    accountName: 'Cloud Infrastructure',
    description: 'AWS hosting - Feb production',
    debit: 185_000,
    credit: 0,
    postDate: '2024-02-05',
    fiscalPeriod: '2024-02',
    department: 'Operations',
    entity: 'US',
    journalId: 'JRNL-2024-009',
    journalLine: 1,
    source: 'AWS Billing',
  },
  {
    id: 'gl-0018',
    accountCode: '5100',
    accountName: 'Cloud Infrastructure',
    description: 'CDN & bandwidth costs',
    debit: 35_000,
    credit: 0,
    postDate: '2024-02-05',
    fiscalPeriod: '2024-02',
    department: 'Operations',
    entity: 'US',
    journalId: 'JRNL-2024-009',
    journalLine: 2,
    source: 'Cloudflare',
  },

  // === COGS Entries (5200 - Direct Labor) ===
  {
    id: 'gl-0019',
    accountCode: '5200',
    accountName: 'Direct Labor',
    description: 'Support team salaries - Jan',
    debit: 210_000,
    credit: 0,
    postDate: '2024-01-31',
    fiscalPeriod: '2024-01',
    department: 'Operations',
    entity: 'US',
    journalId: 'JRNL-2024-010',
    journalLine: 1,
    source: 'Payroll',
  },
  {
    id: 'gl-0020',
    accountCode: '5200',
    accountName: 'Direct Labor',
    description: 'Support team salaries - Feb',
    debit: 215_000,
    credit: 0,
    postDate: '2024-02-29',
    fiscalPeriod: '2024-02',
    department: 'Operations',
    entity: 'US',
    journalId: 'JRNL-2024-011',
    journalLine: 1,
    source: 'Payroll',
  },

  // === OpEx Entries (7100 - Salaries & Wages) ===
  {
    id: 'gl-0021',
    accountCode: '7100',
    accountName: 'Salaries & Wages',
    description: 'Engineering salaries - Jan',
    debit: 820_000,
    credit: 0,
    postDate: '2024-01-31',
    fiscalPeriod: '2024-01',
    department: 'Engineering',
    entity: 'US',
    journalId: 'JRNL-2024-010',
    journalLine: 2,
    source: 'Payroll',
  },
  {
    id: 'gl-0022',
    accountCode: '7100',
    accountName: 'Salaries & Wages',
    description: 'Sales salaries & commissions - Jan',
    debit: 450_000,
    credit: 0,
    postDate: '2024-01-31',
    fiscalPeriod: '2024-01',
    department: 'Sales',
    entity: 'US',
    journalId: 'JRNL-2024-010',
    journalLine: 3,
    source: 'Payroll',
  },
  {
    id: 'gl-0023',
    accountCode: '7100',
    accountName: 'Salaries & Wages',
    description: 'Marketing salaries - Jan',
    debit: 180_000,
    credit: 0,
    postDate: '2024-01-31',
    fiscalPeriod: '2024-01',
    department: 'Marketing',
    entity: 'US',
    journalId: 'JRNL-2024-010',
    journalLine: 4,
    source: 'Payroll',
  },
  {
    id: 'gl-0024',
    accountCode: '7100',
    accountName: 'Salaries & Wages',
    description: 'Finance & Admin salaries - Jan',
    debit: 160_000,
    credit: 0,
    postDate: '2024-01-31',
    fiscalPeriod: '2024-01',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-010',
    journalLine: 5,
    source: 'Payroll',
  },
  {
    id: 'gl-0025',
    accountCode: '7100',
    accountName: 'Salaries & Wages',
    description: 'Engineering salaries - Feb',
    debit: 825_000,
    credit: 0,
    postDate: '2024-02-29',
    fiscalPeriod: '2024-02',
    department: 'Engineering',
    entity: 'US',
    journalId: 'JRNL-2024-011',
    journalLine: 2,
    source: 'Payroll',
  },
  {
    id: 'gl-0026',
    accountCode: '7100',
    accountName: 'Salaries & Wages',
    description: 'Engineering salaries - UK team',
    debit: 280_000,
    credit: 0,
    postDate: '2024-01-31',
    fiscalPeriod: '2024-01',
    department: 'Engineering',
    entity: 'UK',
    journalId: 'JRNL-2024-012',
    journalLine: 1,
    source: 'Payroll',
  },

  // === OpEx Entries (7200 - Employee Benefits) ===
  {
    id: 'gl-0027',
    accountCode: '7200',
    accountName: 'Employee Benefits',
    description: 'Health insurance premiums - Jan',
    debit: 145_000,
    credit: 0,
    postDate: '2024-01-15',
    fiscalPeriod: '2024-01',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-013',
    journalLine: 1,
    source: 'Benefits Admin',
  },
  {
    id: 'gl-0028',
    accountCode: '7200',
    accountName: 'Employee Benefits',
    description: '401k matching - Jan',
    debit: 85_000,
    credit: 0,
    postDate: '2024-01-31',
    fiscalPeriod: '2024-01',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-013',
    journalLine: 2,
    source: 'Payroll',
  },
  {
    id: 'gl-0029',
    accountCode: '7200',
    accountName: 'Employee Benefits',
    description: 'Health insurance premiums - Feb',
    debit: 148_000,
    credit: 0,
    postDate: '2024-02-15',
    fiscalPeriod: '2024-02',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-014',
    journalLine: 1,
    source: 'Benefits Admin',
  },

  // === OpEx Entries (7300 - Marketing & Advertising) ===
  {
    id: 'gl-0030',
    accountCode: '7300',
    accountName: 'Marketing & Advertising',
    description: 'Google Ads - Jan campaign',
    debit: 185_000,
    credit: 0,
    postDate: '2024-01-10',
    fiscalPeriod: '2024-01',
    department: 'Marketing',
    entity: 'US',
    journalId: 'JRNL-2024-015',
    journalLine: 1,
    source: 'Ad Platforms',
  },
  {
    id: 'gl-0031',
    accountCode: '7300',
    accountName: 'Marketing & Advertising',
    description: 'LinkedIn Ads - Jan',
    debit: 95_000,
    credit: 0,
    postDate: '2024-01-10',
    fiscalPeriod: '2024-01',
    department: 'Marketing',
    entity: 'US',
    journalId: 'JRNL-2024-015',
    journalLine: 2,
    source: 'Ad Platforms',
  },
  {
    id: 'gl-0032',
    accountCode: '7300',
    accountName: 'Marketing & Advertising',
    description: 'Content production - Q1',
    debit: 120_000,
    credit: 0,
    postDate: '2024-01-20',
    fiscalPeriod: '2024-01',
    department: 'Marketing',
    entity: 'US',
    journalId: 'JRNL-2024-015',
    journalLine: 3,
    source: 'Vendor Invoices',
  },
  {
    id: 'gl-0033',
    accountCode: '7300',
    accountName: 'Marketing & Advertising',
    description: 'Trade show - SaaSConf 2024',
    debit: 250_000,
    credit: 0,
    postDate: '2024-03-15',
    fiscalPeriod: '2024-03',
    department: 'Marketing',
    entity: 'US',
    journalId: 'JRNL-2024-016',
    journalLine: 1,
    source: 'Event Management',
  },
  {
    id: 'gl-0034',
    accountCode: '7300',
    accountName: 'Marketing & Advertising',
    description: 'Google Ads - Feb campaign',
    debit: 175_000,
    credit: 0,
    postDate: '2024-02-10',
    fiscalPeriod: '2024-02',
    department: 'Marketing',
    entity: 'US',
    journalId: 'JRNL-2024-017',
    journalLine: 1,
    source: 'Ad Platforms',
  },

  // === OpEx Entries (7500 - Software & Tools) ===
  {
    id: 'gl-0035',
    accountCode: '7500',
    accountName: 'Software & Tools',
    description: 'Salesforce annual license',
    debit: 95_000,
    credit: 0,
    postDate: '2024-01-01',
    fiscalPeriod: '2024-01',
    department: 'Sales',
    entity: 'US',
    journalId: 'JRNL-2024-018',
    journalLine: 1,
    source: 'Software Procurement',
  },
  {
    id: 'gl-0036',
    accountCode: '7500',
    accountName: 'Software & Tools',
    description: 'GitHub Enterprise - Jan',
    debit: 22_000,
    credit: 0,
    postDate: '2024-01-05',
    fiscalPeriod: '2024-01',
    department: 'Engineering',
    entity: 'US',
    journalId: 'JRNL-2024-018',
    journalLine: 2,
    source: 'Software Procurement',
  },
  {
    id: 'gl-0037',
    accountCode: '7500',
    accountName: 'Software & Tools',
    description: 'Datadog monitoring - Jan',
    debit: 35_000,
    credit: 0,
    postDate: '2024-01-05',
    fiscalPeriod: '2024-01',
    department: 'Engineering',
    entity: 'US',
    journalId: 'JRNL-2024-018',
    journalLine: 3,
    source: 'Software Procurement',
  },
  {
    id: 'gl-0038',
    accountCode: '7500',
    accountName: 'Software & Tools',
    description: 'Slack & Zoom - Jan',
    debit: 28_000,
    credit: 0,
    postDate: '2024-01-05',
    fiscalPeriod: '2024-01',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-018',
    journalLine: 4,
    source: 'Software Procurement',
  },
  {
    id: 'gl-0039',
    accountCode: '7500',
    accountName: 'Software & Tools',
    description: 'New AI tools license - annual',
    debit: 180_000,
    credit: 0,
    postDate: '2024-03-01',
    fiscalPeriod: '2024-03',
    department: 'Engineering',
    entity: 'US',
    journalId: 'JRNL-2024-019',
    journalLine: 1,
    source: 'Software Procurement',
  },

  // === OpEx Entries (7400 - Travel & Entertainment) ===
  {
    id: 'gl-0040',
    accountCode: '7400',
    accountName: 'Travel & Entertainment',
    description: 'Customer visits - Q1',
    debit: 45_000,
    credit: 0,
    postDate: '2024-01-25',
    fiscalPeriod: '2024-01',
    department: 'Sales',
    entity: 'US',
    journalId: 'JRNL-2024-020',
    journalLine: 1,
    source: 'Expense Reports',
  },
  {
    id: 'gl-0041',
    accountCode: '7400',
    accountName: 'Travel & Entertainment',
    description: 'Team offsite - Engineering',
    debit: 35_000,
    credit: 0,
    postDate: '2024-02-10',
    fiscalPeriod: '2024-02',
    department: 'Engineering',
    entity: 'US',
    journalId: 'JRNL-2024-021',
    journalLine: 1,
    source: 'Expense Reports',
  },
  {
    id: 'gl-0042',
    accountCode: '7400',
    accountName: 'Travel & Entertainment',
    description: 'Client entertainment - Q1',
    debit: 28_000,
    credit: 0,
    postDate: '2024-03-15',
    fiscalPeriod: '2024-03',
    department: 'Sales',
    entity: 'US',
    journalId: 'JRNL-2024-022',
    journalLine: 1,
    source: 'Expense Reports',
  },

  // === OpEx Entries (7600 - Rent & Facilities) ===
  {
    id: 'gl-0043',
    accountCode: '7600',
    accountName: 'Rent & Facilities',
    description: 'Office rent - SF HQ Jan',
    debit: 120_000,
    credit: 0,
    postDate: '2024-01-01',
    fiscalPeriod: '2024-01',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-023',
    journalLine: 1,
    source: 'Property Management',
  },
  {
    id: 'gl-0044',
    accountCode: '7600',
    accountName: 'Rent & Facilities',
    description: 'Office rent - London Jan',
    debit: 65_000,
    credit: 0,
    postDate: '2024-01-01',
    fiscalPeriod: '2024-01',
    department: 'Finance',
    entity: 'UK',
    journalId: 'JRNL-2024-024',
    journalLine: 1,
    source: 'Property Management',
  },
  {
    id: 'gl-0045',
    accountCode: '7600',
    accountName: 'Rent & Facilities',
    description: 'Office utilities & maintenance - Jan',
    debit: 22_000,
    credit: 0,
    postDate: '2024-01-10',
    fiscalPeriod: '2024-01',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-023',
    journalLine: 2,
    source: 'Utilities',
  },

  // === OpEx Entries (7700 - Professional Services) ===
  {
    id: 'gl-0046',
    accountCode: '7700',
    accountName: 'Professional Services',
    description: 'Legal retainer - Q1',
    debit: 60_000,
    credit: 0,
    postDate: '2024-01-05',
    fiscalPeriod: '2024-01',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-025',
    journalLine: 1,
    source: 'Legal Billing',
  },
  {
    id: 'gl-0047',
    accountCode: '7700',
    accountName: 'Professional Services',
    description: 'Audit fees - FY2023',
    debit: 95_000,
    credit: 0,
    postDate: '2024-02-15',
    fiscalPeriod: '2024-02',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-026',
    journalLine: 1,
    source: 'Audit Firm',
  },
  {
    id: 'gl-0048',
    accountCode: '7700',
    accountName: 'Professional Services',
    description: 'Recruitment fees - Q1 hires',
    debit: 75_000,
    credit: 0,
    postDate: '2024-03-10',
    fiscalPeriod: '2024-03',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-027',
    journalLine: 1,
    source: 'HR Invoices',
  },

  // === OpEx Entries (7800 - Depreciation & Amortization) ===
  {
    id: 'gl-0049',
    accountCode: '7800',
    accountName: 'Depreciation & Amortization',
    description: 'Equipment depreciation - Jan',
    debit: 85_000,
    credit: 0,
    postDate: '2024-01-31',
    fiscalPeriod: '2024-01',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-028',
    journalLine: 1,
    source: 'Fixed Assets',
  },
  {
    id: 'gl-0050',
    accountCode: '7800',
    accountName: 'Depreciation & Amortization',
    description: 'Software amortization - Jan',
    debit: 75_000,
    credit: 0,
    postDate: '2024-01-31',
    fiscalPeriod: '2024-01',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-028',
    journalLine: 2,
    source: 'Fixed Assets',
  },
  {
    id: 'gl-0051',
    accountCode: '7800',
    accountName: 'Depreciation & Amortization',
    description: 'Equipment depreciation - Feb',
    debit: 85_000,
    credit: 0,
    postDate: '2024-02-29',
    fiscalPeriod: '2024-02',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-029',
    journalLine: 1,
    source: 'Fixed Assets',
  },
  {
    id: 'gl-0052',
    accountCode: '7800',
    accountName: 'Depreciation & Amortization',
    description: 'Equipment depreciation - Mar',
    debit: 85_000,
    credit: 0,
    postDate: '2024-03-31',
    fiscalPeriod: '2024-03',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-030',
    journalLine: 1,
    source: 'Fixed Assets',
  },

  // === OpEx Entries (7900 - Other) ===
  {
    id: 'gl-0053',
    accountCode: '7900',
    accountName: 'Other Operating Expenses',
    description: 'Office supplies & sundry - Q1',
    debit: 18_000,
    credit: 0,
    postDate: '2024-01-15',
    fiscalPeriod: '2024-01',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-031',
    journalLine: 1,
    source: 'Procurement',
  },
  {
    id: 'gl-0054',
    accountCode: '7900',
    accountName: 'Other Operating Expenses',
    description: 'Insurance premiums - Q1',
    debit: 65_000,
    credit: 0,
    postDate: '2024-01-01',
    fiscalPeriod: '2024-01',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-031',
    journalLine: 2,
    source: 'Insurance',
  },
  {
    id: 'gl-0055',
    accountCode: '7900',
    accountName: 'Other Operating Expenses',
    description: 'Training & development - Q1',
    debit: 42_000,
    credit: 0,
    postDate: '2024-02-20',
    fiscalPeriod: '2024-02',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-032',
    journalLine: 1,
    source: 'HR Invoices',
  },
  {
    id: 'gl-0056',
    accountCode: '7900',
    accountName: 'Other Operating Expenses',
    description: 'Bank fees & merchant charges - Q1',
    debit: 28_000,
    credit: 0,
    postDate: '2024-03-31',
    fiscalPeriod: '2024-03',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-033',
    journalLine: 1,
    source: 'Bank Statements',
  },

  // === Equity Entry (3000 - Retained Earnings) to balance trial balance ===
  {
    id: 'gl-0057',
    accountCode: '3000',
    accountName: 'Retained Earnings',
    description: 'Q1 Net loss closing entry',
    debit: 0,
    credit: 1_253_000,
    postDate: '2024-03-31',
    fiscalPeriod: '2024-03',
    department: 'Finance',
    entity: 'US',
    journalId: 'JRNL-2024-034',
    journalLine: 1,
    source: 'Period Close',
  },
];

export function computeTrialBalance(): TrialBalanceItem[] {
  const grouped = new Map<string, { debit: Decimal; credit: Decimal; count: number }>();

  for (const entry of rawGLEntries) {
    const key = `${entry.accountCode}::${entry.accountName}`;
    const existing = grouped.get(key) ?? {
      debit: new Decimal(0),
      credit: new Decimal(0),
      count: 0,
    };
    existing.debit = existing.debit.plus(entry.debit);
    existing.credit = existing.credit.plus(entry.credit);
    existing.count++;
    grouped.set(key, existing);
  }

  return Array.from(grouped.entries()).map(([key, data]) => {
    const [accountCode, accountName] = key.split('::');
    return {
      accountCode: accountCode!,
      accountName: accountName!,
      totalDebit: data.debit.toNumber(),
      totalCredit: data.credit.toNumber(),
      netBalance: data.debit.minus(data.credit).toNumber(),
      entryCount: data.count,
    };
  });
}

export const mockGLEntries: GLEntry[] = rawGLEntries.map(toGLEntry);
export const mockTrialBalance: TrialBalanceItem[] = computeTrialBalance();

export function getGLEntriesByAccount(accountCode: string): GLEntry[] {
  return mockGLEntries.filter((e) => e.accountCode === accountCode);
}

export function getGLEntriesByPeriod(period: string): GLEntry[] {
  return mockGLEntries.filter((e) => e.period === period);
}
