import type { User, Department, Entity } from '@/types';

export const users: User[] = [
  {
    id: 'usr-001',
    email: 'sarah.chen@finplan.com',
    firstName: 'Sarah',
    lastName: 'Chen',
    avatarUrl: null,
    role: 'FP&A_Manager',
    departmentId: 'dept-finance',
    departmentName: 'Finance & Accounting',
    entityId: 'ent-us',
    status: 'Active',
    lastLoginAt: '2024-12-02T08:30:00Z',
    mfaEnabled: true,
    permissions: ['budget:write', 'forecast:write', 'report:read', 'admin:users'],
  },
  {
    id: 'usr-002',
    email: 'mike.torres@finplan.com',
    firstName: 'Mike',
    lastName: 'Torres',
    avatarUrl: null,
    role: 'Analyst',
    departmentId: 'dept-finance',
    departmentName: 'Finance & Accounting',
    entityId: 'ent-us',
    status: 'Active',
    lastLoginAt: '2024-12-01T14:15:00Z',
    mfaEnabled: true,
    permissions: ['budget:read', 'forecast:read', 'data:enter'],
  },
  {
    id: 'usr-003',
    email: 'jessica.park@finplan.com',
    firstName: 'Jessica',
    lastName: 'Park',
    avatarUrl: null,
    role: 'Analyst',
    departmentId: 'dept-finance',
    departmentName: 'Finance & Accounting',
    entityId: 'ent-us',
    status: 'Active',
    lastLoginAt: '2024-12-02T09:00:00Z',
    mfaEnabled: true,
    permissions: ['budget:read', 'forecast:read', 'data:enter', 'report:create'],
  },
  {
    id: 'usr-004',
    email: 'david.kim@finplan.com',
    firstName: 'David',
    lastName: 'Kim',
    avatarUrl: null,
    role: 'Analyst',
    departmentId: 'dept-finance',
    departmentName: 'Finance & Accounting',
    entityId: 'ent-uk',
    status: 'Active',
    lastLoginAt: '2024-11-30T11:45:00Z',
    mfaEnabled: false,
    permissions: ['budget:read', 'data:enter'],
  },
  {
    id: 'usr-005',
    email: 'emily.wu@finplan.com',
    firstName: 'Emily',
    lastName: 'Wu',
    avatarUrl: null,
    role: 'Analyst',
    departmentId: 'dept-finance',
    departmentName: 'Finance & Accounting',
    entityId: 'ent-de',
    status: 'Active',
    lastLoginAt: '2024-12-02T07:30:00Z',
    mfaEnabled: false,
    permissions: ['budget:read', 'forecast:read', 'data:enter', 'report:create'],
  },
  {
    id: 'usr-006',
    email: 'tom.baker@finplan.com',
    firstName: 'Tom',
    lastName: 'Baker',
    avatarUrl: null,
    role: 'Department_Head',
    departmentId: 'dept-sales',
    departmentName: 'Sales',
    entityId: 'ent-us',
    status: 'Active',
    lastLoginAt: '2024-12-01T16:00:00Z',
    mfaEnabled: false,
    permissions: ['budget:view-dept', 'forecast:view-dept'],
  },
  {
    id: 'usr-007',
    email: 'lisa.wong@finplan.com',
    firstName: 'Lisa',
    lastName: 'Wong',
    avatarUrl: null,
    role: 'Department_Head',
    departmentId: 'dept-engineering',
    departmentName: 'Engineering',
    entityId: 'ent-us',
    status: 'Active',
    lastLoginAt: '2024-12-02T10:30:00Z',
    mfaEnabled: true,
    permissions: ['budget:view-dept', 'forecast:view-dept'],
  },
  {
    id: 'usr-008',
    email: 'john.mitchell@finplan.com',
    firstName: 'John',
    lastName: 'Mitchell',
    avatarUrl: null,
    role: 'Admin',
    departmentId: 'dept-finance',
    departmentName: 'Finance & Accounting',
    entityId: 'ent-us',
    status: 'Active',
    lastLoginAt: '2024-12-02T06:00:00Z',
    mfaEnabled: true,
    permissions: ['admin:*', 'budget:*', 'forecast:*', 'report:*', 'data:*'],
  },
];

export const departments: Department[] = [
  {
    id: 'dept-engineering',
    name: 'Engineering',
    code: 'ENG',
    costCenter: 'CC-1001',
    headId: 'usr-007',
    headName: 'Lisa Wong',
    budgetAmount: 18_500_000,
    userCount: 45,
  },
  {
    id: 'dept-sales',
    name: 'Sales',
    code: 'SAL',
    costCenter: 'CC-1002',
    headId: 'usr-006',
    headName: 'Tom Baker',
    budgetAmount: 12_200_000,
    userCount: 28,
  },
  {
    id: 'dept-marketing',
    name: 'Marketing',
    code: 'MKT',
    costCenter: 'CC-1003',
    headId: null,
    headName: null,
    budgetAmount: 8_100_000,
    userCount: 18,
  },
  {
    id: 'dept-finance',
    name: 'Finance & Accounting',
    code: 'FIN',
    costCenter: 'CC-1004',
    headId: null,
    headName: null,
    budgetAmount: 6_500_000,
    userCount: 14,
  },
  {
    id: 'dept-operations',
    name: 'Operations',
    code: 'OPS',
    costCenter: 'CC-1005',
    headId: null,
    headName: null,
    budgetAmount: 5_300_000,
    userCount: 22,
  },
  {
    id: 'dept-ga',
    name: 'G&A',
    code: 'GNA',
    costCenter: 'CC-1006',
    headId: null,
    headName: null,
    budgetAmount: 4_200_000,
    userCount: 10,
  },
];

export const entities: Entity[] = [
  {
    id: 'ent-us',
    name: 'US Parent',
    code: 'US',
    currency: 'USD',
    country: 'United States',
    isParent: true,
    parentId: null,
  },
  {
    id: 'ent-uk',
    name: 'UK Subsidiary',
    code: 'UK',
    currency: 'GBP',
    country: 'United Kingdom',
    isParent: false,
    parentId: 'ent-us',
  },
  {
    id: 'ent-de',
    name: 'DE Subsidiary',
    code: 'DE',
    currency: 'EUR',
    country: 'Germany',
    isParent: false,
    parentId: 'ent-us',
  },
];

export function getUserById(id: string): User | undefined {
  return users.find((u) => u.id === id);
}

export function getUserByEmail(email: string): User | undefined {
  return users.find((u) => u.email === email);
}

export function getUsersByDepartment(deptId: string): User[] {
  return users.filter((u) => u.departmentId === deptId);
}

export function getUsersByRole(role: User['role']): User[] {
  return users.filter((u) => u.role === role);
}
