// src/components/audit/AuditCompliancePanel.tsx
// Clio (Audit Muse) — Part 141 P0A-17 — Sticky sidebar with stats + report gen

import { useMemo } from 'react';
import { FileText, Users, Hash, ListChecks, Shield, ShieldCheck } from 'lucide-react';
import {
  useAuditTrailStore,
  selectStats,
  type AuditOperation,
  type ApprovalStatus,
} from '@/store/auditTrailStore';
import { Button } from '@/components/ui/Button';

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function AuditCompliancePanel(): JSX.Element {
  const stats = useAuditTrailStore(selectStats);

  const totalEntries = stats.total;

  const operationRows = useMemo(() => {
    const ops: AuditOperation[] = ['write', 'update', 'delete', 'bulk'];
    return ops.map((op) => ({
      op,
      count: stats.operationCounts[op],
      pct: totalEntries > 0 ? (stats.operationCounts[op] / totalEntries) * 100 : 0,
    }));
  }, [stats.operationCounts, totalEntries]);

  const approvalRows = useMemo(() => {
    const statuses: ApprovalStatus[] = ['pending', 'approved', 'rejected', 'auto'];
    return statuses.map((s) => ({
      status: s,
      count: stats.approvalCounts[s],
      pct: totalEntries > 0 ? (stats.approvalCounts[s] / totalEntries) * 100 : 0,
    }));
  }, [stats.approvalCounts, totalEntries]);

  const generateComplianceReport = (): void => {
    const reportLines = [
      `# Audit Trail Compliance Report`,
      ``,
      `Generated: ${new Date().toISOString()}`,
      ``,
      `## Summary`,
      `- Total entries: ${stats.total}`,
      `- Unique users: ${stats.uniqueUsers}`,
      `- Unique cells: ${stats.uniqueCells}`,
      ``,
      `## Operation Breakdown`,
      ...operationRows.map((r) => `- ${r.op}: ${r.count} (${r.pct.toFixed(1)}%)`),
      ``,
      `## Approval Status Breakdown`,
      ...approvalRows.map((r) => `- ${r.status}: ${r.count} (${r.pct.toFixed(1)}%)`),
      ``,
      `## Top 10 Users by Activity`,
      ...stats.topUsers.map((u, i) => `${i + 1}. ${u.userId}: ${u.count} entries`),
      ``,
      `## Compliance Notes`,
      `- SOX (Sarbanes-Oxley): All financial entries retained for 7 years per Article 802`,
      `- GDPR Article 30: Records of Processing Activities (ROPA) maintained`,
      `- Article 17 (Right to erasure): Triggered via recordDelete('gdpr') source`,
      `- Article 15 (Right to access): Triggered via exportToCSV/exportToJSON`,
      ``,
      `Generated by Clio (Audit Muse) — Part 141 P0A-17 Audit Trail UI v0.2.1`,
    ];
    const reportContent = reportLines.join('\n');
    const blob = new Blob([reportContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `audit-trail-compliance-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <aside className="bg-white dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700 p-4 space-y-4 sticky top-4">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Compliance</h2>
        <FileText className="h-5 w-5 text-gray-400" />
      </div>

      {/* Stats cards */}
      <div className="grid grid-cols-3 gap-2">
        <div className="bg-blue-50 dark:bg-blue-900/30 rounded-md p-3 border border-blue-200 dark:border-blue-800">
          <div className="flex items-center gap-1 text-xs text-blue-700 dark:text-blue-300 font-medium">
            <ListChecks className="h-3 w-3" /> Total
          </div>
          <div className="text-2xl font-bold text-blue-900 dark:text-blue-100">{stats.total}</div>
        </div>
        <div className="bg-green-50 dark:bg-green-900/30 rounded-md p-3 border border-green-200 dark:border-green-800">
          <div className="flex items-center gap-1 text-xs text-green-700 dark:text-green-300 font-medium">
            <Users className="h-3 w-3" /> Users
          </div>
          <div className="text-2xl font-bold text-green-900 dark:text-green-100">
            {stats.uniqueUsers}
          </div>
        </div>
        <div className="bg-purple-50 dark:bg-purple-900/30 rounded-md p-3 border border-purple-200 dark:border-purple-800">
          <div className="flex items-center gap-1 text-xs text-purple-700 dark:text-purple-300 font-medium">
            <Hash className="h-3 w-3" /> Cells
          </div>
          <div className="text-2xl font-bold text-purple-900 dark:text-purple-100">
            {stats.uniqueCells}
          </div>
        </div>
      </div>

      {/* Operation breakdown bars */}
      <div>
        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">Operations</h3>
        <div className="space-y-1.5">
          {operationRows.map((r) => (
            <div key={r.op} className="flex items-center gap-2 text-xs">
              <span className="w-16 capitalize text-gray-600 dark:text-gray-400">{r.op}</span>
              <div className="flex-1 h-3 bg-gray-100 dark:bg-gray-800 rounded-full overflow-hidden">
                <div
                  className="h-full bg-blue-500"
                  style={{ width: `${r.pct}%` }}
                  aria-label={`${r.op}: ${r.pct.toFixed(1)}%`}
                />
              </div>
              <span className="w-10 text-right tabular-nums text-gray-700 dark:text-gray-300">
                {r.count}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Approval status breakdown */}
      <div>
        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">
          Approval Status
        </h3>
        <div className="space-y-1.5">
          {approvalRows.map((r) => (
            <div key={r.status} className="flex items-center gap-2 text-xs">
              <span className="w-16 capitalize text-gray-600 dark:text-gray-400">
                {r.status}
              </span>
              <div className="flex-1 h-3 bg-gray-100 dark:bg-gray-800 rounded-full overflow-hidden">
                <div
                  className={
                    r.status === 'approved'
                      ? 'h-full bg-green-500'
                      : r.status === 'rejected'
                        ? 'h-full bg-red-500'
                        : r.status === 'pending'
                          ? 'h-full bg-yellow-500'
                          : 'h-full bg-gray-400'
                  }
                  style={{ width: `${r.pct}%` }}
                  aria-label={`${r.status}: ${r.pct.toFixed(1)}%`}
                />
              </div>
              <span className="w-10 text-right tabular-nums text-gray-700 dark:text-gray-300">
                {r.count}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Top 10 users */}
      <div>
        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">
          Top 10 Users
        </h3>
        <ul className="space-y-1 text-xs">
          {stats.topUsers.length === 0 ? (
            <li className="text-gray-400 italic">No entries yet</li>
          ) : (
            stats.topUsers.map((u) => (
              <li
                key={u.userId}
                className="flex items-center justify-between gap-2 py-1 px-2 rounded hover:bg-gray-50 dark:hover:bg-gray-800"
              >
                <span className="truncate text-gray-700 dark:text-gray-300">{u.userId}</span>
                <span className="tabular-nums font-semibold text-gray-900 dark:text-gray-100">
                  {u.count}
                </span>
              </li>
            ))
          )}
        </ul>
      </div>

      {/* Compliance report generator */}
      <div className="pt-2 border-t border-gray-200 dark:border-gray-700">
        <Button
          variant="primary"
          size="sm"
          onClick={generateComplianceReport}
          className="w-full"
          aria-label="Generate compliance report"
        >
          <ShieldCheck className="h-4 w-4 mr-1" /> Generate Compliance Report
        </Button>
        <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">
          SOX Article 802 (7-year retention), GDPR Article 30 (ROPA), Article 17 (erasure),
          Article 15 (access). Coupled with{' '}
          <a
            href="/audit/gdpr-consent"
            className="text-blue-600 dark:text-blue-400 hover:underline"
          >
            GDPR consent registry
          </a>
          .
        </p>
      </div>

      <div className="text-xs text-gray-500 dark:text-gray-400 pt-2 border-t border-gray-200 dark:border-gray-700">
        <Shield className="h-3 w-3 inline mr-1" />
        Clio Part 141 P0A-17 v0.2.1
      </div>
    </aside>
  );
}