// =============================================================================
// Banking Sector Template
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from './types';
import { makePeriodRange } from './types';

export function buildBankingTemplate(): FPTemplate {
  const drivers: DriverDefinition[] = [
    {
      id: 'bank-fed-funds',
      name: 'Fed Funds Rate',
      description: 'Federal funds target rate',
      unit: 'percentage',
      defaultValue: 4.5,
      minValue: 0,
      maxValue: 20,
      step: 0.25,
      category: 'Rates',
      tags: ['rates', 'monetary'],
    },
    {
      id: 'bank-loan-yield',
      name: 'Loan Yield',
      description: 'Weighted average yield on loan portfolio',
      unit: 'percentage',
      defaultValue: 6.5,
      minValue: 0,
      maxValue: 30,
      step: 0.25,
      category: 'Rates',
      tags: ['yield'],
    },
    {
      id: 'bank-deposit-cost',
      name: 'Cost of Deposits',
      description: 'Weighted average cost of deposits',
      unit: 'percentage',
      defaultValue: 2.0,
      minValue: 0,
      maxValue: 15,
      step: 0.25,
      category: 'Rates',
      tags: ['deposits'],
    },
    {
      id: 'bank-loan-volume',
      name: 'Loan Portfolio',
      description: 'Total outstanding loans',
      unit: 'currency',
      defaultValue: 5000000000,
      minValue: 0,
      maxValue: 1000000000000,
      step: 100000000,
      category: 'Volume',
      tags: ['loans'],
    },
    {
      id: 'bank-deposit-volume',
      name: 'Deposit Base',
      description: 'Total deposits outstanding',
      unit: 'currency',
      defaultValue: 6000000000,
      minValue: 0,
      maxValue: 1000000000000,
      step: 100000000,
      category: 'Volume',
      tags: ['deposits'],
    },
    {
      id: 'bank-npl-ratio',
      name: 'Non-Performing Loan Ratio',
      description: 'NPLs as % of total loans',
      unit: 'percentage',
      defaultValue: 1.2,
      minValue: 0,
      maxValue: 20,
      step: 0.1,
      category: 'Credit Quality',
      tags: ['npl', 'credit'],
    },
    {
      id: 'bank-provision-rate',
      name: 'Provision Rate',
      description: 'Loan loss provision as % of loans',
      unit: 'percentage',
      defaultValue: 0.5,
      minValue: 0,
      maxValue: 10,
      step: 0.05,
      category: 'Credit Quality',
      tags: ['provision'],
    },
    {
      id: 'bank-capital-ratio',
      name: 'Tier 1 Capital Ratio',
      description: 'Tier 1 capital as % of risk-weighted assets',
      unit: 'percentage',
      defaultValue: 12,
      minValue: 0,
      maxValue: 30,
      step: 0.5,
      category: 'Capital',
      tags: ['capital', 'basel'],
    },
    {
      id: 'bank-efficiency-ratio',
      name: 'Efficiency Ratio',
      description: 'Operating expense as % of revenue',
      unit: 'percentage',
      defaultValue: 55,
      minValue: 20,
      maxValue: 100,
      step: 1,
      category: 'Efficiency',
      tags: ['efficiency'],
    },
    {
      id: 'bank-noninterest-income',
      name: 'Non-Interest Income Pct',
      description: 'Non-interest income as % of average assets',
      unit: 'percentage',
      defaultValue: 1.5,
      minValue: 0,
      maxValue: 10,
      step: 0.1,
      category: 'Revenue',
      tags: ['fees'],
    },
  ];

  const accounts: AccountDefinition[] = [
    {
      id: 'bank-net-interest-income',
      name: 'Net Interest Income',
      parentId: null,
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'NII',
      isCalculated: true,
    },
    {
      id: 'bank-interest-income',
      name: 'Interest Income',
      parentId: 'bank-net-interest-income',
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'Interest on loans',
      isCalculated: true,
    },
    {
      id: 'bank-interest-expense',
      name: 'Interest Expense',
      parentId: 'bank-net-interest-income',
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Interest on deposits',
      isCalculated: true,
    },
    {
      id: 'bank-nim',
      name: 'Net Interest Margin',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'NIM percentage',
      isCalculated: true,
    },
    {
      id: 'bank-npl-amount',
      name: 'Non-Performing Loans',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'NPL balance',
      isCalculated: true,
    },
    {
      id: 'bank-provision',
      name: 'Loan Loss Provision',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Credit provision',
      isCalculated: true,
    },
    {
      id: 'bank-noninterest-rev',
      name: 'Non-Interest Income',
      parentId: null,
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'Fee income',
      isCalculated: true,
    },
    {
      id: 'bank-total-revenue',
      name: 'Total Revenue',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'NII + Non-interest',
      isCalculated: true,
    },
    {
      id: 'bank-operating-expense',
      name: 'Operating Expense',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Total OpEx',
      isCalculated: true,
    },
    {
      id: 'bank-pretax-income',
      name: 'Pre-Tax Income',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Pretax profit',
      isCalculated: true,
    },
    {
      id: 'bank-net-income',
      name: 'Net Income',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Bottom line',
      isCalculated: true,
    },
    {
      id: 'bank-tier1-capital',
      name: 'Tier 1 Capital',
      parentId: null,
      accountType: 'equity',
      debitSide: 'credit',
      description: 'T1 capital',
      isCalculated: true,
    },
    {
      id: 'bank-roa',
      name: 'Return on Assets',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'ROA',
      isCalculated: true,
    },
    {
      id: 'bank-roe',
      name: 'Return on Equity',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'ROE',
      isCalculated: true,
    },
  ];

  const cascadeRules: CascadeRuleDefinition[] = [
    {
      id: 'bank-c-1',
      driverId: 'bank-loan-yield',
      targetAccountId: 'bank-interest-income',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Yield drives interest income',
    },
    {
      id: 'bank-c-2',
      driverId: 'bank-loan-volume',
      targetAccountId: 'bank-interest-income',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Loan volume drives interest income',
    },
    {
      id: 'bank-c-3',
      driverId: 'bank-deposit-cost',
      targetAccountId: 'bank-interest-expense',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Deposit cost drives interest expense',
    },
    {
      id: 'bank-c-4',
      driverId: 'bank-deposit-volume',
      targetAccountId: 'bank-interest-expense',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Deposit volume drives interest expense',
    },
    {
      id: 'bank-c-5',
      driverId: 'bank-npl-ratio',
      targetAccountId: 'bank-npl-amount',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'NPL ratio drives NPL amount',
    },
    {
      id: 'bank-c-6',
      driverId: 'bank-provision-rate',
      targetAccountId: 'bank-provision',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Provision rate drives provision',
    },
    {
      id: 'bank-c-7',
      driverId: 'bank-efficiency-ratio',
      targetAccountId: 'bank-operating-expense',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Efficiency ratio drives OpEx',
    },
  ];

  return {
    id: 'tpl-banking',
    name: 'Banking NIM Model',
    description:
      'Banking net interest margin model with rate and volume drivers, credit quality metrics, capital adequacy ratios, and profitability analysis.',
    industry: 'Banking',
    category: 'balance-sheet',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'quarterly'),
    tags: ['banking', 'nim', 'npl', 'capital', 'roa', 'roe', 'credit'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
