// =============================================================================
// Energy Sector Template
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from './types';
import { makePeriodRange } from './types';

export function buildEnergyTemplate(): FPTemplate {
  const drivers: DriverDefinition[] = [
    {
      id: 'en-production-volume',
      name: 'Production Volume',
      description: 'Barrels of oil equivalent per day',
      unit: 'count',
      defaultValue: 50000,
      minValue: 0,
      maxValue: 1000000,
      step: 1000,
      category: 'Production',
      tags: ['production', 'volume'],
    },
    {
      id: 'en-commodity-price',
      name: 'Commodity Price',
      description: 'Price per barrel of oil equivalent',
      unit: 'currency',
      defaultValue: 75,
      minValue: 0,
      maxValue: 200,
      step: 1,
      category: 'Pricing',
      tags: ['price', 'commodity'],
    },
    {
      id: 'en-royalty-rate',
      name: 'Royalty Rate',
      description: 'Royalty payments as % of revenue',
      unit: 'percentage',
      defaultValue: 12.5,
      minValue: 0,
      maxValue: 30,
      step: 0.5,
      category: 'Cost',
      tags: ['royalty'],
    },
    {
      id: 'en-lifting-cost',
      name: 'Lifting Cost per BOE',
      description: 'Operating cost per barrel produced',
      unit: 'currency',
      defaultValue: 12,
      minValue: 0,
      maxValue: 100,
      step: 0.5,
      category: 'Cost',
      tags: ['lifting', 'opex'],
    },
    {
      id: 'en-dda-rate',
      name: 'DD&A Rate',
      description: 'Depletion, depreciation, amortization rate',
      unit: 'percentage',
      defaultValue: 15,
      minValue: 0,
      maxValue: 50,
      step: 1,
      category: 'DD&A',
      tags: ['depletion', 'depreciation'],
    },
    {
      id: 'en-decline-rate',
      name: 'Production Decline Rate',
      description: 'Annual production decline rate',
      unit: 'percentage',
      defaultValue: 8,
      minValue: 0,
      maxValue: 40,
      step: 1,
      category: 'Production',
      tags: ['decline', 'reserves'],
    },
    {
      id: 'en-capex-budget',
      name: 'CapEx Budget',
      description: 'Annual capital expenditure budget',
      unit: 'currency',
      defaultValue: 200000000,
      minValue: 0,
      maxValue: 50000000000,
      step: 1000000,
      category: 'CapEx',
      tags: ['capex', 'drilling'],
    },
    {
      id: 'en-tax-rate',
      name: 'Effective Tax Rate',
      description: 'Corporate effective tax rate',
      unit: 'percentage',
      defaultValue: 25,
      minValue: 0,
      maxValue: 50,
      step: 1,
      category: 'Tax',
      tags: ['tax'],
    },
  ];

  const accounts: AccountDefinition[] = [
    {
      id: 'en-revenue',
      name: 'Total Revenue',
      parentId: null,
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'Total commodity revenue',
      isCalculated: true,
    },
    {
      id: 'en-royalty-expense',
      name: 'Royalty Expense',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Royalty payments',
      isCalculated: true,
    },
    {
      id: 'en-net-revenue',
      name: 'Net Revenue',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Revenue minus royalties',
      isCalculated: true,
    },
    {
      id: 'en-lifting-cost-total',
      name: 'Total Lifting Cost',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Total operating costs',
      isCalculated: true,
    },
    {
      id: 'en-dda',
      name: 'DD&A Expense',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Depletion, depreciation, amortization',
      isCalculated: true,
    },
    {
      id: 'en-operating-income',
      name: 'Operating Income',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Net revenue minus lifting and DD&A',
      isCalculated: true,
    },
    {
      id: 'en-capex',
      name: 'Capital Expenditures',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Total CapEx',
      isCalculated: true,
    },
    {
      id: 'en-pre-tax-income',
      name: 'Pre-Tax Income',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Income before taxes',
      isCalculated: true,
    },
    {
      id: 'en-tax-expense',
      name: 'Tax Expense',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Corporate tax',
      isCalculated: true,
    },
    {
      id: 'en-net-income',
      name: 'Net Income',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Bottom line',
      isCalculated: true,
    },
    {
      id: 'en-boe-per-day',
      name: 'BOE per Day',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'Daily production rate',
      isCalculated: true,
    },
    {
      id: 'en-boe-per-year',
      name: 'Annual BOE',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'Annual production volume',
      isCalculated: true,
    },
  ];

  const cascadeRules: CascadeRuleDefinition[] = [
    {
      id: 'en-c-1',
      driverId: 'en-production-volume',
      targetAccountId: 'en-revenue',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Volume drives revenue',
    },
    {
      id: 'en-c-2',
      driverId: 'en-commodity-price',
      targetAccountId: 'en-revenue',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Price drives revenue',
    },
    {
      id: 'en-c-3',
      driverId: 'en-royalty-rate',
      targetAccountId: 'en-royalty-expense',
      cascadeType: 'formula',
      impactType: 'replacement',
      weight: 1,
      formula: 'current * x / 100',
      description: 'Royalty rate drives royalty expense',
    },
    {
      id: 'en-c-4',
      driverId: 'en-lifting-cost',
      targetAccountId: 'en-lifting-cost-total',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Lifting cost per unit drives total',
    },
    {
      id: 'en-c-5',
      driverId: 'en-decline-rate',
      targetAccountId: 'en-boe-per-day',
      cascadeType: 'formula',
      impactType: 'replacement',
      weight: 1,
      formula: 'current * (1 - x / 100)',
      description: 'Decline rate reduces production',
    },
    {
      id: 'en-c-6',
      driverId: 'en-dda-rate',
      targetAccountId: 'en-dda',
      cascadeType: 'formula',
      impactType: 'replacement',
      weight: 1,
      formula: 'current * x / 100',
      description: 'DD&A rate drives depletion',
    },
  ];

  return {
    id: 'tpl-energy',
    name: 'Energy Upstream Model',
    description:
      'Upstream energy model with production volumes, commodity pricing, lifting costs, DD&A, and reserve economics for oil and gas companies.',
    industry: 'Energy',
    category: 'revenue',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: ['energy', 'oil', 'gas', 'upstream', 'production', 'commodity', 'reserves'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
