// =============================================================================
// Healthcare Sector Template
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from './types';
import { makePeriodRange } from './types';

export function buildHealthcareTemplate(): FPTemplate {
  const drivers: DriverDefinition[] = [
    {
      id: 'hc-member-months',
      name: 'Member Months',
      description: 'Total member months for the period',
      unit: 'absolute',
      defaultValue: 120000,
      minValue: 0,
      maxValue: 10000000,
      step: 1000,
      category: 'Membership',
      tags: ['members', 'enrollment'],
    },
    {
      id: 'hc-pmpm-premium',
      name: 'PMPM Premium',
      description: 'Per Member Per Month premium revenue',
      unit: 'currency',
      defaultValue: 450,
      minValue: 0,
      maxValue: 5000,
      step: 5,
      category: 'Revenue',
      tags: ['premium', 'pmpm'],
    },
    {
      id: 'hc-utilization',
      name: 'Inpatient Utilization',
      description: 'Inpatient admissions per 1000 members',
      unit: 'ratio',
      defaultValue: 65,
      minValue: 0,
      maxValue: 200,
      step: 1,
      category: 'Utilization',
      tags: ['utilization', 'admits'],
    },
    {
      id: 'hc-avg-length-stay',
      name: 'Average Length of Stay',
      description: 'Average days per inpatient admission',
      unit: 'days',
      defaultValue: 4.5,
      minValue: 0,
      maxValue: 30,
      step: 0.5,
      category: 'Utilization',
      tags: ['alos'],
    },
    {
      id: 'hc-unit-cost',
      name: 'Per Diem Cost',
      description: 'Cost per inpatient day',
      unit: 'currency',
      defaultValue: 2500,
      minValue: 0,
      maxValue: 50000,
      step: 50,
      category: 'Cost',
      tags: ['cost', 'per diem'],
    },
    {
      id: 'hc-risk-adj',
      name: 'Risk Adjustment Factor',
      description: 'Risk score adjustment for member acuity',
      unit: 'index',
      defaultValue: 1.0,
      minValue: 0.5,
      maxValue: 3.0,
      step: 0.05,
      category: 'Risk',
      tags: ['risk', 'hcc'],
    },
    {
      id: 'hc-admin-cost',
      name: 'Admin Cost PMPM',
      description: 'Administrative cost per member per month',
      unit: 'currency',
      defaultValue: 35,
      minValue: 0,
      maxValue: 500,
      step: 1,
      category: 'Admin',
      tags: ['admin'],
    },
    {
      id: 'hc-medical-loss-ratio',
      name: 'Target MLR',
      description: 'Target medical loss ratio',
      unit: 'percentage',
      defaultValue: 82,
      minValue: 60,
      maxValue: 95,
      step: 1,
      category: 'Margin',
      tags: ['mlr'],
    },
  ];

  const accounts: AccountDefinition[] = [
    {
      id: 'hc-premium-revenue',
      name: 'Premium Revenue',
      parentId: null,
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'Total premium income',
      isCalculated: true,
    },
    {
      id: 'hc-medical-cost',
      name: 'Total Medical Cost',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Total claims expense',
      isCalculated: true,
    },
    {
      id: 'hc-ip-cost',
      name: 'Inpatient Cost',
      parentId: 'hc-medical-cost',
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Inpatient claims',
      isCalculated: true,
    },
    {
      id: 'hc-op-cost',
      name: 'Outpatient Cost',
      parentId: 'hc-medical-cost',
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Outpatient claims',
      isCalculated: false,
    },
    {
      id: 'hc-pharmacy-cost',
      name: 'Pharmacy Cost',
      parentId: 'hc-medical-cost',
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Pharmacy claims',
      isCalculated: false,
    },
    {
      id: 'hc-professional-cost',
      name: 'Professional Cost',
      parentId: 'hc-medical-cost',
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Physician services',
      isCalculated: false,
    },
    {
      id: 'hc-mlr',
      name: 'Medical Loss Ratio',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'MLR percentage',
      isCalculated: true,
    },
    {
      id: 'hc-admin-expense',
      name: 'Administrative Expense',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Total admin costs',
      isCalculated: true,
    },
    {
      id: 'hc-underwriting-income',
      name: 'Underwriting Income',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Premium minus costs',
      isCalculated: true,
    },
    {
      id: 'hc-net-income',
      name: 'Net Income',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Bottom line',
      isCalculated: true,
    },
    {
      id: 'hc-pmpm-medical',
      name: 'PMPM Medical Cost',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'Medical cost per member',
      isCalculated: true,
    },
    {
      id: 'hc-ip-admits',
      name: 'IP Admissions',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'Total admissions',
      isCalculated: true,
    },
  ];

  const cascadeRules: CascadeRuleDefinition[] = [
    {
      id: 'hc-c-1',
      driverId: 'hc-member-months',
      targetAccountId: 'hc-premium-revenue',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Members drive premium revenue',
    },
    {
      id: 'hc-c-2',
      driverId: 'hc-pmpm-premium',
      targetAccountId: 'hc-premium-revenue',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'PMPM drives premium revenue',
    },
    {
      id: 'hc-c-3',
      driverId: 'hc-utilization',
      targetAccountId: 'hc-ip-cost',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Utilization drives IP cost',
    },
    {
      id: 'hc-c-4',
      driverId: 'hc-unit-cost',
      targetAccountId: 'hc-ip-cost',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Unit cost drives IP cost',
    },
    {
      id: 'hc-c-5',
      driverId: 'hc-risk-adj',
      targetAccountId: 'hc-ip-cost',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Risk adjustment drives IP cost',
    },
    {
      id: 'hc-c-6',
      driverId: 'hc-admin-cost',
      targetAccountId: 'hc-admin-expense',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Admin PMPM drives admin expense',
    },
  ];

  return {
    id: 'tpl-healthcare',
    name: 'Healthcare PMPM Model',
    description:
      'Healthcare payer model with member months, utilization management, PMPM cost analysis, risk adjustment, and medical loss ratio tracking.',
    industry: 'Healthcare',
    category: 'opex',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: ['healthcare', 'payer', 'pmpm', 'mlr', 'utilization', 'risk adjustment'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
