// =============================================================================
// Insurance Sector Template
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from './types';
import { makePeriodRange } from './types';

export function buildInsuranceTemplate(): FPTemplate {
  const drivers: DriverDefinition[] = [
    {
      id: 'ins-gwp',
      name: 'Gross Written Premium',
      description: 'Total premiums written',
      unit: 'currency',
      defaultValue: 500000000,
      minValue: 0,
      maxValue: 50000000000,
      step: 1000000,
      category: 'Premium',
      tags: ['premium', 'gwp'],
    },
    {
      id: 'ins-loss-ratio',
      name: 'Loss Ratio',
      description: 'Claims paid as % of earned premium',
      unit: 'percentage',
      defaultValue: 62,
      minValue: 30,
      maxValue: 120,
      step: 1,
      category: 'Claims',
      tags: ['loss', 'claims'],
    },
    {
      id: 'ins-expense-ratio',
      name: 'Expense Ratio',
      description: 'Operating expenses as % of written premium',
      unit: 'percentage',
      defaultValue: 28,
      minValue: 10,
      maxValue: 50,
      step: 1,
      category: 'Expenses',
      tags: ['expense'],
    },
    {
      id: 'ins-commission-rate',
      name: 'Commission Rate',
      description: 'Agent commissions as % of premium',
      unit: 'percentage',
      defaultValue: 12,
      minValue: 0,
      maxValue: 30,
      step: 0.5,
      category: 'Distribution',
      tags: ['commission'],
    },
    {
      id: 'ins-reserve-ratio',
      name: 'Reserve Ratio',
      description: 'Loss reserves as % of earned premium',
      unit: 'percentage',
      defaultValue: 80,
      minValue: 30,
      maxValue: 200,
      step: 5,
      category: 'Reserves',
      tags: ['reserves', 'ibnr'],
    },
    {
      id: 'ins-investment-yield',
      name: 'Investment Yield',
      description: 'Return on invested assets',
      unit: 'percentage',
      defaultValue: 3.5,
      minValue: 0,
      maxValue: 15,
      step: 0.25,
      category: 'Investment',
      tags: ['investment', 'float'],
    },
    {
      id: 'ins-retention-rate',
      name: 'Policy Retention Rate',
      description: 'Percentage of policies renewed',
      unit: 'percentage',
      defaultValue: 88,
      minValue: 50,
      maxValue: 100,
      step: 1,
      category: 'Retention',
      tags: ['retention', 'renewal'],
    },
    {
      id: 'ins-combined-ratio-target',
      name: 'Target Combined Ratio',
      description: 'Target loss + expense ratio',
      unit: 'percentage',
      defaultValue: 95,
      minValue: 70,
      maxValue: 120,
      step: 1,
      category: 'Underwriting',
      tags: ['combined'],
    },
  ];

  const accounts: AccountDefinition[] = [
    {
      id: 'ins-gwp',
      name: 'Gross Written Premium',
      parentId: null,
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'Total premiums written',
      isCalculated: true,
    },
    {
      id: 'ins-earned-premium',
      name: 'Net Earned Premium',
      parentId: null,
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'Premium earned after reinsurance',
      isCalculated: true,
    },
    {
      id: 'ins-loss-expense',
      name: 'Loss & Loss Adjustment Expense',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Claims paid + LAE',
      isCalculated: true,
    },
    {
      id: 'ins-commission-expense',
      name: 'Commission Expense',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Agent commissions',
      isCalculated: true,
    },
    {
      id: 'ins-underwriting-expense',
      name: 'Underwriting Expense',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Operating expenses',
      isCalculated: true,
    },
    {
      id: 'ins-combined-ratio',
      name: 'Combined Ratio',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'Loss + expense ratio',
      isCalculated: true,
    },
    {
      id: 'ins-underwriting-income',
      name: 'Underwriting Income',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Premium minus all costs',
      isCalculated: true,
    },
    {
      id: 'ins-investment-income',
      name: 'Investment Income',
      parentId: null,
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'Return on float',
      isCalculated: true,
    },
    {
      id: 'ins-net-income',
      name: 'Net Income',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Bottom line',
      isCalculated: true,
    },
    {
      id: 'ins-loss-reserves',
      name: 'Loss Reserves',
      parentId: null,
      accountType: 'liability',
      debitSide: 'credit',
      description: 'Outstanding claims reserves',
      isCalculated: true,
    },
    {
      id: 'ins-policy-count',
      name: 'Policy Count',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'Total active policies',
      isCalculated: true,
    },
    {
      id: 'ins-avg-premium',
      name: 'Average Premium per Policy',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'GWP / Policy Count',
      isCalculated: true,
    },
  ];

  const cascadeRules: CascadeRuleDefinition[] = [
    {
      id: 'ins-c-1',
      driverId: 'ins-loss-ratio',
      targetAccountId: 'ins-loss-expense',
      cascadeType: 'formula',
      impactType: 'replacement',
      weight: 1,
      formula: 'current * x / 100',
      description: 'Loss ratio drives claims',
    },
    {
      id: 'ins-c-2',
      driverId: 'ins-gwp',
      targetAccountId: 'ins-gwp',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'GWP drives revenue',
    },
    {
      id: 'ins-c-3',
      driverId: 'ins-commission-rate',
      targetAccountId: 'ins-commission-expense',
      cascadeType: 'formula',
      impactType: 'replacement',
      weight: 1,
      formula: 'current * x / 100',
      description: 'Commission rate drives commission expense',
    },
    {
      id: 'ins-c-4',
      driverId: 'ins-expense-ratio',
      targetAccountId: 'ins-underwriting-expense',
      cascadeType: 'formula',
      impactType: 'replacement',
      weight: 1,
      formula: 'current * x / 100',
      description: 'Expense ratio drives underwriting expense',
    },
    {
      id: 'ins-c-5',
      driverId: 'ins-reserve-ratio',
      targetAccountId: 'ins-loss-reserves',
      cascadeType: 'formula',
      impactType: 'replacement',
      weight: 1,
      formula: 'current * x / 100',
      description: 'Reserve ratio drives reserves',
    },
    {
      id: 'ins-c-6',
      driverId: 'ins-retention-rate',
      targetAccountId: 'ins-policy-count',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Retention drives policy count',
    },
  ];

  return {
    id: 'tpl-insurance',
    name: 'Insurance Underwriting Model',
    description:
      'Property & casualty insurance model with combined ratio analysis, loss development, investment income, reserve adequacy, and policy retention tracking.',
    industry: 'Insurance',
    category: 'revenue',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'quarterly'),
    tags: [
      'insurance',
      'underwriting',
      'combined ratio',
      'loss ratio',
      'premium',
      'reserves',
      'float',
    ],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
