// =============================================================================
// Manufacturing Sector Template
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from './types';
import { makePeriodRange } from './types';

export function buildManufacturingTemplate(): FPTemplate {
  const drivers: DriverDefinition[] = [
    {
      id: 'mfg-material-cost',
      name: 'Raw Material Cost per Unit',
      description: 'Cost of raw materials per finished unit',
      unit: 'currency',
      defaultValue: 25,
      minValue: 0,
      maxValue: 10000,
      step: 0.5,
      category: 'COGS',
      tags: ['material', 'cost'],
    },
    {
      id: 'mfg-labor-rate',
      name: 'Direct Labor Rate',
      description: 'Hourly labor rate for production workers',
      unit: 'currency',
      defaultValue: 35,
      minValue: 10,
      maxValue: 200,
      step: 1,
      category: 'COGS',
      tags: ['labor', 'wages'],
    },
    {
      id: 'mfg-labor-hours',
      name: 'Labor Hours per Unit',
      description: 'Direct labor hours required per unit',
      unit: 'absolute',
      defaultValue: 0.5,
      minValue: 0,
      maxValue: 100,
      step: 0.1,
      category: 'COGS',
      tags: ['labor', 'efficiency'],
    },
    {
      id: 'mfg-overhead-rate',
      name: 'Overhead Allocation Rate',
      description: 'Manufacturing overhead as % of direct costs',
      unit: 'percentage',
      defaultValue: 40,
      minValue: 0,
      maxValue: 200,
      step: 5,
      category: 'COGS',
      tags: ['overhead'],
    },
    {
      id: 'mfg-yield',
      name: 'Production Yield',
      description: 'Percentage of good units produced',
      unit: 'percentage',
      defaultValue: 95,
      minValue: 50,
      maxValue: 100,
      step: 0.5,
      category: 'Production',
      tags: ['yield', 'quality'],
    },
    {
      id: 'mfg-volume',
      name: 'Production Volume',
      description: 'Units produced per month',
      unit: 'count',
      defaultValue: 10000,
      minValue: 0,
      maxValue: 1000000,
      step: 100,
      category: 'Production',
      tags: ['volume', 'capacity'],
    },
    {
      id: 'mfg-price',
      name: 'Selling Price per Unit',
      description: 'Average selling price per unit',
      unit: 'currency',
      defaultValue: 75,
      minValue: 0,
      maxValue: 100000,
      step: 1,
      category: 'Revenue',
      tags: ['price', 'revenue'],
    },
    {
      id: 'mfg-inventory-days',
      name: 'Inventory Days on Hand',
      description: 'Average days of inventory held',
      unit: 'days',
      defaultValue: 45,
      minValue: 0,
      maxValue: 365,
      step: 1,
      category: 'Working Capital',
      tags: ['inventory', 'turns'],
    },
  ];

  const accounts: AccountDefinition[] = [
    {
      id: 'mfg-revenue',
      name: 'Net Revenue',
      parentId: null,
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'Total product revenue',
      isCalculated: true,
    },
    {
      id: 'mfg-material-cost-total',
      name: 'Raw Material Cost',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Total material costs',
      isCalculated: true,
    },
    {
      id: 'mfg-labor-cost-total',
      name: 'Direct Labor Cost',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Total labor costs',
      isCalculated: true,
    },
    {
      id: 'mfg-overhead-total',
      name: 'Manufacturing Overhead',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Allocated overhead',
      isCalculated: true,
    },
    {
      id: 'mfg-cogs',
      name: 'Cost of Goods Sold',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Total COGS',
      isCalculated: true,
    },
    {
      id: 'mfg-gross-profit',
      name: 'Gross Profit',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Revenue minus COGS',
      isCalculated: true,
    },
    {
      id: 'mfg-gross-margin',
      name: 'Gross Margin %',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Gross margin percentage',
      isCalculated: true,
    },
    {
      id: 'mfg-good-units',
      name: 'Good Units Produced',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'Units passing quality',
      isCalculated: true,
    },
    {
      id: 'mfg-scrap-units',
      name: 'Scrap Units',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'Defective units',
      isCalculated: true,
    },
    {
      id: 'mfg-cost-per-unit',
      name: 'Fully Loaded Cost per Unit',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'Total cost per good unit',
      isCalculated: true,
    },
    {
      id: 'mfg-inventory-value',
      name: 'Inventory Value',
      parentId: null,
      accountType: 'asset',
      debitSide: 'debit',
      description: 'On-hand inventory value',
      isCalculated: true,
    },
    {
      id: 'mfg-contribution-margin',
      name: 'Contribution Margin',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Price minus variable cost',
      isCalculated: true,
    },
  ];

  const cascadeRules: CascadeRuleDefinition[] = [
    {
      id: 'mfg-c-1',
      driverId: 'mfg-material-cost',
      targetAccountId: 'mfg-material-cost-total',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Material cost drives total material',
    },
    {
      id: 'mfg-c-2',
      driverId: 'mfg-labor-rate',
      targetAccountId: 'mfg-labor-cost-total',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Labor rate drives total labor',
    },
    {
      id: 'mfg-c-3',
      driverId: 'mfg-overhead-rate',
      targetAccountId: 'mfg-overhead-total',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'OH rate drives total overhead',
    },
    {
      id: 'mfg-c-4',
      driverId: 'mfg-yield',
      targetAccountId: 'mfg-good-units',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Yield drives good units',
    },
    {
      id: 'mfg-c-5',
      driverId: 'mfg-volume',
      targetAccountId: 'mfg-revenue',
      cascadeType: 'weighted',
      impactType: 'additive',
      weight: 1,
      description: 'Volume drives revenue',
    },
    {
      id: 'mfg-c-6',
      driverId: 'mfg-price',
      targetAccountId: 'mfg-revenue',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Price drives revenue',
    },
    {
      id: 'mfg-c-7',
      driverId: 'mfg-inventory-days',
      targetAccountId: 'mfg-inventory-value',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Days drives inventory value',
    },
  ];

  return {
    id: 'tpl-manufacturing',
    name: 'Manufacturing COGS Model',
    description:
      'Manufacturing cost model with material costs, direct labor, overhead allocation, production yield, and breakeven analysis.',
    industry: 'Manufacturing',
    category: 'cogs',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: ['manufacturing', 'cogs', 'materials', 'labor', 'overhead', 'yield', 'production'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
