// =============================================================================
// Real Estate Sector Template
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from './types';
import { makePeriodRange } from './types';

export function buildRealEstateTemplate(): FPTemplate {
  const drivers: DriverDefinition[] = [
    {
      id: 're-occupancy-rate',
      name: 'Occupancy Rate',
      description: 'Percentage of units occupied',
      unit: 'percentage',
      defaultValue: 93,
      minValue: 50,
      maxValue: 100,
      step: 0.5,
      category: 'Occupancy',
      tags: ['occupancy', 'vacancy'],
    },
    {
      id: 're-avg-rent',
      name: 'Average Rent per Unit',
      description: 'Monthly rent per unit',
      unit: 'currency',
      defaultValue: 1800,
      minValue: 0,
      maxValue: 50000,
      step: 50,
      category: 'Revenue',
      tags: ['rent', 'pricing'],
    },
    {
      id: 're-unit-count',
      name: 'Total Units',
      description: 'Total rentable units in portfolio',
      unit: 'count',
      defaultValue: 200,
      minValue: 0,
      maxValue: 50000,
      step: 10,
      category: 'Portfolio',
      tags: ['units', 'portfolio'],
    },
    {
      id: 're-rent-escalation',
      name: 'Annual Rent Escalation',
      description: 'Annual rent increase percentage',
      unit: 'percentage',
      defaultValue: 3,
      minValue: 0,
      maxValue: 15,
      step: 0.5,
      category: 'Revenue',
      tags: ['escalation', 'growth'],
    },
    {
      id: 're-operating-expense-ratio',
      name: 'Operating Expense Ratio',
      description: 'Operating expenses as % of revenue',
      unit: 'percentage',
      defaultValue: 42,
      minValue: 20,
      maxValue: 70,
      step: 1,
      category: 'Expenses',
      tags: ['opex', 'noi'],
    },
    {
      id: 're-cap-rate',
      name: 'Cap Rate',
      description: 'Capitalization rate for valuation',
      unit: 'percentage',
      defaultValue: 5.5,
      minValue: 2,
      maxValue: 15,
      step: 0.25,
      category: 'Valuation',
      tags: ['cap rate', 'valuation'],
    },
    {
      id: 're-vacancy-loss',
      name: 'Vacancy Loss Rate',
      description: 'Revenue loss from vacancy',
      unit: 'percentage',
      defaultValue: 5,
      minValue: 0,
      maxValue: 30,
      step: 0.5,
      category: 'Occupancy',
      tags: ['vacancy', 'loss'],
    },
    {
      id: 're-capex-psf',
      name: 'CapEx per Square Foot',
      description: 'Capital expenditure per square foot',
      unit: 'currency',
      defaultValue: 5,
      minValue: 0,
      maxValue: 100,
      step: 0.5,
      category: 'CapEx',
      tags: ['capex', 'maintenance'],
    },
  ];

  const accounts: AccountDefinition[] = [
    {
      id: 're-gross-revenue',
      name: 'Gross Potential Revenue',
      parentId: null,
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'Max revenue at 100% occupancy',
      isCalculated: true,
    },
    {
      id: 're-vacancy-loss',
      name: 'Vacancy Loss',
      parentId: null,
      accountType: 'revenue',
      debitSide: 'debit',
      description: 'Revenue lost to vacancy',
      isCalculated: true,
    },
    {
      id: 're-effective-revenue',
      name: 'Effective Revenue',
      parentId: null,
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'Revenue after vacancy',
      isCalculated: true,
    },
    {
      id: 're-operating-expense',
      name: 'Operating Expense',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Total property operating costs',
      isCalculated: true,
    },
    {
      id: 're-noi',
      name: 'Net Operating Income',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'NOI',
      isCalculated: true,
    },
    {
      id: 're-noi-margin',
      name: 'NOI Margin',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'NOI as % of revenue',
      isCalculated: true,
    },
    {
      id: 're-capex',
      name: 'Capital Expenditures',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Total CapEx',
      isCalculated: true,
    },
    {
      id: 're-cash-flow',
      name: 'Free Cash Flow',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'NOI minus CapEx',
      isCalculated: true,
    },
    {
      id: 're-property-value',
      name: 'Implied Property Value',
      parentId: null,
      accountType: 'asset',
      debitSide: 'debit',
      description: 'NOI / Cap Rate',
      isCalculated: true,
    },
    {
      id: 're-rent-per-sqft',
      name: 'Rent per Square Foot',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Annual rent per sqft',
      isCalculated: true,
    },
    {
      id: 're-occupied-units',
      name: 'Occupied Units',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'Units currently occupied',
      isCalculated: true,
    },
    {
      id: 're-revenue-per-unit',
      name: 'Revenue per Unit',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Monthly revenue per unit',
      isCalculated: true,
    },
  ];

  const cascadeRules: CascadeRuleDefinition[] = [
    {
      id: 're-c-1',
      driverId: 're-avg-rent',
      targetAccountId: 're-gross-revenue',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Average rent drives gross revenue',
    },
    {
      id: 're-c-2',
      driverId: 're-unit-count',
      targetAccountId: 're-gross-revenue',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Unit count drives gross revenue',
    },
    {
      id: 're-c-3',
      driverId: 're-occupancy-rate',
      targetAccountId: 're-occupied-units',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Occupancy drives occupied units',
    },
    {
      id: 're-c-4',
      driverId: 're-vacancy-loss',
      targetAccountId: 're-vacancy-loss',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Vacancy rate drives loss',
    },
    {
      id: 're-c-5',
      driverId: 're-operating-expense-ratio',
      targetAccountId: 're-operating-expense',
      cascadeType: 'formula',
      impactType: 'replacement',
      weight: 1,
      formula: 'current * x / 100',
      description: 'OER drives operating expenses',
    },
    {
      id: 're-c-6',
      driverId: 're-cap-rate',
      targetAccountId: 're-property-value',
      cascadeType: 'formula',
      impactType: 'replacement',
      weight: 1,
      formula: 'x > 0 ? current / (x / 100) : 0',
      description: 'Cap rate drives property value',
    },
  ];

  return {
    id: 'tpl-real-estate',
    name: 'Real Estate Portfolio Model',
    description:
      'Commercial real estate model with occupancy, NOI, cap rate valuation, operating expense ratios, and cash flow analysis.',
    industry: 'Real Estate',
    category: 'cashflow',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: ['real estate', 'noi', 'cap rate', 'occupancy', 'property', 'valuation', 'cash flow'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
