// =============================================================================
// Retail Sector Template
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from './types';
import { makePeriodRange } from './types';

export function buildRetailTemplate(): FPTemplate {
  const drivers: DriverDefinition[] = [
    {
      id: 'ret-same-store-sales',
      name: 'Same-Store Sales Growth',
      description: 'Year-over-year sales growth for existing stores',
      unit: 'percentage',
      defaultValue: 3,
      minValue: -30,
      maxValue: 50,
      step: 0.5,
      category: 'Revenue',
      tags: ['comps', 'organic'],
    },
    {
      id: 'ret-traffic',
      name: 'Store Traffic',
      description: 'Monthly customer visits per store',
      unit: 'count',
      defaultValue: 15000,
      minValue: 0,
      maxValue: 500000,
      step: 100,
      category: 'Traffic',
      tags: ['footfall'],
    },
    {
      id: 'ret-conversion',
      name: 'Conversion Rate',
      description: 'Percentage of visitors who purchase',
      unit: 'percentage',
      defaultValue: 22,
      minValue: 0,
      maxValue: 100,
      step: 0.5,
      category: 'Sales',
      tags: ['conversion'],
    },
    {
      id: 'ret-basket-size',
      name: 'Average Basket Size',
      description: 'Average transaction value',
      unit: 'currency',
      defaultValue: 65,
      minValue: 0,
      maxValue: 10000,
      step: 1,
      category: 'Revenue',
      tags: ['atv', 'ticket'],
    },
    {
      id: 'ret-inventory-turns',
      name: 'Inventory Turns',
      description: 'Annual inventory turnover ratio',
      unit: 'ratio',
      defaultValue: 6,
      minValue: 0,
      maxValue: 52,
      step: 0.5,
      category: 'Inventory',
      tags: ['turns'],
    },
    {
      id: 'ret-store-count',
      name: 'Store Count',
      description: 'Number of operating stores',
      unit: 'count',
      defaultValue: 25,
      minValue: 0,
      maxValue: 10000,
      step: 1,
      category: 'Operations',
      tags: ['stores'],
    },
    {
      id: 'ret-rent-psf',
      name: 'Rent per Square Foot',
      description: 'Annual rent cost per square foot',
      unit: 'currency',
      defaultValue: 35,
      minValue: 0,
      maxValue: 500,
      step: 1,
      category: 'Occupancy',
      tags: ['rent'],
    },
    {
      id: 'ret-markup',
      name: 'Markup Percentage',
      description: 'Gross markup on cost of goods',
      unit: 'percentage',
      defaultValue: 55,
      minValue: 0,
      maxValue: 500,
      step: 1,
      category: 'Margin',
      tags: ['markup', 'pricing'],
    },
  ];

  const accounts: AccountDefinition[] = [
    {
      id: 'ret-total-revenue',
      name: 'Total Revenue',
      parentId: null,
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'Total retail sales',
      isCalculated: true,
    },
    {
      id: 'ret-transactions',
      name: 'Transaction Count',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'Total transactions',
      isCalculated: true,
    },
    {
      id: 'ret-cogs',
      name: 'Cost of Goods Sold',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Product cost',
      isCalculated: true,
    },
    {
      id: 'ret-gross-profit',
      name: 'Gross Profit',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Revenue minus COGS',
      isCalculated: true,
    },
    {
      id: 'ret-shrinkage',
      name: 'Shrinkage Expense',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Inventory loss',
      isCalculated: true,
    },
    {
      id: 'ret-occupancy',
      name: 'Occupancy Cost',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Total rent expense',
      isCalculated: true,
    },
    {
      id: 'ret-payroll',
      name: 'Store Payroll',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Labor costs',
      isCalculated: false,
    },
    {
      id: 'ret-store-profit',
      name: 'Store-Level Profit',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Store contribution',
      isCalculated: true,
    },
    {
      id: 'ret-avg-inventory',
      name: 'Average Inventory',
      parentId: null,
      accountType: 'asset',
      debitSide: 'debit',
      description: 'Inventory on hand',
      isCalculated: true,
    },
    {
      id: 'ret-sales-per-sqft',
      name: 'Sales per Square Foot',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Productivity metric',
      isCalculated: true,
    },
    {
      id: 'ret-sales-per-store',
      name: 'Sales per Store',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Average store revenue',
      isCalculated: true,
    },
  ];

  const cascadeRules: CascadeRuleDefinition[] = [
    {
      id: 'ret-c-1',
      driverId: 'ret-traffic',
      targetAccountId: 'ret-transactions',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Traffic drives transactions',
    },
    {
      id: 'ret-c-2',
      driverId: 'ret-conversion',
      targetAccountId: 'ret-transactions',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Conversion drives transactions',
    },
    {
      id: 'ret-c-3',
      driverId: 'ret-basket-size',
      targetAccountId: 'ret-total-revenue',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Basket size drives revenue',
    },
    {
      id: 'ret-c-4',
      driverId: 'ret-store-count',
      targetAccountId: 'ret-total-revenue',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Store count drives revenue',
    },
    {
      id: 'ret-c-5',
      driverId: 'ret-markup',
      targetAccountId: 'ret-cogs',
      cascadeType: 'formula',
      impactType: 'replacement',
      weight: 1,
      formula: 'current / (1 + x / 100)',
      description: 'Markup drives COGS',
    },
    {
      id: 'ret-c-6',
      driverId: 'ret-inventory-turns',
      targetAccountId: 'ret-avg-inventory',
      cascadeType: 'formula',
      impactType: 'replacement',
      weight: 1,
      formula: 'current / x',
      description: 'Turns drive inventory',
    },
  ];

  return {
    id: 'tpl-retail',
    name: 'Retail Store Model',
    description:
      'Multi-unit retail model with same-store sales, traffic/conversion funnel, basket analysis, inventory turns, and store-level profitability.',
    industry: 'Retail',
    category: 'revenue',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: ['retail', 'store', 'traffic', 'conversion', 'basket', 'inventory', 'occupancy'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
