// =============================================================================
// SaaS Sector Template
// =============================================================================

import type {
  FPTemplate,
  DriverDefinition,
  AccountDefinition,
  CascadeRuleDefinition,
} from './types';
import { makePeriodRange } from './types';

export function buildSaaSTemplate(): FPTemplate {
  const drivers: DriverDefinition[] = [
    {
      id: 'saas-mrr-growth',
      name: 'MRR Growth Rate',
      description: 'Monthly Recurring Revenue growth rate',
      unit: 'percentage',
      defaultValue: 8,
      minValue: -50,
      maxValue: 200,
      step: 1,
      category: 'Revenue',
      tags: ['mrr', 'growth', 'recurring'],
    },
    {
      id: 'saas-churn-rate',
      name: 'Monthly Churn Rate',
      description: 'Percentage of customers lost per month',
      unit: 'percentage',
      defaultValue: 3,
      minValue: 0,
      maxValue: 30,
      step: 0.5,
      category: 'Retention',
      tags: ['churn', 'retention'],
    },
    {
      id: 'saas-arpu',
      name: 'Average Revenue Per User',
      description: 'Average monthly revenue per customer',
      unit: 'currency',
      defaultValue: 500,
      minValue: 0,
      maxValue: 100000,
      step: 10,
      category: 'Revenue',
      tags: ['arpu', 'pricing'],
    },
    {
      id: 'saas-cac',
      name: 'Customer Acquisition Cost',
      description: 'Cost to acquire one new customer',
      unit: 'currency',
      defaultValue: 3000,
      minValue: 0,
      maxValue: 100000,
      step: 100,
      category: 'Sales',
      tags: ['cac', 'acquisition'],
    },
    {
      id: 'saas-gross-margin',
      name: 'Gross Margin',
      description: 'Gross margin percentage',
      unit: 'percentage',
      defaultValue: 75,
      minValue: 0,
      maxValue: 100,
      step: 1,
      category: 'Profitability',
      tags: ['margin', 'profitability'],
    },
    {
      id: 'saas-expansion-rate',
      name: 'Net Expansion Rate',
      description: 'Revenue expansion from existing customers',
      unit: 'percentage',
      defaultValue: 5,
      minValue: 0,
      maxValue: 100,
      step: 1,
      category: 'Revenue',
      tags: ['expansion', 'upsell'],
    },
    {
      id: 'saas-new-customers',
      name: 'New Customers per Month',
      description: 'Number of new customers acquired monthly',
      unit: 'count',
      defaultValue: 50,
      minValue: 0,
      maxValue: 10000,
      step: 5,
      category: 'Sales',
      tags: ['acquisition', 'growth'],
    },
    {
      id: 'saas-avg-contract',
      name: 'Average Contract Length',
      description: 'Average customer contract duration in months',
      unit: 'months',
      defaultValue: 12,
      minValue: 1,
      maxValue: 60,
      step: 1,
      category: 'Contract',
      tags: ['contract', 'retention'],
    },
  ];

  const accounts: AccountDefinition[] = [
    {
      id: 'saas-arr',
      name: 'Annual Recurring Revenue',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Total ARR',
      isCalculated: true,
    },
    {
      id: 'saas-mrr',
      name: 'Monthly Recurring Revenue',
      parentId: null,
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'Total MRR',
      isCalculated: true,
    },
    {
      id: 'saas-new-mrr',
      name: 'New MRR',
      parentId: 'saas-mrr',
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'MRR from new customers',
      isCalculated: false,
    },
    {
      id: 'saas-expansion-mrr',
      name: 'Expansion MRR',
      parentId: 'saas-mrr',
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'MRR from upsells',
      isCalculated: true,
    },
    {
      id: 'saas-churned-mrr',
      name: 'Churned MRR',
      parentId: 'saas-mrr',
      accountType: 'revenue',
      debitSide: 'debit',
      description: 'Lost MRR from churn',
      isCalculated: true,
    },
    {
      id: 'saas-net-mrr',
      name: 'Net New MRR',
      parentId: 'saas-mrr',
      accountType: 'revenue',
      debitSide: 'credit',
      description: 'Net MRR change',
      isCalculated: true,
    },
    {
      id: 'saas-cogs',
      name: 'Cost of Goods Sold',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Hosting, support costs',
      isCalculated: true,
    },
    {
      id: 'saas-gross-profit',
      name: 'Gross Profit',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'MRR minus COGS',
      isCalculated: true,
    },
    {
      id: 'saas-sm-expense',
      name: 'Sales & Marketing Expense',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'S&M spend',
      isCalculated: false,
    },
    {
      id: 'saas-rd-expense',
      name: 'R&D Expense',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Engineering costs',
      isCalculated: false,
    },
    {
      id: 'saas-ga-expense',
      name: 'G&A Expense',
      parentId: null,
      accountType: 'expense',
      debitSide: 'debit',
      description: 'Admin costs',
      isCalculated: false,
    },
    {
      id: 'saas-total-opex',
      name: 'Total Operating Expense',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'Total OpEx',
      isCalculated: true,
    },
    {
      id: 'saas-ebitda',
      name: 'EBITDA',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Operating income before D&A',
      isCalculated: true,
    },
    {
      id: 'saas-customer-count',
      name: 'Customer Count',
      parentId: null,
      accountType: 'memo',
      debitSide: 'debit',
      description: 'Total active customers',
      isCalculated: true,
    },
    {
      id: 'saas-ltv',
      name: 'Customer Lifetime Value',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'LTV per customer',
      isCalculated: true,
    },
    {
      id: 'saas-ltv-cac-ratio',
      name: 'LTV/CAC Ratio',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'Unit economics ratio',
      isCalculated: true,
    },
    {
      id: 'saas-nrr',
      name: 'Net Revenue Retention',
      parentId: null,
      accountType: 'memo',
      debitSide: 'credit',
      description: 'NRR percentage',
      isCalculated: true,
    },
  ];

  const cascadeRules: CascadeRuleDefinition[] = [
    {
      id: 'saas-c-1',
      driverId: 'saas-mrr-growth',
      targetAccountId: 'saas-new-mrr',
      cascadeType: 'formula',
      impactType: 'multiplicative',
      weight: 1,
      formula: 'x * prev / 100 + prev',
      description: 'MRR growth drives new MRR',
    },
    {
      id: 'saas-c-2',
      driverId: 'saas-churn-rate',
      targetAccountId: 'saas-churned-mrr',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Churn rate drives churned MRR',
    },
    {
      id: 'saas-c-3',
      driverId: 'saas-arpu',
      targetAccountId: 'saas-mrr',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 0.5,
      description: 'ARPU changes flow to MRR',
    },
    {
      id: 'saas-c-4',
      driverId: 'saas-expansion-rate',
      targetAccountId: 'saas-expansion-mrr',
      cascadeType: 'direct',
      impactType: 'multiplicative',
      weight: 1,
      description: 'Expansion rate drives expansion MRR',
    },
    {
      id: 'saas-c-5',
      driverId: 'saas-new-customers',
      targetAccountId: 'saas-new-mrr',
      cascadeType: 'weighted',
      impactType: 'additive',
      weight: 1,
      description: 'New customers drive new MRR',
    },
    {
      id: 'saas-c-6',
      driverId: 'saas-gross-margin',
      targetAccountId: 'saas-cogs',
      cascadeType: 'formula',
      impactType: 'replacement',
      weight: 1,
      formula: 'current * (100 - x) / 100',
      description: 'Margin changes drive COGS',
    },
    {
      id: 'saas-c-7',
      driverId: 'saas-cac',
      targetAccountId: 'saas-sm-expense',
      cascadeType: 'weighted',
      impactType: 'additive',
      weight: 1,
      description: 'CAC drives S&M expense',
    },
  ];

  return {
    id: 'tpl-saas-metrics',
    name: 'SaaS Metrics Model',
    description:
      'Comprehensive SaaS financial model with ARR, MRR, churn analysis, LTV/CAC, and net revenue retention. Ideal for subscription businesses tracking unit economics.',
    industry: 'SaaS',
    category: 'revenue',
    version: '1.0.0',
    drivers,
    cascadeRules,
    accounts,
    periods: makePeriodRange('2026-01', '2026-12', 'monthly'),
    tags: ['saas', 'subscription', 'arr', 'mrr', 'churn', 'ltv', 'cac', 'nrr'],
    isCustom: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  };
}
